### ISSUE TITLE
Can't build example project on Xcode 12.5

### ISSUE THREAD

**Issue by matheusmatos** [mrousavy/react-native-mmkv#102]
I just cloned the repository to know the project and when compiling the example there was an error:

```diff
- RCT-Folly/folly/synchronization/DistributedMutex-inl.h:1051:5: 'atomic_notify_one<unsigned long>' is unavailable
```

Maybe it's related with this conversation: https://stackoverflow.com/questions/66189325/xcode-throws-atomic-notify-oneunsigned-long-is-unavailable

**Comment by matheusmatos** [comment]
I was able to build with following changes:

```diff
# filename: example/ios/Podfile

-  :hermes_enabled => true
+  :hermes_enabled => false

...

- use_flipper!({ 'Flipper' => '0.74.0' })
```

However I'm not sure if it's the correct solution.

**Comment by mrousavy** [comment]
yeah I believe that's a flipper issue, maybe this will work on RN 65?
