### ISSUE TITLE
TypeError: _$$_REQUIRE(...).MMKV.set is not a function

### ISSUE THREAD

**Issue by TrisKnightGamer** [mrousavy/react-native-mmkv#104]
I got error TypeError: _$$_REQUIRE(...).MMKV.set is not a function when run with `react-native^0.63.4` and Chrome Base Debugger with Android 10. What I need to do ?
Thank you.

**Comment by mrousavy** [comment]
Nothing, as stated in [the README](https://github.com/mrousavy/react-native-mmkv), JSI does not support Chrome debugging.
