### ISSUE TITLE
[Jest] : TypeError: _reactNativeMmkv.MMKV.set is not a function

### ISSUE THREAD

**Issue by nazmeln** [mrousavy/react-native-mmkv#109]
Seems like the race condition [again](https://github.com/mrousavy/react-native-mmkv/issues/1) when using Jest for testing.
In the app, everything works well, but when I'm trying to test, Jest sees all methods as ```undefined```.

Here are the screenshots:

Jest:
<img width="696" alt="Screenshot at Jul 28 17-16-50" src="https://user-images.githubusercontent.com/63898981/127338335-22d12912-a682-40ed-b4d8-8b237a17bbad.png">

Flipper:
<img width="860" alt="Screenshot at Jul 28 17-17-09" src="https://user-images.githubusercontent.com/63898981/127338348-becab090-8a36-4924-aca4-8a0ca7986613.png">

**Comment by mrousavy** [comment]
That has nothing to do with a race condition, Jest does not run on a real device so the native code does not exist. You have to mock MMKV. See: https://jestjs.io/docs/manual-mocks

**Comment by nazmeln** [comment]
Maybe, it will be useful for someone, who faces the same issue as me.
I create file ```react-native-mmkv.ts``` under the folder ```__mocks__```

Here is the file: 

```
// /**
//  * @format
//  */

const mmkvMock = {
  __INTERNAL_MOCK_STORAGE__: {},

  set: jest.fn(async (key, value) => {
    mmkvMock.__INTERNAL_MOCK_STORAGE__[key] = value;

    return null;
  }),

  getString: jest.fn(async (key) => {
    const result = mmkvMock.__INTERNAL_MOCK_STORAGE__[key]
      ? mmkvMock.__INTERNAL_MOCK_STORAGE__[key]
      : null;

    return result;
  }),

  delete: jest.fn((key: string) => _removeItem(key)),

  clearAll: jest.fn(_clearAll),
  getAllKeys: jest.fn(_getAllKeys),
};

async function _removeItem(key: string) {
  if (mmkvMock.__INTERNAL_MOCK_STORAGE__[key]) {
    delete mmkvMock.__INTERNAL_MOCK_STORAGE__[key];
  }
}

async function _clearAll() {
  mmkvMock.__INTERNAL_MOCK_STORAGE__ = {};

  return null;
}

async function _getAllKeys() {
  return Object.keys(mmkvMock.__INTERNAL_MOCK_STORAGE__);
}

jest.fn(() => mmkvMock);

module.exports = {
  MMKV: mmkvMock,
};

```

**Comment by Corliosity** [comment]
Hello,

@nazmeln  - I am working on integrating MMKV into a solution currently and am trying your solution for the Tests.  However, I am getting an error (using your mock file) when running the unit tests :
` TypeError: _reactNativeMmkv.MMKV is not a constructor`

I have copied your code in to a __mock__ folder with the name react-native-mmkv.  But when using it in a test with jest.mock() I get the above error.

Any thoughts or advice?

// Thanks Andrew

**Comment by nazmeln** [comment]
Hey, @Corliosity 
Have you tried to use without ```jest mock()```?
Could you try to import and use MMKV like in the example below?
If I'm not mistaken when you created a file under the mocks folder there's no reason for using ```jest.mock()```

```
import {MMKV} from 'react-native-mmkv';

describe('Storage', () => {
  const key = 'key';
  const value = 100;
  const stringifiedValue = JSON.stringify(value);

  it('call getItem method of MMKV with key', async () => {
    await Storage.getItem(key);

    expect(MMKV.getString).toBeCalledWith(key);
  });
  ```

**Comment by Corliosity** [comment]
@nazmeln 

I tried with both removing the mock and adding the import in the Test file and it fails on both still claiming that MMKV is not a constructor.

**Comment by norellanac** [comment]
Add a wrapper provider to your App/Component

```
import { Provider } from 'react-redux';
import store from '../stores/store';

export const renderWithProviderTheme = (component: React.ReactElement) => {
  const { debug, ...rest } = render(
      <Provider store={store}>{component}</Provider>,
  );

  return {
    debug,
    ...rest,
  };
};
```

**********************
```
import { renderWithProviderTheme } from '...';

describe('Render with provider, store(mmk)', () => {
  test('Should render correctly component', () => {
    renderWithProviderTheme(
      <MyComponent/>,
    );
  });
```
