### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by nandorojo** [mrousavy/react-native-mmkv#11]
Could be cool to add web support, maybe with store or just localStorage directly.

**Comment by mrousavy** [comment]
Hi! Unfortunately I am not really familiar with react-native-web, and have no use-case for it.

It looks like this is relatively easy to implement though, probably only requires a bit of fiddling around with configuration files and then just creating a `index.web.ts`.

I would however gladly accept any PR regarding web support 👍

**Comment by mrousavy** [comment]
Working on this here: https://github.com/mrousavy/react-native-mmkv/pull/130

**Comment by mrousavy** [comment]
Would love some help with testing 🙏

**Comment by nandorojo** [comment]
@mrousavy I think this will break in an app with SSR, since `window` is undefined.

I would make `storage` a getter function instead, which is only called when one of the functions is called.

**Comment by mrousavy** [comment]
does that not work?
https://github.com/mrousavy/react-native-mmkv/blob/5b4d0ad07c561a8b69b241f1d8d712dcfa0cee14/src/createMMKV.web.ts#L7

**Comment by nandorojo** [comment]
No, because `window` is accessed when it's inexistent.

A null check is insufficient.

A typical solution on SSR apps is to do this:

`if (typeof window !== 'undefined')`

Since that won't throw an error.

In your case, if you changed that line to 

```ts
const storage = () => global.localStorage ?? window.localStorage ?? localStorage;
```

Then it would work fine. Since it's now a function, we only access `window` when one of the MMKV functions is called, and no one would call it on the server.

To be safe, you could run the window check I used above.

However, a more standardized RNW check to see if we can access the dom is `canUseDOM`. See the usage here of that variable here:

https://gist.github.com/nandorojo/066ff2f40419b7e06054cc7282e24f8d#file-hoverable-ts-L11

**Comment by nandorojo** [comment]
The issue is, you're throwing an error if storage doesn't exist, but it will never exist on the server

**Comment by nandorojo** [comment]
I added the suggested edits here: https://github.com/mrousavy/react-native-mmkv/pull/130#issuecomment-913179225

**Comment by mrousavy** [comment]
done!

**Comment by vishwanathkokare** [comment]
localStorage → It's synchronous, slow, and limited, which can block the UI

**Comment by mrousavy** [comment]
> It's synchronous

Good, this is what MMKV is about.

> slow

Do you have any benchmarks? What is a faster synchronous storage library?

> limited

How? It supports every feature of MMKV, except for encryption.
