### ISSUE TITLE
Unable to build on Mac Catalyst

### ISSUE THREAD

**Issue by ryanlntn** [mrousavy/react-native-mmkv#113]
I'm unable to build on Mac Catalyst with the same errors noted here: https://github.com/mrousavy/react-native-mmkv/issues/10

I created a minimal reproduction here: https://github.com/ryanlntn/MacOSCatalystMMKV

I've tried messing with deployment targets as per the solution there without effect. I've also toyed with different compiler settings but haven't found anything that does more than change the error message a little. I'm not sure what the requirements are for JSI but I am using react-native-reanimated 2 on catalyst without this issue. Oddly enough they set a lower deployment target too.

**Comment by mrousavy** [comment]
hey! which react native version? which deployment target?

**Comment by ryanlntn** [comment]
Using react-native 0.64.2. I tried bumping iOS deployment targets from 11 on up to the latest and did the same for macOS deployment targets.

**Comment by mrousavy** [comment]
Hey! Do you have a solution for this? Shoot me a PR and I'll review
