### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by andreialecu** [mrousavy/react-native-mmkv#133]
It would be great if the API would be more idiomatic with modern React and exposed some hooks.

In some of my projects I created a wrapper that looks like this:

```ts
  const { value, update, clear } = useAppSetting('someSetting');
```

`value` is the value, and it auto-updates in all consumers regardless of where it's being set from.
`update` and `clear` to update or clear the value

If you'd be up to this sort of implementation, I could come up with a PR for it.

**Comment by yfunk** [comment]
`react-native-mmkv-storage` has [a hook for this](https://rnmmkv.vercel.app/#/usemmkvstorage) that is similar to `useState`, which fits the React paradigm really well imo.

Maybe a similar API could be implemented for this library, something like
```ts
const [ user, setUser ] = useMMKV('userKey', instance)
console.log(user) // null (no persisted value) 

setUser('Max') 
console.log(user) // 'Max'

setUser(null)
console.log(user) // null (key deleted)

/* or */

const user = useMMKV('user', instance)
console.log(user.value) // persisted value 'Max'

user.value = 'Max'
console.log(user.value) // 'Max'

user.value = null
console.log(user.value) // null (key deleted)
```

**Comment by andreialecu** [comment]
Implementing an API similar to `useState` would be good too. My `useAppSetting` hook example above was actually using `AsyncStorage`, and I needed to expose an `isLoading` value as well.

But since MMKV is sync, and `isLoading` isn't necessary, then mimicking how `useState` works would be good as well.

**Comment by mrousavy** [comment]
Sounds like a great idea! I'm thinking about how this can be implemented most efficiently, I'll happily accept PRs for that 🤗

**Comment by andreialecu** [comment]
In my wrapper I was using [React Query](https://react-query.tanstack.com/) to be able to listen when the store was being changed, because it was already a dependency of the app.

But for a correct implementation, it seems that the native code might need to trigger some sort of JS event for when the data store changed. 🤔

**Comment by mrousavy** [comment]
no not the native code, we can do this very easily in [the `MMKV` class](https://github.com/mrousavy/react-native-mmkv/blob/9f1c30cc560a0bb38e1328ad5cc76117fe19e8ca/src/MMKV.ts#L82-L121)

**Comment by andreialecu** [comment]
Super edge case thing to think about: it might be possible that someone has some native code in a hybrid native/react-native app and saves something to MMKV straight from the Java/ObjC/Swift MMKV API.

Or if there's a share extension implemented (ref: https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/131)

I don't know if MMKV exposes any events about data changes, but if it did, it would handle the scenarios above.

**Comment by andreialecu** [comment]
Regarding my comment above, this seems to only be implemented for Android in MMKV:

> Add notification of content changed by other process, check the new MMKVContentChangeNotification<> interface & checkContentChangedByOuterProcess() for details.

Ref: https://github.com/Tencent/MMKV/blob/master/CHANGELOG.md#v1023--2019-09-03

**Comment by mrousavy** [comment]
https://github.com/mrousavy/react-native-mmkv/pull/163
