### ISSUE TITLE
Missing source.properties file

### ISSUE THREAD

**Issue by alexco2** [mrousavy/react-native-mmkv#140]
Hi,
I tried installing you library as desribed here (https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md). I also have reanimated2 installed. 
First a question: In the documentation for reanimated2 the installation guide states that the `ReanimatedJSIModulePackage()` has to be added in the Method `getJSIModulePackage()`. Your installation guide does not show that step in the code snippet from your installation guide (see bellow).

```
import com.facebook.react.bridge.JSIModulePackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          return new PackageList(this).getPackages();
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        // Add this method here!
        @Override
        protected JSIModulePackage getJSIModulePackage() {
          return new ExampleJSIPackage(); // Where is return new ReanimatedJSIModulePackage() ?
        }
      };

  // ...

```

If I follow your guide, i get the error :
```
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at C:\Users\alexa\AppData\Local\Android\Sdk\ndk\20.1.5948944 did not have a source.properties file
```

Have I done something wrong during the installation? Here a snippet from my MainApplication.java file

```
import com.facebook.react.bridge.JSIModulePackage; // <- add
import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add

public class MainApplication extends MultiDexApplication implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        /** 
        @Override
        protected JSIModulePackage getJSIModulePackage() {
          return new ReanimatedJSIModulePackage(); // <- For Reanimated2 Package
        }
       */

        @Override
        protected JSIModulePackage getJSIModulePackage() {
          return new ExampleJSIPackage(); // <-- For MMVK Package
        }
      };...
```

Thank you for your help! :)

**Comment by mrousavy** [comment]
> Your installation guide does not show that step in the code snippet from your installation guide (see bellow).

Exactly, because if you use reanimated v2 you have to override the reanimated v2 installation step with the MMKV installation step (the MMKV JSI Module Package _extends_ the Reanimated JSI module package)

> NDK Error

Which react-native version are you using?

**Comment by mrousavy** [comment]
Does your app's `build.gradle` file (in the `android/` folder) have a `ndkVersion` parameter? See [this line in the official react-native template](https://github.com/facebook/react-native/blob/4f0671b40953374d00ec5fe98d5442a13ffd5f41/template/android/build.gradle#L9)

Also make sure you have installed the NDK through Android Studio (see ["The Android NDK"](https://developer.android.com/ndk))

**Comment by alexco2** [comment]
Thank you for your quick answer. I suspected something like that, but was not sure.
I have the rn version `0.64.2`
my ndkVersion parameter is `ndkVersion = "20.1.5948944"`
Installing NDK and CMake fixed it! For anybody with the same issue, here the guide how to install them:
https://developer.android.com/studio/projects/install-ndk#default-version
