### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by wq13718048209** [mrousavy/react-native-mmkv#141]
Ios often crashes during use,

- (void)close {
    SCOPED_LOCK(g_lock);
    MMKVInfo("closing %@", m_mmapID);

    [g_instanceDic removeObjectForKey:m_mmapKey];
}

The error is here
prompt: com.facebook.react.JavaScript (35): EXC_BAD_ACCESS (code=1, address=0x5c881fc33c18)
@mrousavy  help me

**Comment by fahad86** [comment]
```
EXC_BAD_ACCESS: close > closing %@ > hash > XTUM >
Attempted to dereference garbage pointer 0x100f302c0.
  ?, in -[MMKV close]
  ?, in MmkvHostObject::~MmkvHostObject
  ?, in MmkvHostObject::~MmkvHostObject
  ?, in std::__1::__shared_ptr_emplace<T>::__on_zero_shared
  ?, in std::__1::__shared_count::__release_shared
...
(83 additional frame(s) were not displayed)
```

I'm having the above crash while trying to reload during development in iOS simulator

**Comment by mrousavy** [comment]
No reproduceable code
