### ISSUE TITLE
android

### ISSUE THREAD

**Issue by wq13718048209** [mrousavy/react-native-mmkv#145]
React-native 0.65.1 React-native MMKV :1.3.1
Failed to build on Android
C/C++: /Users/wangqiang/ttvc/TTvc/node_modules/react-native-mmkv/android/CMakeLists.txt debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
REACT_NATIVE_JNI_LIB
    linked by target "reactnativemmkv" in directory /Users/wangqiang/ttvc/TTvc/node_modules/react-native-mmkv/android

**Comment by kanzitelli** [comment]
hey @wq13718048209. I have faced the same issue while updating rn-mmkv to `1.3.1` after the automatic installation of JNI in Android Studio. Reinstalling `node_modules` and cleaning the Android project have solved the issue for me.

**Comment by wq13718048209** [comment]
@kanzitelli   thank you so much   I'll give it a try

**Comment by Jalson1982** [comment]
@wq13718048209 is this working? I see same issue on my appcenter builds and did not find solution yet. @mrousavy maybe we can move our twitter discussion here :)

**Comment by wq13718048209** [comment]
@Jalson1982   I'm sorry it didn't work

**Comment by smallzZz8** [comment]
I am also getting this error. Is there a fix yet?

**Comment by mrousavy** [comment]
A clean and rebuild usually fixes this issue for me 🤔 

```
cd android
./gradlew clean
./gradlew buildDebug
```

**Comment by yuri-lomashko-itechart** [comment]
I have the same error only on AppCenter CI

**Comment by Luanluu96** [comment]
find and replace the code below in the file **android/CMakeLists.txt** will work 
same: https://github.com/mrousavy/react-native-vision-camera/issues/513#issuecomment-940857627
```
find_library(
        JSI_LIB
        ${JSI_LIB}
        jsi
        PATHS ${LIBRN_DIR}
        NO_CMAKE_FIND_ROOT_PATH
)
```

**Comment by hiscc** [comment]
> find_library(
>         ${JSI_LIB}
>         jsi
>         PATHS ${LIBRN_DIR}
>         NO_CMAKE_FIND_ROOT_PATH
> )

save my day!!!! thx🙏🙏

**Comment by mrousavy** [comment]
That'd be introducing other bugs since the C++ symbols are duplicated. I'm looking into finding a real fix soon

**Comment by julian-kingman-lark** [comment]
Sorry, what's the solution here? I'm encountering this in react native 0.69.6, fresh node_modules install.

**Comment by rb185264** [comment]
> Sorry, what's the solution here? I'm encountering this in react native 0.69.6, fresh node_modules install. Adding `${JSI_LIB}` and `jsi` to the mmkv CMakeList.txt does temporarily solve this

Hi Julian, how did you add these? I am also facing the same problem.
