### ISSUE TITLE
TypeError: constructor is not callable

### ISSUE THREAD

**Issue by d3vhound** [mrousavy/react-native-mmkv#146]
```bash
TypeError: constructor is not callable, js engine: hermes
```
After following the installation guide for android I get this error when trying to run my project on an android sim.

**Comment by sergiuchuckmisha** [comment]
I personally have experienced this annoying issue

`constructor is not callable`
when trying to establish websocket connection from the default react-native application.
And in my particular case point was in importing/exporting and, possibly, in a mixture of .js and .tsx JS files.

When I put all the code in one file (App.tsx) the error has gone.

[stackoverflow link](https://stackoverflow.com/a/76324186/6045233)
