### ISSUE TITLE
Upgrading to 1.3.3 in React Native Monorepo breaks build

### ISSUE THREAD

**Issue by Corliosity** [mrousavy/react-native-mmkv#178]
Upgrading from 1.3.2 (fix for Android Monorepo Build) to v 1.3.3 breaks the fixes done to make the build agnostic for Monorepos vs. single projects it appears to be due to inclusion of : 
`        arguments '-DANDROID_STL=c++_shared',
          "-DNODE_MODULES_DIR=${rootDir}/../node_modules"`

Which makes a presumption of where the code will be handled.  Is it possible to revert this line to the previous fix?

**Comment by andrewcorliss** [comment]
Created a PR for this today. Thank you.

**Comment by Corliosity** [comment]
Merged and closing issue
