### ISSUE TITLE
Change `encryptionKey` on existing instances

### ISSUE THREAD

**Issue by franjs** [mrousavy/react-native-mmkv#179]
From the docs on [IOS](https://github.com/Tencent/MMKV/wiki/iOS_advance#encryption) and [Android](https://github.com/Tencent/MMKV/wiki/android_advance#encryption) I can see that it is possible to change the encryption key for MMVK. 

It looks that this feature has not been implemented yet. Are there any plans to include this feature?

**Comment by mattijsf** [comment]
Yes this would be a very useful addition. We would like to use that in the exact way.

**Comment by mrousavy** [comment]
Alright I got 40 minutes of free time, what do you want the function to be called? I'm thinking `storage.recrypt(...)` - not sure if that's a word tho

**Comment by mattijsf** [comment]
Cool. Well... here they call it `reKey` not sure if that has a good ring to it either: https://github.com/Tencent/MMKV/blob/3b79dad46d09881aed7a6b54291069130e53e249/flutter/README.md#encryptio

Quoting there docs:
```
// an unencrypted MMKV instance
var mmkv = MMKV("test-encryption");

// change from unencrypted to encrypted
mmkv.reKey("Key_seq_1");

// change encryption key
mmkv.reKey("Key_seq_2");

// change from encrypted to unencrypted
kmmkv.reKey(null);
```

**Comment by mrousavy** [comment]
Can you guys check if #314 works for you?
