### ISSUE TITLE
Support for objects?

### ISSUE THREAD

**Issue by scarlac** [mrousavy/react-native-mmkv#2]
Feature request:
I see references to things like `convertObjCObjectToJSIValue` and the reverse but mmkv.mm doesn't seem to be exposing this functionality.

Would it be possible to get native object/dict support so one could avoid using `JSON.stringify()` (and rely on the native counter-part)? Or have you found that it's more trouble than it's worth?

**Comment by mrousavy** [comment]
Hmm, on iOS there is support for storing `id` (basically `any`), I'll have to see how that will work.

What do you think the return type should be?

I'm thinking `unknown`:

```
getObject: (key: string) => unknown
```

**Comment by mrousavy** [comment]
I'll see what's possible in https://github.com/mrousavy/react-native-mmkv/pull/7

**Comment by samuel3105** [comment]
A way to do it is already explain on documentation :

```js
const user = {
  username: 'Marc',
  age: 21
}

storage.set('user', JSON.stringify(user))

const jsonUser = storage.getString('user') // { 'username': 'Marc', 'age': 21 }
const userObject = JSON.parse(jsonUser)
```

May this Issues should be closed ?

**Comment by mrousavy** [comment]
Yeah I think closing this issue makes sense. `JSON` is fast and easy, otherwise I would have to create a custom implementation and binary serializer (protobuf/flatbuf/flexbuf?) and that's maintainable native code.
