### ISSUE TITLE
Android build failing in monorepo

### ISSUE THREAD

**Issue by axeldelafosse** [mrousavy/react-native-mmkv#218]
Using `v1.5.3` in a monorepo, I get this error when building the Android app:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-mmkv.
     Required by:
         project :app
      > No matching configuration of project :react-native-mmkv was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
```

**Comment by axeldelafosse** [comment]
cc @Titozzz (https://github.com/mrousavy/react-native-mmkv/pull/151) and @andrewcorliss (https://github.com/mrousavy/react-native-mmkv/pull/189) -- any idea why this is happening?

**Comment by andrewcorliss** [comment]
Hello,

nothing comes to mind.  Can you share any more information?  How do you have the android package setup?

Thank you,

**Comment by axeldelafosse** [comment]
Hey Andrew!

I found the reason why, cf. `settings.gradle`:

```
include ':react-native-mmkv'
project(':react-native-mmkv').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mmkv/android/')
```

It needs to be:
```
include ':react-native-mmkv'
project(':react-native-mmkv').projectDir = new File(rootProject.projectDir, '../../../node_modules/react-native-mmkv/android/')
```

Closing this, thanks!

**Comment by andrewcorliss** [comment]
No worry glad you were able to get it solved!

Thank you for double checking.

**Comment by Titozzz** [comment]
Why wouldn't you use auto linking ? @axeldelafosse

**Comment by axeldelafosse** [comment]
I assumed that it wasn't working (based on my previous setup)! Just tested and it's working correctly! Thanks man
