### ISSUE TITLE
calling the `set` method where the key includes a colon ":" causes segfault

### ISSUE THREAD

**Issue by sebbekarlsson** [mrousavy/react-native-mmkv#220]
What characters are the keys allowed to include?

**Comment by mrousavy** [comment]
That's weird, I thought the key can be any string? Maybe post this question over at [Tencent/MMKV](https://github.com/Tencent/MMKV/issues)

**Comment by mrousavy** [comment]
I always use `.` and `-`, so for example: `user.profile-picture`, `user.name` or `cache.wallet-balance`

**Comment by mrousavy** [comment]
Actually now that I think about it - I am using `:` as a key and it works. 

This code here works fine:

```ts
const storage = new MMKV({
  id: 'bla'
})

const key = 'cache.thumbnail-url-https://medium.com/@PinkPandaFinance/759554723a30'
storage.set(key, 'Hello!')
const word = storage.getString(key) // <-- Hello!
```

**Comment by sebbekarlsson** [comment]
> Actually now that I think about it - I am using `:` as a key in one of my apps and it works fine:
> 
> ```ts
> const storage = new MMKV({
>   id: 'bla'
> })
> 
> const key = 'cache.thumbnail-url-https://medium.com/@PinkPandaFinance/759554723a30'
> storage.set(key, 'Hello!')
> const word = storage.getString(key) // <-- Hello!
> ```

Hmmm strange.
Maybe I just didn't test this properly.

I'm closing this until I can reproduce it again.

Thanks
