### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by zxwGH** [mrousavy/react-native-mmkv#226]
I have used react native realized and have followed（ https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md ）Disposition ，  This error occurs after compilation
![image](https://user-images.githubusercontent.com/39894660/141045064-0c91b796-23f5-4ce1-8eba-fd4db4f554f5.png)

Use environment

react-native- reanimated@2.2.3 、react-native- mmkv@1.5.3 、react- native@0.66.2

How can I eliminate mistakes?
thank you

**Comment by zxwGH** [comment]
Error: Failed to create a new MMKV instance, the native initializer function does not exist. Is the native MMKV library correctly installed? Make sure to disable any remote debugger (e.g. Chrome) to use JSI!, js engine: hermes

**Comment by andrey-shostik** [comment]
@zxwGH Did you managed to solve it?

**Comment by zxwGH** [comment]
> @zxwGH Did you managed to solve it?

Yes, according to the document
