### ISSUE TITLE
Testing the performance after the upgrade

### ISSUE THREAD

**Issue by MaxToyberman** [mrousavy/react-native-mmkv#229]
Hi,
Thanks for the great library, I would like to compare the performance before the upgrade and after.

How did you test it?

**Comment by mrousavy** [comment]
[Here](https://github.com/mrousavy/react-native-mmkv/blob/master/example/src/Benchmarks.ts) are the benchmarks I used to test **read speed**.

In a real world example, I guess the general app speed can be perceived faster by the user, depending on how much storage reads/writes you have.
