### ISSUE TITLE
Typed keys

### ISSUE THREAD

**Issue by sseppola** [mrousavy/react-native-mmkv#236]
Cheers for the good work you're doing for the community Marc!

I wrote a thin wrapper around this lib in order to have TypeScript enforce a set of keys, and as it would be a breaking change for the library I figured I'd post it here in case you or anyone else want to use the solution.

Do as you wish, let me know if you'd rather have it as a PR.

```ts
import {MMKV} from 'react-native-mmkv';

export interface TypedMMKVInterface<StringKeysT, NumberKeysT, BoolKeysT> {
  /**
   * Set a value for the given `key`.
   */
  set: (key: StringKeysT | NumberKeysT | BoolKeysT, value: boolean | string | number) => void;

  /**
   * Get a boolean value for the given `key`.
   *
   * @default false
   */
  getBoolean: (key: BoolKeysT) => boolean;
  /**
   * Get a string value for the given `key`.
   *
   * @default undefined
   */
  getString: (key: StringKeysT) => string | undefined;
  /**
   * Get a number value for the given `key`.
   *
   * @default 0
   */
  getNumber: (key: NumberKeysT) => number;
  /**
   * Delete the given `key`.
   */
  delete: (key: StringKeysT | NumberKeysT | BoolKeysT) => void;
  /**
   * Get all keys.
   *
   * @default []
   */
  getAllKeys: () => Array<StringKeysT | NumberKeysT | BoolKeysT>;
  /**
   * Delete all keys.
   */
  clearAll: () => void;
}

export function createKeyStore<
  StringKeysT extends string = never,
  NumberKeysT extends string = never,
  BoolKeysT extends string = never,
>(id: string): TypedMMKVInterface<StringKeysT, NumberKeysT, BoolKeysT> {
  const _keyStore = new MMKV({id});

  return {
    set: (key, value) => _keyStore.set(key, value),

    getBoolean: key => _keyStore.getBoolean(key),

    getString: key => _keyStore.getString(key),

    getNumber: key => _keyStore.getNumber(key),

    delete: key => _keyStore.delete(key),

    getAllKeys: () => _keyStore.getAllKeys() as Array<StringKeysT | NumberKeysT | BoolKeysT>,

    clearAll: () => _keyStore.clearAll(),
  };
}

```

**Comment by mrousavy** [comment]
Cool! I've played around with something similar in one of my apps before.

**Comment by mrousavy** [comment]
@sseppola revisiting this - how do you think should we proceed? I don't think this should be part of MMKV but rather a user's abstraction, do you disagree?

**Comment by sseppola** [comment]
Looking at how I use it:
```
const store = createKeyStore<'user', never, never>({
  id: `mmkv_user_store`,
});
```
where createKeyStore is the fn shared above. My wrapper basically wraps the whole interface of MMKV 1:1 in order to provide the types, which seems unnecessary.

Would you consider a PR that doesn't introduce any breaking changes, but makes this typing opt-in?
I need to tinker with your source code, but I think by changing the defaults from `never` to `string` could achieve this.

**Comment by mrousavy** [comment]
After a lot of consideration I'd say we leave this out of the library's core code. If you want, you can provide this abstraction as a separate library, but I'd like to avoid the code duplication here and keep MMKV as lean and lightweight as possible :)
