### ISSUE TITLE
How can you set a default variable for hooks.. specifically a default object for useMMKVObject?

### ISSUE THREAD

**Issue by nescroft** [mrousavy/react-native-mmkv#238]
I want to do something like this but it doesn't seem to work.
type Store = {
  dreams: Object[],
  recordIndex: Number,
};

function App(){
const [store, setStore] = useMMKVObject<Store>('store', {dreams:[], recordIndex:0});
}

**Comment by nescroft** [comment]
i guess i can do something like this:

useEffect(() => {
    if (!store) {
      setStore({dreams: [], recordIndex: 0});
    }
  }, []);

**Comment by ferrannp** [comment]
You could just do like this to give a default value:

```js
const [store =  {dreams:[], recordIndex:0}), setStore] = useMMKVObject('store');
```

**Comment by nescroft** [comment]
woah no idea that could be done. thanks ill try it out!
