### ISSUE TITLE
This may seem like a dumb question

### ISSUE THREAD

**Issue by 10000multiplier** [mrousavy/react-native-mmkv#241]
In the example:

```jsx

function App() {
  const globalStorage = useMMKV()
  const userStorage = useMMKV({ id: `${userId}.storage` })

  const [username, setUsername] = useMMKVString("user.name", userStorage)
}
```

How can I set up my app so that I don't have to perform a database fetch to get the `userId` anytime I'd want to use MMKV, while still having a unique local storage for each user?

Sorry if this is a dumb question.

**Comment by mrousavy** [comment]
Hey, just share the `userStorage` object (e.g. via React.Context)

**Comment by 10000multiplier** [comment]
> Hey, just share the `userStorage` object (e.g. via React.Context)

thanks!
