### ISSUE TITLE
How would you add a key to an existing object, without overriding the whole object?

### ISSUE THREAD

**Issue by 10000multiplier** [mrousavy/react-native-mmkv#242]
For example, this doesn't seem to work:

```jsx
type User = {
  id: string
  username: string
  age: number
}

function App() {
  const [user, setUser] = useMMKVObject<User>("user")
  
  setUser((prev) => ({ 
  	...prev, 
  	gender: 'male' 
  }))
}
```

Any insight is greatly appreciated, thanks!

**Comment by 10000multiplier** [comment]
So turns out the solution was really simple:

```jsx
  setUser({ 
  	...user, 
  	gender: 'male' 
  })
}
```

**Comment by 10000multiplier** [comment]
Actually, `user` can be `undefined` so it should be:

```jsx
  user ? 
  setUser({ 
  	...user, 
  	gender: 'male' 
  }) 
  :
  setUser({ 
  	gender: 'male' 
  }) 
```

Although a better strategy is probably giving the `user` object a default initial value.

**Comment by mrousavy** [comment]
I could also provide the function syntax

**Comment by 10000multiplier** [comment]
> I could also provide the function syntax

Sir if you are asking if you should make your amazing library even more amazing the answer is yes😁.
