### ISSUE TITLE
Do we support chrome debugger?

### ISSUE THREAD

**Issue by minhchienwikipedia** [mrousavy/react-native-mmkv#245]
```
Failed to create a new MMKV instance, the native initializer function does not exist. Is the native MMKV library correctly installed? Make sure to disable any remote debugger (e.g. Chrome) to use JSI! 
```
Seems your package use JSI like RN reanimated 2, and they already fixed that issue by [this](https://github.com/software-mansion/react-native-reanimated/pull/2197 )
Can you fix it to support a chrome debugger? Or any plan for it?

**Comment by mrousavy** [comment]
Hey!

No, that's not supported. See the ["Limitations"](https://github.com/mrousavy/react-native-mmkv#limitations) section in the README:

> As the library uses JSI for synchronous native methods access, remote debugging (e.g. with Chrome) is no longer possible. Instead, you should use Flipper.

**Comment by mrousavy** [comment]
The way Reanimated works, is by using a pure JS implementation. This does not work for MMKV, there is no pure JS implementation of a synchronous key/value storage. That's part of the reason why MMKV is so nice 😄 

You can mock it using a simple in memory `Map<K, V>`, but that obviously doesn't persist to storage.

**Comment by pvinis** [comment]
i see this, https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/221, which could be something to support too. basically what you're saying, but would be nice to have it in the lib.

**Comment by mrousavy** [comment]
This should already work with a minor change to the import script (we need to skip the native install() call), but then it will use the Web implementation (localStorage).

Either way, the Chrome Debugger is not recommended anyways, and will fail in the future because more and more modules will use JSI. On RN with Fabric enabled it won't work at all.

So I recommend:
* either debug with Safari debugger (that runs on device!)
* or use the Flipper debugger (recommended by facebook)

**Comment by pvinis** [comment]
oh snap. safari debugger? i didnt know that.. ill try. flipper is cool, but there is no breakpoint debugging with it.

**Comment by mrousavy** [comment]
VSCode also has a RN Debugger, that has breakpoints.

**Comment by zbyzhlsp** [comment]
> VSCode also has a RN Debugger, that has breakpoints.

Hi @mrousavy, I've tried the react native tools in VSCode, but it also didn't work if i integrated react-native-mmkv in my project.
when I toggle on the debug mode in the dev menu, the console output this error log:
`error: Failed to create a new MMKV instance: React Native is not running on-device. MMKV can only be used when synchronous method invocations (JSI) are possible. If you are using a remote debugger (e.g. Chrome), switch to an on-device debugger (e.g. Flipper) instead.`
So the flipper is the only way to debug my app, is that right?

**Comment by kulak91** [comment]
Hello! What about the case if i need to set breakpoints and flipper is already deprecated?

**Comment by mrousavy** [comment]
Therr are alternatives to flipper. RN IDE for example

**Comment by kulak91** [comment]
I started using VSCode [React Native Tools](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native)  extension. Quite simple as for me

**Comment by csimpi** [comment]
@mrousavy Flipper is incompatible with Firebase which is essential for mobile apps. 
RN's official debugging is using the Devtools.  Is it technically impossible to solve this problem?
