### ISSUE TITLE
[ANDROID] Error with react-native 0.66.3 

### ISSUE THREAD

**Issue by KrifaYounes** [mrousavy/react-native-mmkv#248]
A problem occurred configuring project ':react-native-mmkv'.
> java.lang.RuntimeException: Unsupported ABI for NDK r19+: ARMEABI

    "react-native-mmkv": "^1.5.3",
    "react-native": "0.66.3",

 with   ndkVersion = "21.4.7075529" the error occurred

**Comment by pgiki** [comment]
I used ndkVersion = 22.0.7026061 and was able to build the app successfully. I am not sure if this issue is ndkVersion related but you can give it a try.

**Comment by mrousavy** [comment]
This seems unrelated. Let me know if you still have the error after cleaning everything, and if the error can be reproduced in the Example app - then I'll re-open the issue.

**Comment by misino** [comment]
It was fixed for me after setting up `ndk.dir` property in local.properties
