### ISSUE TITLE
[android] variables are set to NOTFOUND

### ISSUE THREAD

**Issue by vonoro** [mrousavy/react-native-mmkv#253]
hello, thanks for the lib

related to https://github.com/mrousavy/react-native-mmkv/commit/584665c35b89022730bc5555aac484c10031bb66
´
v1.5.3 builds fine in my project but after upgrading to 1.5.4 I'm seeing this when building release version

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv:generateJsonModelRelease'.
> /Users/runner/work/1/s/node_modules/react-native-mmkv/android/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "reactnativemmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv/android
  REACT_NATIVE_JNI_LIB
      linked by target "reactnativemmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv/android

```

using RN 0.64.rc4

**Comment by zpd106** [comment]
If you use (./gradlew clean app:assembleRelease ), please use it separately (./gradlew clean && ./gradlew app:assembleRelease). I ran into this problem and solved it like this

**Comment by hiscc** [comment]
i solve this by https://github.com/mrousavy/react-native-mmkv/issues/145#issuecomment-960569065

**Comment by mrousavy** [comment]
clean and rebuild fixes this.
