### ISSUE TITLE
I got this error after installing @react-native-firebase/messaging

### ISSUE THREAD

**Issue by thanhnvpk01168** [mrousavy/react-native-mmkv#264]
everything works perfectly, but after installing @react-native-firebase/messaging it gives me this error

------------\/--------------
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-mmkv:generateJsonModelDebug'.
> /Users/vanthanh/Documents/base/testNotify/node_modules/react-native-mmkv/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "reactnativemmkv" in directory /Users/vanthanh/Documents/base/testNotify/node_modules/react-native-mmkv/android
  REACT_NATIVE_JNI_LIB
      linked by target "reactnativemmkv" in directory /Users/vanthanh/Documents/base/testNotify/node_modules/react-native-mmkv/android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-firebase_messaging:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 54s

**Comment by mrousavy** [comment]
This seems unrelated. Let me know if you still have the error after cleaning everything, and if the error can be reproduced in the Example app - then I'll re-open the issue.
