### ISSUE TITLE
There are a lot of problems on Android

### ISSUE THREAD

**Issue by wq13718048209** [mrousavy/react-native-mmkv#265]
There will be a lot of problems in Android, issues about Android will still encounter, the author, have you ever thought about making android installation more simple, I have not succeeded in Android.
"The react - native" : "0.66.4",
"The react - native - MMKV" : "^ 1.5.4"
There are so many problems on Android, and every time clean and Build will always download a lot of things, if the network is not good, it will never download successfully

**Comment by wq13718048209** [comment]
Questions like, why do we keep getting them:
Execution failed for task ':react-native-mmkv:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/wangqiang/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/wangqiang/Desktop/ReactNativeHodgepodge/node_modules/react-native-mmkv/android/.cxx/cmake/debug/armeabi-v7a reactnativemmkv}
  ninja: Entering directory `/Users/wangqiang/Desktop/ReactNativeHodgepodge/node_modules/react-native-mmkv/android/.cxx/cmake/debug/armeabi-v7a'

**Comment by wq13718048209** [comment]
I don't know why I have to download a lot of stuff after automatic link on Android, I couldn't download it at all due to network issues:
https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz
https://github.com/google/double-conversion/archive/v1.1.6.tar.gz
https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz
https://github.com/google/glog/archive/v0.3.5.tar.gz

**Comment by mrousavy** [comment]
I need those to build the library, that's how native JSI modules work today. This will likely be resolved once Facebook releases better build tools/libs for the new architecture, but there's not a lot I can do until then unless building a precompiled `.aar` for **every** React Native version.

**Comment by cesargdm** [comment]
Vision camera has a fix already https://github.com/mrousavy/react-native-vision-camera/commit/77e065d961470c695a00063ec1940163c6df4905

**Comment by Val-M9** [comment]
So I can't start app due to issue

**Comment by Val-M9** [comment]
So I can't start app due the issue 
> Task :react-native-mmkv:downloadBoost
Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

> Task :react-native-mmkv:downloadFolly FAILED
Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz

> Task :react-native-mmkv:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-mmkv:downloadGlog FAILED
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-mmkv:downloadDoubleConversion FAILED

and can't download that files directly. Though "downloadBoost" file eventually downloads (automatically), the other three - do not.

**Comment by anastely** [comment]
> So I can't start app due the issue
> 
> > Task :react-native-mmkv:downloadBoost
> > Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
> 
> > Task :react-native-mmkv:downloadFolly FAILED
> > Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz
> 
> > Task :react-native-mmkv:downloadDoubleConversion
> > Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz
> 
> > Task :react-native-mmkv:downloadGlog FAILED
> > Download https://github.com/google/glog/archive/v0.3.5.tar.gz
> 
> > Task :react-native-mmkv:downloadDoubleConversion FAILED
> 
> and can't download that files directly. Though "downloadBoost" file eventually downloads (automatically), the other three - do not.

Did you fix it 👀 ?

**Comment by Val-M9** [comment]
> 

for some reason I can't download this files from my machine, so eventually I've asked my teammate to do this, and then just simply added them to library's downloads folder. I could sent them to you, if needed

**Comment by anastely** [comment]
@Val-M9 yeah please, you can find my email in my GitHub profile.
Appreciate, thanks.
