### ISSUE TITLE
Supporting mobx-persist ?

### ISSUE THREAD

**Issue by riamon-v** [mrousavy/react-native-mmkv#269]
Hey there,

I saw react-native-mmkv supports mobx-persist-store but does it support mobx-persist ( https://github.com/pinqy520/mobx-persist) ?

Mobx-persist-store uses mobx-persist under the hood but is there a way with react-native-mmkv to go with mobx-persist only ?

**Comment by mrousavy** [comment]
Of course, it probably even has the same syntax. You just need to write the wrapper yourself, should be no more than 20 lines of code.

**Comment by riamon-v** [comment]
Well, seems I lied about my first comment.

Mobx-persit-store does not use mobx-persist under the hood, I will check if we can implement your library with mobx-persist.

Else, can this be a feature request ?

**Comment by mrousavy** [comment]
react-native-mmkv is a key/value storage library. It does not provide MobX, Redux, or other persist wrappers - those should be created either by you in your app (only a few lines of code) or as a separate repository - but I don't want those dependencies in this repo.

So I think the solution here is to add the mobx-persist wrapper to the documentation/README section here :)

**Comment by Hirbod** [comment]
https://github.com/mrousavy/react-native-mmkv/blob/master/docs/WRAPPER_MOBX.md

?
