### ISSUE TITLE
Fail to build on Android with version 1.6.0

### ISSUE THREAD

**Issue by cesargdm** [mrousavy/react-native-mmkv#270]
When trying to build for android or runinng `./gradlew clean` with version 1.6.0 i get the following error

```bash
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '<PROJECT_DIR>/node_modules/react-native-mmkv/android/build.gradle' line: 77

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv'.
> <PROJECT_DIR>/node_modules/react-native-mmkv/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
```

Running with RN version `0.64.3` with Expo bare project `44.0.2`. iOS builds correctly

**Comment by cesargdm** [comment]
Even tho this step is fixed by #271 I get the next error:

```
fatal error: 'folly/dynamic.h' file not found
  #include <folly/dynamic.h>
```

**Comment by mrousavy** [comment]
Hey!

Okay your first error is because I didn't think about monorepos with the path...

The second one seems to be caused by RN core?

**Comment by mrousavy** [comment]
Hey! Can you check if #273 solves the issue for you? Remember to do a clean and rebuild.

**Comment by cesargdm** [comment]
> Hey!
> 
> Okay your first error is because I didn't think about monorepos with the path...
> 
> The second one seems to be caused by RN core?

Will check! I'm not sure what do you mean by mono-repo since my project is a single RN app

**Comment by cesargdm** [comment]
Worked! Thanks @mrousavy

**Comment by mrousavy** [comment]
Awesome! Nice to hear it finally being resolved 😅

**Comment by anastely** [comment]
Hey @mrousavy 

I've run the clean command but I got this 😅

![Screen Shot 2022-02-17 at 1 44 41 PM](https://user-images.githubusercontent.com/24620979/154475289-fc1c6c2e-933a-4fc9-9d10-1b5ff88f4ba9.png)


And this when trying to build an android app

```

......../app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:47: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvPackage;
                          ^
..../app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:129: error: cannot find symbol
      new MmkvPackage(),
          ^
  symbol:   class MmkvPackage
  location: class PackageList
Note: ......../app/android/app/src/debug/java/com/pastrystation/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

```
--
I delete node_modules then re-install without luck

--
  "react-native-mmkv": "^2.1.0"

**Comment by mrousavy** [comment]
Run `rm -rf android/app/build` and try again with clean & build

**Comment by anastely** [comment]
@mrousavy  Sadly i got the same errors 🙁

**Comment by anastely** [comment]
here's what i got when open android studio 

<img width="1119" alt="Screen Shot 2022-02-17 at 3 10 16 PM" src="https://user-images.githubusercontent.com/24620979/154488668-7e66fe80-6010-482d-aba4-f74b5dd98f5c.png">

**Comment by krunalbad** [comment]
I am using below version and facing same error. Working fine in iOS
- "react": "16.13.1",
- "react-native": "0.63.2",
- "react-native-mmkv": "2.3.0",

**Comment by DominicTobias** [comment]
I'm getting this issue trying to run fastlane build task. Non-apk build, or APK build in Android Studio works. But trying to emulate what the CI does (which is also on mac). I guess there is something in the toolchain which is a different version on my Mac. On RN 0.68 :/

``` 
desc 'Build the Android application.'
  lane :build do |options|
    flavor = get_flavors(options[:env])
    bump_build_number(buildNumber: options[:buildNumber])
    gradle(
      task: "clean bundle",
      flavor: flavor[:android],
      build_type: "Release",
      project_dir: 'android/',
      flags: "--stacktrace --no-daemon"
    )
  end
```

```
fastlane android build
```

```
In file included from ***/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/CxxModuleWrapperBase.h:13:
***/node_modules/react-native/ReactCommon/cxxreact/CxxModule.h:15:10: fatal error: 'folly/dynamic.h' file not found
#include <folly/dynamic.h>
```

**Comment by vberezkin** [comment]
I have same issue when build from command line. Everything is ok when build from AS

`> Task :react-native-vision-camera:buildCMakeRelWithDebInfo
C/C++: ninja: Entering directory '/Users/me/myapp/node_modules/react-native-vision-camera/android/.cxx/RelWithDebInfo/1m3m2u6e/armeabi-v7a'
C/C++: In file included from ../../../../src/main/cpp/JSIJNIConversion.cpp:15:
C/C++: /Users/me/myapp/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/NativeMap.h:11:10: fatal error: 'folly/dynamic.h' file not found
`
