### ISSUE TITLE
[android][expo sdk 44][crash] - Support for 0.64.3?

### ISSUE THREAD

**Issue by Hirbod** [mrousavy/react-native-mmkv#277]
HI Marc,

would you consider also providing support for older RN Versions (those shipped with Expo SDK)?
RNVC went smoothly so far, now I tried to install this lib but it crashed at the last 1%

```gradle
fatal error: 'folly/dynamic.h' file not found
#include <folly/dynamic.h>
         ^~~~~~~~~~~~~~~~~
```

**Comment by mrousavy** [comment]
haha you and your percentages - I actually fixed that bug but turned off my pc now, update will come tomorrow

**Comment by Hirbod** [comment]
Well, when you wait like 3 minutes and see light at the end of the tunnel and it crashes at 99% - its so painful :D

**Comment by Hirbod** [comment]
No worries, have a good rest. Was about to drop some more coffees, but GIthub wont let me to do you a favour.
<img width="300" alt="Bildschirmfoto 2022-01-04 um 18 43 31" src="https://user-images.githubusercontent.com/504909/148101276-d1fff9de-c511-4775-bd0e-57779a7e2602.png">

**Comment by Hirbod** [comment]
Fixed via #276 
Thanks @mrousavy

**Comment by mrousavy** [comment]
yup just wanted to tag you, finally resolved it. let me know if everything works for you now

**Comment by Hirbod** [comment]
Works perfectly with @alexdelafosse plug-in !
