### ISSUE TITLE
Support for macOS and Windows

### ISSUE THREAD

**Issue by ShivamJoker** [mrousavy/react-native-mmkv#279]
Hey it would be great to have the support for desktop version of react native as well.

**Comment by mrousavy** [comment]
yeah, that would indeed be great

**Comment by mrousavy** [comment]
duplicate of https://github.com/mrousavy/react-native-mmkv/issues/12

**Comment by ShivamJoker** [comment]
@mrousavy Not sure about windows but macOS should be easy because the library already works on iOS.
