### ISSUE TITLE
android cmake

### ISSUE THREAD

**Issue by wq13718048209** [mrousavy/react-native-mmkv#299]
"react-naitve":"0.63.4"
"react-native-mmkv": "^2.0.0",
My native cmake version is 3.9.2, but it is Android./gradlew build will cause an error  ( CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2) ,
I don't have the 3.6.0-Rc2 version of Cmake locally, but it will always be installed automatically after bulid ends and an error will be reported,
I tried deleting it, but as soon as the build finished it would come up and give an error. I felt like I was stuck in a loop

**Comment by mrousavy** [comment]
Maybe NDK Version is missing in your app's build.gradle
