### ISSUE TITLE
TS changes 

### ISSUE THREAD

**Issue by Hajan39** [mrousavy/react-native-mmkv#303]
Hello, 
I am testing this library to see if it will be better than AsyncStorage, and I like this as synchronous and fast. I was trying to implement the useMMKVObject.
https://github.com/mrousavy/react-native-mmkv/blob/HEAD/docs/HOOKS.md 
I was using it like this 

`const [items, setItems] = useMMKVObject<MyObject[]>(storageKey);`

the 'items' value can be MyObject[] or undefined, but I can't set this to undefined. It has to be changed as follows:

`const [items, setItems] = useMMKVObject<MyObject[] | undefined>(storageKey);`

So I would suggest one of two changes (or both)

1. Possibility to set a default value when the key will not exist, in this case, would be '[]',
2. that setItems should accept undefined

If there is any reason for this, please tell me. I would be happy to hear it 😄 

And there is one question - it means if I will be using useMMKVObject, it is the same as useSatate and get/set to MMKV?

**Comment by mrousavy** [comment]
Hey!

The return value of `useMMKVObject` is `T | undefined`, so I'm not sure why it is not undefined in your case?

https://github.com/mrousavy/react-native-mmkv/blob/83aa57631e05d619e1c4886cb9ec4e97a625b8aa/src/hooks.ts#L148

Also, default values like `[]` have to be handled by you. If `items` is `undefined`, you can treat it as `[]`.

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/react-native-mmkv/commit/d32a48d4fd4bb86960a7a55ee3983ff118640057

**Comment by AndresdoSantos** [comment]
Hi @mrousavy.

I made it

`const [users, setUsers] = useMMKVObject<User[]>('users', [])`

And when I try to do that

`setUsers((state) => [...state, newUser])`

It gives me the error
**Argument of type '(state: any) => any[]' is not assignable to parameter of type 'User[]'.**

I understand that the instance is an `MMKV` and that it returns the generic type I passed in, but I can't see that happening.

Another point here... when I try to initialize the state with `[]` it returns the error **Argument of type 'undefined[]' is not assignable to parameter of type 'MMKV'.**

Why is the instance MMKV and not T?
