### ISSUE TITLE
Migrate from react-native-mmkv-storage

### ISSUE THREAD

**Issue by bjjeong** [mrousavy/react-native-mmkv#307]
Hi there, I've been using `react-native-mmkv-storage` for some time now (at the time, I didn't know much about the differences between the two so I blindly chose that library.

But now, I've decided that I want to migrate over to `react-native-mmkv` since it's easier to use and has less upfront configuration. But the problem is, I'm not quite sure how I can migrate everything from the old library to this one. I've taken a look at the guide for migrating over from AsyncStorage but wasn't sure that would translate over directly.

Any help would be much appreciated!

**Comment by mrousavy** [comment]
Hey, thanks for choosing my library! I _think_ you don't need to migrate at all, they both use the same native MMKV implementation :)

**Comment by bjjeong** [comment]
@mrousavy  I just tried and kept all the keys consistent through the migration but unfortunately the existing key/value pairs were deleted :/

I wasn't using any special initialization either. `const MMKV = new MMKVStorage.Loader().initialize()` for `react-native-mmkv-storage` and `const storage = new MMKV()` for `react-native-mmkv`

**Comment by mrousavy** [comment]
Ah! My fault, I use custom IDs for MMKV per default, I am not a big fan of using the shared instance.

You can try:
`const storage = new MMKV({ id: '' })`
and if that doesn't work you need to copy over the keys.

**Comment by mrousavy** [comment]
I could also add the feature of optionally using the shared instance, but I'm a fan of keeping the API simple.

So
`const storage = MMKV.sharedInstance`

for example. I'll think about this.

**Comment by bjjeong** [comment]
@mrousavy unfortunately, initializing with an empty `id` returns `Error: Exception in HostFunction: Failed to create MMKV instance!`.

I'll have to see if I can come up with some creative solution to migrate over - but yes, if there was a way to use the shared instance as an option that would be awesome! At the very least, it would help people like me who want to safely migrate over from `react-native-mmkv-storage`.

**Comment by mrousavy** [comment]
Migrating over is actually very easy for you, what do you mean with "creative solution"? You just iterate over the keys in the old DB and write each one to the new one..

**Comment by bjjeong** [comment]
I had tried that approach before and it wasn't working but just discovered the issue (was on `react-native-mmkv-storage` side).

now all key/value pairs are migrated over :) thanks for the help @mrousavy!

**Comment by mrousavy** [comment]
Anytime! Also check out https://github.com/mrousavy/react-native-mmkv/pull/312

**Comment by dynamichny** [comment]
Hey @bjjeong, could you tell how did you migrate data from react-native-mmkv-storage to react-native-mmkv? I have a conflict with CocaPods and I can't have them both, because they depend on different MMKV version.

**Comment by bjjeong** [comment]
> Hey @bjjeong, could you tell how did you migrate data from react-native-mmkv-storage to react-native-mmkv? I have a conflict with CocaPods and I can't have them both, because they depend on different MMKV version.

@dynamichny unfortunately I was only able to migrate because I was able to have both libraries in my project at the same time. I wasn't able to reference the same MMKV instance between the two libraries and instead had to iterate through my old DB and write it into the new DB (which required that both libraries existed in the project at the same time)

Is it not possible for you to downgrade/upgrade one of the libraries to have a compatible shared MMKV version?

**Comment by mrousavy** [comment]
Well react-native-mmkv-storage still uses the native MMKV library, I think you can uninstall react-native-mmkv-storage, and open the same storage instance (passing the same ID) with react-native-mmkv.

So you don't need to "migrate", you just access the same instance but this time with my lib :)

**Comment by asphyxiar** [comment]
iam not able to access the same instance on android with ur lib even when using default instance in react-native-mmkv-storage any suggestion? On Ios iam able to get the instance easily. thanks

**Comment by CaptainSinyak** [comment]
> Well react-native-mmkv-storage still uses the native MMKV library, I think you can uninstall react-native-mmkv-storage, and open the same storage instance (passing the same ID) with react-native-mmkv.
> 
> So you don't need to "migrate", you just access the same instance but this time with my lib :)

How to migrate from react-native-mmkv-storage to react-native-mmkv if I used encryption in react-native-mmkv-storage?
The problem is that I can't migrate because these libraries are incompatible: different versions of MMKVCore. Maybe I can install some earlier version of react-native-mmkv that will be compatible?
