### ISSUE TITLE
Passing down mmkv as createContext

### ISSUE THREAD

**Issue by crystalii** [mrousavy/react-native-mmkv#308]
Hello!

I have two questions which I need help with. In my app, the user fills in a form with about 15 fields which I need to hold in state management in order to pass it between the screens. Currently I am using Zustand for this, but I would like to migrate to this amazing library.

Now having to use storage.set and storage.getString for each of the 15 fields in each screen is obviously not clean and causes me a lot of headache. I believe it would be better if I just created an object, and put all 15 fields in the object as keys, and just retrieve this object. But reading your documentation, I didn't find how to read a specific key of an object, and how to update a specific value of a key in that object? ´

Now the second problem is, if I have understood it correctly then it would be better to put the storage in a Context and pass it down to all screens. This way I don't need to import it to every screen and wait for it to load right? Could you show me some examples on how to do this?

I appreciate all help in this regard, and might even donate to this project if it serves my needs.

**Comment by mrousavy** [comment]
I think you are confusing MMKV with State Management. I would stick with using Zustand, and use MMKV as a storage wrapper (see this PR: https://github.com/mrousavy/react-native-mmkv/pull/278)
