### ISSUE TITLE
Directory size > 300 Mb

### ISSUE THREAD

**Issue by proxymades** [mrousavy/react-native-mmkv#321]
The directory size is 341 MB, which is crazy.

**Comment by mrousavy** [comment]
Which directory?

**Comment by proxymades** [comment]
> Which directory?

In folder node_modules -> react-native-mmkv (341Mb)

**Comment by mrousavy** [comment]
Yes, that's because of your build cache. 

The folders `node_modules/react-native-mmkv/android/build` and `node_modules/react-native-mmkv/android/.cxx` are cache from the native build chain (NDK / C++ / CMake) and will be used for faster builds in the future. The package itself is not nearly as big, it is only 4.9kB in size:

![Screenshot 2022-02-10 at 09 10 11](https://user-images.githubusercontent.com/15199031/153364586-d463ebae-2dd7-41b0-a3e9-8e748667428b.png)

Also, in your original comment you said:

> The size of the bundle after installing the library has increased by 10 MB

That confuses me, since it's wrong. Where did you get that from?

**Comment by mrousavy** [comment]
When you're running react-native-mmkv in a React Native app (no Web), the size of the JS-code files is ~17 KB. Nowhere near 10 MB.

This means your bundle grows 17 KB in size after installing react-native-mmkv.

**Comment by proxymades** [comment]
> When you're running react-native-mmkv in a React Native app (no Web), the size of the JS-code files is ~17 KB. Nowhere near 10 MB.
> 
> This means your bundle grows 17 KB in size after installing react-native-mmkv.

Hi, I edited the message, I made a mistake in the size of the bundle, I'm sorry that it offended you

**Comment by proxymades** [comment]
> Yes, that's because of your build cache.
> 
> The folders `node_modules/react-native-mmkv/android/build` and `node_modules/react-native-mmkv/android/.cxx` are cache from the native build chain (NDK / C++ / CMake) and will be used for faster builds in the future. The package itself is not nearly as big, it is only 4.9kB in size:
> 
> ![Screenshot 2022-02-10 at 09 10 11](https://user-images.githubusercontent.com/15199031/153364586-d463ebae-2dd7-41b0-a3e9-8e748667428b.png)
> 
> Also, in your original comment you said:
> 
> > The size of the bundle after installing the library has increased by 10 MB
> 
> That confuses me, since it's wrong. Where did you get that from?

I'll try to reinstall your library, to be honest I don't like the asynchronous AsyncStorage, I was just scared of > 300Mb, and deleted it, I hope everything works out, thanks

**Comment by mrousavy** [comment]
> I'm sorry that it offended you

Lol no one is offended here 😅 

> I was just scared of > 300Mb

You can also browse the folder sizes yourself and you'll notice that it's only build-cache. This is present in a lot of libraries that use native code. Bundle size won't increase by 300Mb, don't worry

**Comment by proxymades** [comment]
> > I'm sorry that it offended you
> 
> Lol no one is offended here 😅
> 
> > I was just scared of > 300Mb
> 
> You can also browse the folder sizes yourself and you'll notice that it's only build-cache. This is present in a lot of libraries that use native code. Bundle size won't increase by 300Mb, don't worry

Your library is really cool! I tested it. Thanks!

**Comment by proxymades** [comment]
Is it possible to use your library, for example, instead of Zustand or Redux or Apollo cache, to save the application store in it, how realistic is this?
