### ISSUE TITLE
Secure storage

### ISSUE THREAD

**Issue by ahmedu007** [mrousavy/react-native-mmkv#330]
Heyy

Thanks for this awesome library. I was wondering if there is a way to generate a random encryption key without having to manually pass one?

Or basically if there is a migration guide to replace [Expo securestore](https://docs.expo.dev/versions/latest/sdk/securestore/) with an encrypted version?

Thank you for this amazing work btw <3

**Comment by mrousavy** [comment]
Hey Ahmed!

Thanks for the kind words!

> I was wondering if there is a way to generate a random encryption key

How would you open the storage again? 🤨 

The encryption key could be the user's password if you want, but I'd recommend reading [this section in the MMKV documentation regarding encryption](https://github.com/Tencent/MMKV/wiki/android_advance#encryption)

**Comment by ahmedu007** [comment]
Interesting. Didn't think of using user's password. Makes sense. I was sort of expecting something that expo does currently, everything under the hood, managing the keys and exposing `getItem`, `setItem` etc. I guess it just needs a different approach, but essentially would do similar thing. 

Thanks for such a quick response Marc. I'll see what I can do

**Comment by mrousavy** [comment]
MMKV relies on iOS'/Android's sandboxing to "protect" the data from being read by other users, you can additionally encrypt it with a key. But you cannot lose that key.

You can also choose to _additionally_ encrypt the data yourself before storing it everytime 😄 

Often that's not needed and is just very complex though.
