### ISSUE TITLE
Ability to list down all values

### ISSUE THREAD

**Issue by RMG0** [mrousavy/react-native-mmkv#336]
First of all, Thank you for this awesome library. Its much better than using AsyncStorage or any other storage options.

I would like to request a feature something like `storage.getAllData()` or `storage.getMulti(keys)` so we can get all data Or all data based on passed keys.

Currently I am using below function but it will work only for 'string' type values. For example if stored value is boolean, related value would return undefined

```
getAll: function () {
    let values:any[] = [];
    try {
      let keys = MMKVStorage.getAllKeys();
      keys.map(k => {
          //TODO: Note here number and booleans are returned as undefined 
        values.push([k, MMKVStorage.getString(k)]);
      })
      return values;
    } catch (error) {
      logger.warn('Error: getAll ', error);
    }
    return values;
   
  }
```

Thank you

**Comment by mrousavy** [comment]
Hey!

Thanks, this is quite interesting as we don't really know the types of the values unless we access them. I don't think MMKV has a way to expose that either, and I don't want to introduce `x*3` complexity just because we get string, then number, then boolean for every value.

I'll take a look!

**Comment by RMG0** [comment]
Hi,
Yes agree on complexity on this. In most cases this won't be required but in our app, for debugging purpose we want to list down all storage value. Thanks for checking this.

**Comment by RMG0** [comment]
Sorry, by debugging, I mean we want to see storage value in a debugging screen in a release build.

**Comment by mrousavy** [comment]
Here's a hacky solution:

```ts
export function getAllValues(storage: MMKV): (string | number | boolean)[] {
  const keys = storage.getAllKeys()
  return keys.map((key) => {
    const string = storage.getString(key)
    if (string != null) return string
    const number = storage.getNumber(key)
    if (number !== 0) return number // <-- 1.
    return storage.getBoolean(key) // <-- 2.
  })
}
```

1.: We can't be sure if this is actually stored or not. You could store `0.0` in the Storage and my script will think that you don't have a value there, and returns a Boolean instead. This will be fixed when I implement https://github.com/mrousavy/react-native-mmkv/pull/306 :)
2.: Again, we can't really be sure if it is a boolean here. It could even be a completely different type when written to with the native MMKV interface.

I'll take another look at this once I merge #306, maybe there's a way to expose all values. I'm thinking about something like:

```ts
interface MMKV {
  // ...

  toMap(): Map<string, string | number | boolean>

  // ...
}
```

wdyt?

**Comment by mrousavy** [comment]
Actually, I just took a closer look at the native implementation and tried to determine the value type - this doesn't work that way. There's no way in MMKV to determine whether a value is stored as a number, string or boolean. You can only make guesses.

For example, if you store `'1'` (as a string) to MMKV, I don't know if it is a boolean or a string, since both have the same size (1 byte). Same for if you store `'helloooo'`, because that's exactly 8 bytes, aka a `double` (number in JS).

**Comment by RMG0** [comment]
having toMap would be great but I can understand native limitation. I think `getAllValues `will work for me.
Thank you again for all your efforts. I will update you if can get some better way here

**Comment by mrousavy** [comment]
This script returns you all values in `[string, number, boolean]` pairs. Each key can either be a string, number or a boolean, as I mentioned above there's no clear way of determining which is which so here you can just fetch all possibilities and interpret it however you want to 😄 

```ts
export function getAllValues(storage: MMKV): [string, number, boolean][] {
  const keys = storage.getAllKeys()
  return keys.map((key) => {
    return [storage.getBoolean(key), storage.getNumber(key), storage.getString(key)]
  })
}
```

**Comment by RMG0** [comment]
Awesome, I think I can use this for my case. Thank you so much for all support.

**Comment by bombillazo** [comment]
Hey! Thanks for the awesome work on the library. 

May I suggest for this use-case having an internal mapping storing what method was used for the set key, then the method can internally track what type it is vs checking at runtime when reading from the store? 

Perhaps it's a tradeoff on some speed but would be of great utility.

**Comment by mym0404** [comment]
Well this function works pretty well.
```ts
  _DEBUG_dumpListToConsole = () => {
    let ret = '-------START OF MMKV DUMP-------\n';
    const obj: any = {};
    for (const key of mmkv.getAllKeys()) {
      const stringValue = mmkv.getString(key);
      if (typeof stringValue === 'string' && stringValue.length) {
        obj[key] = stringValue;
        continue;
      }
      const numberValue = mmkv.getNumber(key);
      if (typeof numberValue === 'number') {
        obj[key] = numberValue;
        continue;
      }
      obj[key] = mmkv.getBoolean(key);
    }
    ret += formatJson(obj);
    ret += '\n-------END OF MMKV DUMP-------';
    // eslint-disable-next-line no-console
    console.log(ret);
  };
```
