### ISSUE TITLE
Lowest supported React Native version

### ISSUE THREAD

**Issue by dynamichny** [mrousavy/react-native-mmkv#343]
Hey, 
I am curious what's the lowest RN supported version, because it's not provided in README

**Comment by mrousavy** [comment]
0.63

**Comment by dynamichny** [comment]
@mrousavy Doesn't it need RN 0.65 from version 2.0 of the package, as it started to install automatically there? I've seen in previous android installation that it will be removed when "MMKV can be autoinstalled (maybe RN 0.65)" - could you confirm?

**Comment by mrousavy** [comment]
Nope, I found a solution that should work on every React Native version that has JSI 😄

Let me know if you run into any issues
