### ISSUE TITLE
[npm] Release 2.1.1 is missing `lib` folder

### ISSUE THREAD

**Issue by giovannilondero** [mrousavy/react-native-mmkv#348]
As per title, release 2.1.1 on npm is missing the `lib` folder

`yarn add react-native-mmkv@2.1.0` (or previous version) => lib is present

`yarn add react-native-mmkv@2.1.1` => lib not present

Am I missing something or should it be released again?

**Comment by sharifhh** [comment]
yeah they missed the typescript declaration ... now the library shows typescript errors

**Comment by mrousavy** [comment]
oh whoops?

**Comment by sharifhh** [comment]
Thanks @mrousavy !

**Comment by giovannilondero** [comment]
Solved with v2.1.2, thanks 👍

**Comment by chrispader** [comment]
Whoah, that was quickly solved 🚀😅

Thanks a lot!
