### ISSUE TITLE
Hooks Object - Date being converted to string

### ISSUE THREAD

**Issue by nescroft** [mrousavy/react-native-mmkv#352]
Try the code below. If you refresh the page DateMMKV.date becomes a string instead of a date. This happens if you are making edits to the object at all. The dates become strings. Please let me know if i'm doing something wrong.

```
const [DateMMKV = {date: new Date()}, setDateMMKV] = useMMKVObject('DateMMKV');
const [DateState, setDateState] = useState({date: new Date()});

useEffect(() => {
    console.log('test');

    console.log(DateMMKV);
    setDateMMKV(DateMMKV);

    console.log(DateState);
    setDateState(DateState);

  }, []);
```

FIRST OUTPUT:
test
{"date": 2022-03-13T16:58:20.587Z}
{"date": 2022-03-13T16:58:20.587Z}

OUTPUT AFTER REFRESH:
test
{"date": "2022-03-13T16:58:20.587Z"}  <--- becomes a string instead of a date
{"date": 2022-03-13T16:58:20.587Z}

**Comment by nescroft** [comment]
It seems when you use setDateTest it enters it as a string. Which makes sense if it is being stored on the device. The same thing happens if you use JSON.stringify on an object with a date. Closing this issue for now.

**Comment by mrousavy** [comment]
Hi!

I don't think I really understand the issue, does the MMKV object actually hold a string instead of the Date as the type says? Then it would be a bug and the issue should be left open...

**Comment by mrousavy** [comment]
Actually this is not MMKV's fault. 

```ts
const date = new Date()

const serialized = JSON.stringify(date)
const deserialized = JSON.parse(serialized)
console.log(typeof deserialized)
```

JSON.stringify makes `Date` -> `string`, and JSON.parse does not make `string` -> `Date` because there's no info about that. That's simply how JSON parsing works in JS.
You could add your own separate logic here, but storing **complex instances** (e.g. Date) is technically not supported in MMKv or any kind of external storage library. You can't store a class either.

**Comment by mrousavy** [comment]
Yea you can store the Date time value (milliseconds, `number`) and re-parse that everytime.

**Comment by mrousavy** [comment]
I think MMKV should still warn about such behaviour.... Maybe if something isn't an `object`, `array`, `string`, `number` or `boolean` we can warn in console? Or even have it as a type

**Comment by nescroft** [comment]
Ya that might be nice. Even just some information about it in the docs would probably be sufficient.
