### ISSUE TITLE
i get this error when i run cd android &&./gradlew clean && ./gradlew assembleDebug && cd ..

### ISSUE THREAD

**Issue by thanhnvpk01168** [mrousavy/react-native-mmkv#357]
I don't know how to fix it, can anyone help me?

<img width="1301" alt="Screen Shot 2022-03-17 at 2 31 32 PM" src="https://user-images.githubusercontent.com/58645779/158758906-f3afa4ff-6f52-4630-a400-86f6c3475a16.png">

environment:
"react-native": "0.63.3",
"react-native-mmkv": ^2.2.0,
"@react-native-firebase/app": "^8.3.0",
"@react-native-firebase/crashlytics": "^8.3.0",
"@react-native-firebase/messaging": "^7.6.1",......

**Comment by mrousavy** [comment]
Hey, I need to download a library to compile into MMKV and it looks like you either did not allow internet access for Android Studio/gradle or you do not have internet access

**Comment by thanhnvpk01168** [comment]
hi @mrousavy, 
So what do i need to allow internet access?

**Comment by mrousavy** [comment]
I don't know, I bet google has some answers

**Comment by thanhnvpk01168** [comment]
ok, thank you
