### ISSUE TITLE
Jest Mocking react-native-mmkv

### ISSUE THREAD

**Issue by radelcom** [mrousavy/react-native-mmkv#367]
Hi,

is there a way or provided way to easily mock this great library? 

would be great if we can provide mocks directly from the library similar way to how [AsyncStorage](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest) does

Thanks!

**Comment by mrousavy** [comment]
Hey, this seems to be very weird to let the user set up all of this - I think there's better examples (e.g. Reanimated) that automatically mock everything

**Comment by radelcom** [comment]
@mrousavy, yeah that looks simpler. Anything that will help other people using this package so that we dont need to look else where or make our own mocking.

**Comment by mrousavy** [comment]
Sure, if you shoot me a PR I'll be happy to review, test and merge it :)

**Comment by mrousavy** [comment]
Hey! I think mocking should now work! Thanks everyone! :)

**Comment by norellanac** [comment]
Add a wrapper provider to your App/Component

```
import { Provider } from 'react-redux';
import store from '../stores/store';

export const renderWithProviderTheme = (component: React.ReactElement) => {
  const { debug, ...rest } = render(
      <Provider store={store}>{component}</Provider>,
  );

  return {
    debug,
    ...rest,
  };
};
```

**********************
```
import { renderWithProviderTheme } from '...';

describe('Render with provider, store(mmk)', () => {
  test('Should render correctly component', () => {
    renderWithProviderTheme(
      <MyComponent/>,
    );
  });
```
