### ISSUE TITLE
useMMKV return type

### ISSUE THREAD

**Issue by hlspablo** [mrousavy/react-native-mmkv#369]
useMMKV is returning something like {"current": {"mst.storage": [Array]}}, but the return type is MMKV.
Seems that it uses useRef internally, but the TS type is:  useMMKV(configuration: MMKVConfiguration): MMKV (+1 overload)
is safe to ignore it and just use .current notation? because im getting TS error
Im using version 2.3.0

**Comment by mrousavy** [comment]
Sorry, had a ts-ignore there that f*cked up the return value. Fixed in [v2.3.1](https://github.com/mrousavy/react-native-mmkv/releases/tag/v2.3.1)! 👍
