### ISSUE TITLE
Android: error: cannot find symbol MmkvModule.install

### ISSUE THREAD

**Issue by 3DJakob** [mrousavy/react-native-mmkv#38]
I installed this module and successfully used it on iOS. I then preceded with following the steps for setting up android with reanimated installed copying the code from the example. It could not find the module so I had to add it manually by adding
```
include ':react-native-mmkv'
project(':react-native-mmkv').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mmkv/android/')
```
to `settings.gradle` and in `build.gradle` adding
```
implementation project(':react-native-mmkv')
```

As described here: https://github.com/mrousavy/react-native-mmkv/issues/37

Strangely enough, it had added the code ```implementation 'com.tencent:mmkv-static:1.0.10'``` there from before but with that code it simply cannot load the module.

However when I try to build the project in android studio it fails with:

```
/Users/jakob/coding/my-app/android/app/src/main/java/com/striveapp/StriveJSIPackage.java:17: error: cannot find symbol
        MmkvModule.install(jsContext, reactApplicationContext.getFilesDir().getAbsolutePath() + "/mmkv");
                  ^
  symbol:   method install(JavaScriptContextHolder,String)
  location: class MmkvModule
  ```
Am I missing something here? Perhaps the module gets loaded incorrectly and thus cannot run the function? Just a noob with android development here, please tell me if you need some other information.

**Comment by mrousavy** [comment]
Sorry I don't quite get the part with `implementation 'com.tencent:mmkv-static:1.0.10'` - where did that come from?

Did you add the import statement on top of StriveJSIPackage?

**Comment by 3DJakob** [comment]
Hey! The 1.0.10 was in the file from the beginning so I replaced it with that other line. I guess it got there when it was trying to auto-link the dependency?

Yes android studio studio says "cannot resolve method 'install' in 'MmkvModule'

However, maybe the problem is before that. On this line `public class StriveJSIPackage extends ReanimatedJSIModulePackage {` it says `cannot resolve symbol ReanimatedJSIModulePackage`

Thank you for your time!

**Comment by mrousavy** [comment]
Could you share your versions? Reanimated, React Native, MMKV please

**Comment by 3DJakob** [comment]
Sure!
react-native 0.63.2
react-native-reanimated 2.0.1
react-native-mmkv 1.0.10

Running android studio in rosetta on an M1 Mac could be related.

**Comment by mrousavy** [comment]
Hm, that's weird. Don't have an answer for this atm, I'll take a look when I have some free time

**Comment by mrousavy** [comment]
You could try to Cmd+Click the MmkvModule to find out if it actually exists as a class. Also try cleaning & rebuilding gradle

**Comment by 3DJakob** [comment]
Weird indeed. Cmd+Clicking it takes me to the class. Tried cleaning and rebuilding without any luck.

**Comment by 3DJakob** [comment]
Just to verify. This is the correct location for the JSIPackage right? 
<img width="462" alt="Screenshot 2021-03-25 at 19 52 43" src="https://user-images.githubusercontent.com/3826262/112527847-c50bc280-8da3-11eb-95cc-32fa8b8a5dfd.png">

I'm also going to start a fresh project to see if I can get it working there.

**Comment by mrousavy** [comment]
Yes it is the correct location - can you send a **screenshot** from android studio of the entire JSI package file you created?

**Comment by 3DJakob** [comment]
I think I solved it! I made a new scratch project to try this in. At first, I had to do steps described in https://github.com/mrousavy/react-native-mmkv/issues/37. Then I got error finding symbol JSIModulePackage. I then imported it like this in the mainApplication.java:
```
import com.facebook.react.bridge.JSIModulePackage;
```
That snippet is from the reanimated docks https://docs.swmansion.com/react-native-reanimated/docs/installation/. And then voila it compiled! Haven't actually tried using the module yet but seems promising. It looks however like I already tried that in the main repository that has reanimated already but I will do some troubleshooting over there to see if I can get it working there as well.

**Comment by 3DJakob** [comment]
Here is the screenshot you asked for: 
<img width="1665" alt="Screenshot 2021-03-25 at 20 38 21" src="https://user-images.githubusercontent.com/3826262/112533360-26cf2b00-8daa-11eb-856d-000e5246fe52.png">

**Comment by 3DJakob** [comment]
> I think I solved it! I made a new scratch project to try this in. At first, I had to do steps described in #37. Then I got error finding symbol JSIModulePackage. I then imported it like this in the mainApplication.java:
> 
> ```
> import com.facebook.react.bridge.JSIModulePackage;
> ```
> 
> That snippet is from the reanimated docks https://docs.swmansion.com/react-native-reanimated/docs/installation/. And then voila it compiled! Haven't actually tried using the module yet but seems promising. It looks however like I already tried that in the main repository that has reanimated already but I will do some troubleshooting over there to see if I can get it working there as well.

This does not seem to be the issue in the main repository that uses the reanimated module, unfortunately.

**Comment by 3DJakob** [comment]
So when I command+click the `MmkvModule` in my `myAppNameJSIPackage.java` I can't find any public function called `install`. Shouldn't there be one? I attached a screenshot with the file.
<img width="1068" alt="Screenshot 2021-03-25 at 22 00 38" src="https://user-images.githubusercontent.com/3826262/112543043-8bdc4e00-8db5-11eb-81ae-88e927b80dcf.png">

**Comment by mrousavy** [comment]
Oh jesus christ I just noticed you aren't on the latest MMKV version, you have to upgrade to 1.1.4 or something!

**Comment by 3DJakob** [comment]
Haha, I changed to the latest and it solved that problem! However, I'm getting other problems and I just cannot seem to get it to launch without crashing. However, since the problem described in this thread is resolved I will close this now. Thank you so much for your time and effort. Let's hope the android setup will be easier in the future!
