### ISSUE TITLE
MMKV compilation issues after RN macOS upgrade

### ISSUE THREAD

**Issue by Simek** [mrousavy/react-native-mmkv#380]
# Why

After the latest upgrade of `react-native-macos` in my test project (0.64 -> 0.66) MMKV stops compiling.

I'm using the latest version available on NPM which is 2.3.1.

<img width="435" alt="Screenshot 2022-04-18 at 09 36 53" src="https://user-images.githubusercontent.com/719641/163773919-63cf7c53-1b94-4bca-97af-e3b1adc7e345.png">

<img width="1110" alt="Screenshot 2022-04-18 at 09 42 56" src="https://user-images.githubusercontent.com/719641/163774661-af2ea950-d7e6-46e8-ba2b-e26378509475.png">

Downgrading RN MMKV to `2.2.0` has fixed the issue. I can provide more details if needed.

**Comment by mrousavy** [comment]
Ah, sh*t.
Hold on a sec

**Comment by mrousavy** [comment]
Can you check if https://github.com/mrousavy/react-native-mmkv/pull/381 fixes the issue for you?

**Comment by Simek** [comment]
Thanks for the quick answer Marc! Can confirm that manually applying changes from the referenced PR after changing back to `2.3.1` has fixed the issues, however, there are now even more compilation issues reported. 😅 

<img width="456" alt="Screenshot 2022-04-18 at 17 44 26" src="https://user-images.githubusercontent.com/719641/163834281-5c0aca2b-4bf7-4947-bd67-7fba4ca20b17.png">

**Comment by mrousavy** [comment]
Does https://github.com/mrousavy/react-native-mmkv/pull/383 fix that issue as well?

**Comment by mrousavy** [comment]
I wonder how this code here compiles for you, that should actually error out too 🤔 
https://github.com/mrousavy/react-native-mmkv/blob/117eaeb65084541351df41c64d7cd01ab8294acc/ios/MmkvHostObject.mm#L178-L179

**Comment by Simek** [comment]
Yup, it looks like the change from #383 fixed the compilation issues and app runs again. 👍 

The lines you have quoted above do not output any errors or warnings.
