### ISSUE TITLE
Can't use mmkv for react-native-web

### ISSUE THREAD

**Issue by HuuNguyen312** [mrousavy/react-native-mmkv#385]
Dear @mrousavy 

I can't use mmkv (2.3.2) for react-native-web

`Attempted import error: 'unstable_batchedUpdates' is not exported from 'react-native'.`

Please help me resolve it. Thanks

**Comment by mrousavy** [comment]
Hi, can you see if https://github.com/mrousavy/react-native-mmkv/pull/386 fixes the issue for you?

**Comment by mrousavy** [comment]
Fixed & Released in [v2.3.3](https://github.com/mrousavy/react-native-mmkv/releases/tag/v2.3.3) 🎉

**Comment by mrousavy** [comment]
If you appreciate my efforts please consider sponsoring me on GitHub so I can have more time in the future to work on issues like these. 🙏
