### ISSUE TITLE
Android build error "package com.reactnativemmkv does not exist"

### ISSUE THREAD

**Issue by jesse-savary** [mrousavy/react-native-mmkv#388]
Hello, not sure what's up but I'm suddenly running into this error w/o any local changes:

```
/client/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:39: error: package com.reactnativemmkv does not exist
import com.reactnativemmkv.MmkvPackage;
                          ^
/client/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:115: error: cannot find symbol
      new MmkvPackage(),
          ^
  symbol:   class MmkvPackage
  location: class PackageList
```

Same issue is also occurring with `react-native-vision-camera`. Latest version of both, running `react-native@0.66.4`.

**Comment by mikepaszkiewicz** [comment]
@jesse-savary I'm running into this today - did you manage to fix it?

**Comment by jesse-savary** [comment]
@mikepaszkiewicz Unfortunately no, the issue seems to be greater: https://youtrack.jetbrains.com/issue/IDEA-292541

Not sure how more people haven't run into this.

**Comment by mikepaszkiewicz** [comment]
@jesse-savary Hmm yeah - will report back here if I make any progress.

**Comment by fastesol** [comment]
having the same problem :(

**Comment by AleP04** [comment]
Me too!

**Comment by mrousavy** [comment]
Can you guys try with completely nuked clean cache for Gradle?

**Comment by fobos531** [comment]
> java.io.FileNotFoundException: https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-1.xml

Hey, I've encountered an issue demonstrated in [this comment](https://github.com/mrousavy/react-native-mmkv/issues/388#issuecomment-1105838355). I tried applying your solution on a macOS machine (`rm -rf .gradle/caches/`) and running a local Expo EAS build - it seems to work for me!

**Comment by ajiehatajie** [comment]
sames issue

**Comment by jamal0909** [comment]
try to run the command with sudo.

sudo npx react-native run-android

**Comment by unicornRainbows** [comment]
Same issue for me.

**Comment by salimsea** [comment]
hey bro, how about this problem? has anything worked?

Same issue for me.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/49223890/221394685-aae227da-b910-4b4a-9c42-a66eef2023ae.png">

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Comment by astikatika** [comment]
same issue for me

**Comment by anultravioletaurora** [comment]
> Remove `android/build` and `android/app/build` folders works for me.

Worked for me too!

**Comment by dhruv-1010** [comment]
i was able to fix this by clearing my cache folders just open android subfolder of ur project and 
run 
`rm -rf .gradle/caches/`
also remove `android/build` and `android/app/build `folders as mentioned by @Jin39 , for me it happened as one of my other branch was on a newer version of gradle and the build caches were not cleared when i switched to older branch
