### ISSUE TITLE
JSON Parse error: Unexpected token: u

### ISSUE THREAD

**Issue by ddikodroid** [mrousavy/react-native-mmkv#391]
First, thank you for creating this awesome package!

I try to use the package on my project, but today I found an error like this
![Simulator Screen Shot - iPhone 13 - 2022-04-22 at 15 25 33](https://user-images.githubusercontent.com/4207774/164649166-9c38e025-998c-4907-9ce8-c41c1e771708.png)

I'm creating custom hooks to retrieve user data from storage.
```
export const useUser = () => {
  const json = storage.getString('user');
  const user = JSON.parse(json);
  return user;
};
```

Is the data should be available from the beginning? because i get the user data after the login.

Thank you!

**Comment by ddikodroid** [comment]
Fixed

I modify the code to be like this
```
export const useUser = () => {
  const hasUser = storage.contains('user');
  if (hasUser) {
    const json = storage.getString('user');
    const user = JSON.parse(json);
    return user;
  }
};
```

**Comment by mrousavy** [comment]
I'd recommend you use TypeScript/VSCode. `json` can be `undefined`, I'd check for undefined here instead
