### ISSUE TITLE
Accessing stored data or set data from native code?

### ISSUE THREAD

**Issue by hellofarhan** [mrousavy/react-native-mmkv#396]
Hi, Thank you for this wonderful library. Is it possible to call read/write functions from native code? 

Sorry for asking questions that are a bit outside the scope of this library. I know it is supposed to be react-native context, but some documentation about how this work behind the scene would be fantastic.

**Comment by JoaoOliveiraRocha** [comment]
hello @hellofarhan 

I just found (literally 20 minutes ago) a way to check for those values for Android.

I'm using to check if the user has anylaunch the dark/light splash. But I feel it can be used for any setting.

``` java
import com.tencent.mmkv.MMKV;

(...)


public class MainActivity extends ReactActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(null);

// I'm using the default location. From the docs it's the:  getFilesDir().getAbsolutePath() + "/mmkv";
// The initialize method supports Context and/or Strings. I believe you can pass the directory to this method.
        MMKV.initialize(this);

        MMKV kv = MMKV.defaultMMKV();
        String userSetTheme = kv.decodeString("com.yourApp.themePreferenceKey");

// here you can conditionally check for the userSetTheme, System theme, etc.
        RNBootSplash.init(R.drawable.splash_background, MainActivity.this);
    }
```

I'll probably be using using a `try ... catch ...` for using the app for the first time (I haven't tried it yet). I believe the code this is based on (https://github.com/Tencent/MMKV) demands/strongly suggests it anyway.

I'll try to do the same for iOS now.

**Comment by keremoge** [comment]
> I absolutely do not recommend reading/writing values from native code - there might be differences in configuration, and MMKV is not enabled in multi-process mode. Also, the even listener code does not work when you access it from native.

But in some cases we need data from mmkv before the react bundle initializes, for example in AppDelegate, StartupManager, etc., can you support this usage?

**Comment by mrousavy** [comment]
Sure, contact us at hello@margelo.io for consulting, shouldn't take long to implement. :)

**Comment by mrousavy** [comment]
Closing for now until we work on that
