### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by arthurgeron-work** [mrousavy/react-native-mmkv#397]
I'm running some analysis on my business' application and came through this data from xCodes Instrument on Memory Leak analyzer mode:
<img width="1274" alt="Captura de Tela 2022-05-16 às 19 41 25" src="https://user-images.githubusercontent.com/71399856/168694006-14552e2c-2a44-49cf-a148-6f9907b4a3b6.png">
It seems like there's a memory leak with mmkv's get function:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/71399856/168694229-73b01718-5f22-4a18-9fe4-86f44e2af7fb.png">

Xcode's Instrment's Profile data:  https://drive.google.com/file/d/10TX6kSu9b8Y8jtHkaeLHrFDQeY9ufYWt/view?usp=sharing
Currently using react-native-mmkv@2.3.0 and react-native@0.67.4

**Comment by mrousavy** [comment]
Oh that's interesting! Could you profile if this happens on Android too?

**Comment by alzalabany** [comment]
i got same results on IOS, is it possible to introduce a something like "release memory" function example in FastImage we use `FastImage.clearMemoryCache()` after the component unmount to clear the image from memory and use the disk cache

**Comment by mrousavy** [comment]
Yea I think this is a leak, and adding a clear function is a bit hacky. I'll need to find the root cause for this, but if this is in [MMKV's codebase](https://github.com/Tencent/MMKV) then maybe we should create an issue there?

**Comment by mrousavy** [comment]
Possibly related? https://github.com/mrousavy/react-native-mmkv/issues/440

**Comment by Nasseratic** [comment]
@mrousavy Hi, any updates about this? We are ready to migrate to mmkv but we are worried about this 😿

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
