### ISSUE TITLE
Usage with a library

### ISSUE THREAD

**Issue by KaiVolume** [mrousavy/react-native-mmkv#399]
Hey 👋 

Im building a library, for context its just a single component that I require react-native-mmkv for. I cannot seem to get this to work unless I explicitly add this package as a dependency of the actual application that imports my component (and have to pod install on iOS)

Is there a way to ensure the auto install works on the end installation of my package without any additional install steps required?

Thanks

**Comment by mrousavy** [comment]
Hi!

Wdym installation steps? I found a clever way of automatically installing the library, so you don't need any installation steps (except `pod install`, which you cannot get around since it's a native library) :)

**Comment by KaiVolume** [comment]
Hi @mrousavy,

The issue is, the magic automatic install isn't working for our use case. As we install this package in our library X, the end user installs X and only get the library working if they then add the package as a dependency in their app. We are hoping to not require the additional step of them adding this to their package.json, and be able to bundle everything required with our library X. 

Hope that makes sense. :D

**Comment by KaiVolume** [comment]
Thats exactly the problem, the auto linking doesn't work for dependencies of dependencies. 
It all works if i manually install this package at the app level, then pod install. 
But for shipping my library I would like to avoid that

**Comment by mrousavy** [comment]
I see - well you will need to tell the user to install RN MMKV. If you want to check whether the auto-install worked, you can try this code:

```ts
import 'react-native-mmkv'

if (global.mmkvCreateNewInstance == null) {
  throw new Error('react-native-mmkv is not correctly installed!')
}
```
