### ISSUE TITLE
 Failed to create a new MMKV instance, the native initializer function does not exist

### ISSUE THREAD

**Issue by fencer-yd** [mrousavy/react-native-mmkv#403]
This error is occured when I restart the app in the development environment。

react-native: "0.68.2"
expo: "45.0.0"
react-native-mmkv: "^2.4.1"

![image](https://user-images.githubusercontent.com/18526704/172041110-aad827a7-27cd-4af0-91b1-f935b939b650.png)

**Comment by fencer-yd** [comment]
![image](https://user-images.githubusercontent.com/18526704/172041323-6c407457-8a76-460b-aa4e-19f897e19af1.png)

**Comment by todorone** [comment]
This happens to me also, mmkv, expo versions are the same.

When starting the app on iOS, all good. Then usually all good with working on code with fast refresh.

But after some code change it throws error and even JS bundle reload does not help, only removing app from memory helps.

**Comment by mrousavy** [comment]
This was an issue with Expo. The latest Expo SDK should fix this!
