### ISSUE TITLE
How to set the "group directory" for iOS

### ISSUE THREAD

**Issue by siderakis** [mrousavy/react-native-mmkv#404]
I'd like to use MMKV to share data between the React Native app and a native iOS app extension. 

MMKV docs say "When using MMKV in AppExtension or WatchExtension, you should link MMKV to your target by dynamic linking(for details, check the [setup](https://github.com/mrousavy/react-native-mmkv/issues/iOS_setup) again)." Also we need to set the group directory. 

[group directory](https://github.com/Tencent/MMKV/wiki/iOS_tutorial#configuration)

Is this possible with this library? thanks!

**Comment by mrousavy** [comment]
Hey! There's a PR for this, try testing it and let me know if it works: https://github.com/mrousavy/react-native-mmkv/pull/402

**Comment by shawarmaz** [comment]
+1 this is a roadblock for me

@mrousavy how much $ would you prioritize this for? re your tweet on bounties: all for it 🚀

**Comment by mrousavy** [comment]
Hey! Sorry didn't see your comment @shawarmaz. This is implemented now already in latest MMKV version!! :)
