### ISSUE TITLE
Fails to compile with RN 0.69

### ISSUE THREAD

**Issue by oblador** [mrousavy/react-native-mmkv#407]
When using latest RC 6 the project fails to compile with:

```
FAILURE: Build failed with an exception.

* Where:
Build file '[...]/node_modules/react-native-mmkv/android/build.gradle' line: 163

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv'.
> Expected directory '[...]/node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.
```

I think this is due to hermes now being bundled as source code. It's possible that using the newish `com.facebook.react` gradle plugin instead would solve these problems and greatly simplify your `build.gradle`.

**Comment by mrousavy** [comment]
Ah yes, that'd be awesome! Do you have any references for that new plugin?

**Comment by mrousavy** [comment]
...does it even work with CMake? They're using Makefiles...

**Comment by chentogit** [comment]
Is there a solution? I also encountered this problem.

**Comment by ajiehatajie** [comment]
same problem

**Comment by YangJonghun** [comment]
`android/build.gradle` file's
`def rnAAR = fileTree("${defaultDir.toString()}").matching({ it.include "**/**/*.aar" }).singleFile`
above code makes this problem, pattern should be change from RN0.69

indicated below is sample from `react-native-reanimated`
"**/react-native/**/*${buildType}.aar"

**Comment by brandon-austin-lark** [comment]
+1

**Comment by mrousavy** [comment]
Is this even still a problem with the latest MMKV? I thought the new buildscript fixes that?

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=iL-o8IJhwSQ&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=16

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Comment by doneill** [comment]
@mrousavy What version works with 0.69 that you can't reproduce with? I can reproduce with any version and 0.69?

**Comment by doneill** [comment]
```
error Failed to build the app: No package name found. Found errors in /.../node_modules/react-native-mmkv/android/src/hasNamespace/AndroidManifest.xml.

[!] Invalid `Podfile` file: unexpected token at 'info Run CLI with --verbose flag for more details.
```

**Comment by mrousavy** [comment]
RN 0.69 is not supported anymore. It's a pretty old version when it comes to stuff like new arch and changes like these.
