### ISSUE TITLE
Use dynamic storage instance for hooks ?

### ISSUE THREAD

**Issue by DCKT** [mrousavy/react-native-mmkv#411]
Hello,

My app has a demo mode, and I would like to use a different storage instance in order to simplify the way to clean it.
I tried this implementation but it's not responsive and things are unsync, maybe this is not-op ?

```js
const useMmkvList = () => {
  const defaultStorage = useMMKV()
  const demoStorage = useMMKV({ id: "demo" })
  const [env, _] = useMMKVObject("env")

  useMMKVObject("list", env.isDemoMode ? demoStorage : defaultStorage)
}
```

It looks like I need to re-render a second time after the env is updated.

EDIT : [I've made a repo with my example ](https://github.com/DCKT/mmkv-hooks-instance/tree/master)

Thanks for your help.

**Comment by mrousavy** [comment]
Hey! I see!

Currently we update the value when the key changes, or when a new value is set (listener), but not if the mmkv instance changes. We need to add that logic as well somehow https://github.com/mrousavy/react-native-mmkv/blob/ab6584a814f9fb48430792ea358873310d3eda8a/src/hooks.ts#L85-L102

**Comment by DCKT** [comment]
Thanks for pointing out the code ! I'll try to make you a PR :)
