### ISSUE TITLE
I can't seem to build successfully; arm64 error comes up.

### ISSUE THREAD

**Issue by MyloCarson** [mrousavy/react-native-mmkv#413]
![Screenshot 2022-06-24 at 01 49 24](https://user-images.githubusercontent.com/12560014/175438295-295ab7d0-38f8-45b2-ab65-b8e9cca9c385.png)
![Screenshot 2022-06-24 at 01 49 32](https://user-images.githubusercontent.com/12560014/175438299-bd1e6ca3-2991-492d-9042-4e33e1d67d2b.png)

Xcode version: 3.4
RN 0.68.2

**Comment by demerzel3** [comment]
If you happen to be using `use_franeworks!` in your `Podfile` this might help you: https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/96#issuecomment-1124519698

did the trick for me 🙂

**Comment by MyloCarson** [comment]
A fix that worked.
`
....

use_frameworks!

target 'Flip' do
  ...

end

pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('react-native-mmkv')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
end
`
