### ISSUE TITLE
rn-web with mobx-persist-store issue

### ISSUE THREAD

**Issue by LukasMod** [mrousavy/react-native-mmkv#415]
Hi, 
My app runs on android, ios and web platforms.
On android and ios the problem does not occur.

In storage.ts I create 

```
export const storage = new MMKV()

configurePersistable({
    storage: {
        setItem: (key, data) => storage.set(key, data),
        getItem: key => storage.getString(key),
        removeItem: key => storage.delete(key),
    },
})
```

Data saves and loads correctly everywhere, including the web. Or I didn't notice in the web that something was not working.
I only get this error, 3 times in web after compiling (we use next.js)

```
error - node_modules/react-native-mmkv/lib/commonjs/createMMKV.web.js (1:681) @ storage
Error: Tried to access storage on the server. Did you forget to call this in useEffect?
null
```

I noticed that the error flies when canUseDOM: false. I would hate to leave code that works but generates error logs. How to understand this message and what can be done about it? I've been combining a bit with useEffect in App.tsx but it hasn't helped.

 ```
   "react-native": "0.64.2",
    "react-native-mmkv": "2.4.1",
    "mobx": "6.1.8",
    "mobx-persist-store": "1.0.6",
    "mobx-react": "7.3.0",
```

Thank you for any help

**Comment by mrousavy** [comment]
cc @axeldelafosse @nandorojo - do we need the `canUseDOM` check?

**Comment by nandorojo** [comment]
yeah we do. this would happen if you're reading storage in the global
scope / in render / not in `useEffect`. this isn't recommended for `localStorage` in general on Web. 

i recommend moving the Web code to an effect, or only rendering the components using it on the client (let me know if you need me to show you how).

alternatively, we could add an option to silence the warning, and it will just return `undefined` if you call it on the server.

**Comment by LukasMod** [comment]
@nandorojo  `UseEffect` is rather out, as it would be too much work, and I don't want to interfere too much with a properly working android/ios. Any tips on the second solution (render on client) would be very helpful.

**Comment by ataschz-g** [comment]
Hey guys, I'm receiving the same error when try to use in NextJS app. Basically, I'm crearing a MMKV instance into a global Provider to persist the user auth and check ir later, but I'm not sure how check it only in the client-side.

**Comment by nandorojo** [comment]
this is just a fact of web development. storage doesn’t exist on the server, and react hydration requires that props match on the client and server. so you could use a `Platform.OS` check and then set it in an effect on web. or you can use `next/dynamic` with `ssr: false` if you’re using Next.js. but this will disable all SSR for its children, so you may not want to do that if you’re using this for the root provider of your app

**Comment by ataschz-g** [comment]
Uhmmm... I got it. Do you have an example of this implementation? I'm not sure how implement it.

**Comment by nandorojo** [comment]
Assuming this component renders on the server, you have a few options:

## Import in an effect

```ts
import { Platform } from 'react-native'
import { useLayoutEffect, useEffect } from 'react'

const useIsomorphicLayoutEffect = typeof window == 'undefined' ? useEffect : useLayoutEffect

function App() {
  const [value, setValue] = useState(() => {
    if (Platform.OS !== 'web') { return storage.getString('userId') }
  })

  useIsomorphicLayoutEffect(function readWebStorage() {
    if (Platform.OS === 'web') { setValue(storage.getString('userId') }
  }, [])

  if (value) // do something
}
```

This should be fine for all use cases imo, since values returned from storage are never required to exist on the initial render. After all, they have to be set at some point.

Also, it's a good practice to not call `localStorage.getItem` in a render-blocking manner on Web in general, since it can be unpredictable in time.

## Next.js dynamic import

If you're using storage in a one-off component, and you're using Next.js, you could do this too:

```tsx
export default function ClientOnlyComponent() {
  const [value, setValue] = useState(() => storage.getString('userId'))

  return <Text>{userId}</Text>
}

// then in another file:
import dynamic from 'next/dynamic'
const ClientOnlyComponent = dynamic(() => import('./client-only-component'), { ssr: false })
```

## Window check

If, for some rare reason, you're reading from storage **but you aren't using the result in the first render**, then you could do something like this:

```ts
let userId
if (Platform.OS === 'web' && typeof window != 'undefined') {
  userId = storage.getString('userId')
}
```

**Comment by nandorojo** [comment]
From `mobx-persist-store`'s [docs](https://github.com/quarrant/mobx-persist-store#storageoptions--reactionoptions):

> If you have an app that is Server-side rendering (SSR) you can set the value `undefined` to prevent errors.

<img width="866" alt="Screen Shot 2022-07-06 at 8 21 24 PM" src="https://user-images.githubusercontent.com/13172299/177663586-c728485b-6c9d-4f4b-b8e7-884603c1b16b.png">

**Comment by LukasMod** [comment]
@nandorojo 
Thanks for your help. Finally what worked for me was combination of "Window check" and storage: undefined.

In my storage.web.ts i did:
```
export const persistedStorage = configurePersistable({
    storage:
        typeof window != 'undefined'
            ? {
                  setItem: (key, data) => storage.set(key, data),
                  getItem: key => storage.getString(key),
                  removeItem: key => storage.delete(key),
              }
            : undefined,
})
```
Persisting works and there is no more errors from mmkv in rn-web.
