### ISSUE TITLE
[Can't reproduce for now] Android Studio C/C++ Configuration Problem

### ISSUE THREAD

**Issue by Thanaen** [mrousavy/react-native-mmkv#418]
Hello,
I have a warning message on Android Studio that says this: 
Title: "C/C++ Configuration Problem"
Contents: Lots of text, but one line that mentions an error: `C:\Projects\my-project\node_modules\react-native-mmkv\android\src\main\cpp\cpp-adapter.cpp:2:10: fatal error: 'jsi/jsi.h' file not found #include jsi.h> ^~~~~~~~~~~ 1 error generated. `

I could not reproduce this error on a freshly created react-native project, so it must be related to my development environment.

Note that this error message does not seem to prevent the react-native-mmkv package from working.

My project is using expo@^45.0.0.
Output of `react-native info`
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 16.88 GB / 31.61 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220306.015012.0 - C:\Dev\Utils\watchman-v2022.03.07.00-windows\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.2.32616.157 (Visual Studio Enterprise 2022), 16.11.32510.428 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.14.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.68.0 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Here is the full error message created by Android Studio: https://pastebin.com/5WrnrgvL

Do you have any idea what could be causing this problem?

Thanks in advance

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
