### ISSUE TITLE
Alternatives for building via Expo Go

### ISSUE THREAD

**Issue by bgeshk** [mrousavy/react-native-mmkv#420]
I am getting the `react-native-mmkv is not supported in Expo Go!` error. Can somebody please point me to a way around this?

**Comment by mrousavy** [comment]
Yes, use `expo prebuild` (google: "Expo Custom Dev Client")

**Comment by alexco2** [comment]
I´m running expo prebuild and I am still getting this error

```
Error: react-native-mmkv is not supported in Expo Go! Use EAS (`expo prebuild`) or eject to a bare workflow instead., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:127:23 in metroRequire
at http://192.168.178.21:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:306187:3 in global
```

**Comment by JuanDavidLopez95** [comment]
Hi all,

This is such an awesome module, my immense gratitude to @mrousavy. Thank you.

I am getting the same error as @alexco2 — `react-native-mmkv is not supported in Expo Go! Use EAS ("expo prebuild") or eject to a bare workflow`. 

This happens even after running `expo prebuild` prior to `expo start`. Have tried running `expo prebuild --clean` and removing the `android/` & `ios/` folders prior.

**Comment by mrousavy** [comment]
Are you sure you're using the custom Dev Client that gets installed on your phone, and not the Expo Go app from the AppStore?

**Comment by mrousavy** [comment]
Here's the Expo check, maybe something's going wrong there? 

https://github.com/mrousavy/react-native-mmkv/blob/f693645e610e267c8f46f6e28e196a7f7fc964c9/src/createMMKV.ts#L29-L42

**Comment by TomasSestak** [comment]
i did the following for someone who still needs to support Expo Go app:

`import { MMKV } from 'react-native-mmkv';

import Constants from 'expo-constants';

const isRunningInExpoGo = Constants.appOwnership === 'expo';

export let storage: {
	setItem: (key: string, value: string) => void;
	getItem: (key: string) => Promise<string | undefined | null>;
	removeItem: (key: string) => void;
};

if (isRunningInExpoGo) {
	const AsyncStorage = require('@react-native-async-storage/async-storage').default;
	storage = {
		setItem: (key: string, value: string) => {
			return AsyncStorage.setItem(key, value);
		},
		getItem: (key: string) => {
			return AsyncStorage.getItem(key);
		},
		removeItem: (key: string) => {
			return AsyncStorage.removeItem(key);
		},
	};
} else {
	const mmkv = new MMKV();

	storage = {
		setItem: (key: string, value: string) => {
			mmkv.set(key, value);
			return Promise.resolve(true);
		},
		getItem: (key: string) => {
			const value = mmkv.getString(key);
			return Promise.resolve(value);
		},
		removeItem: (key: string) => {
			mmkv.delete(key);
			return Promise.resolve(true);
		},
	};
}`

It forces you to continue to use it with await though :/ and AsyncStorage is still installed in ios/Pods even if i install it to devDependencies in package.json :(
