### ISSUE TITLE
Build Error  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Victorvikson1996** [mrousavy/react-native-mmkv#421]
* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> org.gradle.api.InvalidUserDataException: NDK not configured. Download it with SDK manager. Preferred NDK version is '21.4.7075529'. 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by SMhdAsadi** [comment]
As error message suggests, in order to use this library you need NDK. You can download it with SDK manager in:
Android Studio > Tools tab > SDK manager > SDK Tools tab.

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
