### ISSUE TITLE
Build error with compileSdkVersion 31

### ISSUE THREAD

**Issue by DGonzo001** [mrousavy/react-native-mmkv#423]
Hello, my project uses api level 31 with rn version 0.67.4
```
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "22.1.7171670"
    }
```
I get an error when building

```
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.
```

If I understand correctly, now in the rn-mmkv project uses api level 30

```
Mmkv_compileSdkVersion=30
Mmkv_buildToolsVersion=30.0.2
Mmkv_targetSdkVersion=30
android.useAndroidX=true
```
Could you help me solve this problem? Please!

**Comment by capezzbr** [comment]
> com.android.builder.errors.EvalIssueException: Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

Try to uninstall SDK 31 and reinstall from SDK manager

**Comment by bryce0516** [comment]
same issue. already have been tried to reinstall but not working

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=iL-o8IJhwSQ&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=16

**Comment by OHHAKO** [comment]
using sdk31 but not working. anybody same iussue?

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
