### ISSUE TITLE
Is encrypted storage backup & restore friendly?

### ISSUE THREAD

**Issue by abejfehr** [mrousavy/react-native-mmkv#429]
Sorry for leaving an issue in the form of a question, but I just wanted to assess whether [this issue](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/269) would be present in this library.

In short, since MMKV is file-based storage and those files are present in iCloud backups and restored when a backup is restored on a new device, but since the encryption key is different on the new device, encrypted storage is just broken in react-native-mmkv-storage in apps that were restored from iCloud.

Would the same thing happen here?

**Comment by mrousavy** [comment]
Hey! If you restore a key from iCloud KeyChain, this should not happen. Then it's synced across devices.

**Comment by abejfehr** [comment]
My keychain isn't synced with iCloud, but my apps are backed up via iCloud. Would my app just be broken in this case if I got a new phone?

**Comment by abejfehr** [comment]
Sorry, I see now that encryption keys for this library must be specified by the consumer of the library, which _isn't_ the case for react-native-mmkv-storage.

So this exact issue wouldn't happen unless the consumer of this library would have inconsistent keys between app installations

**Comment by mrousavy** [comment]
Exactly! :)
