### ISSUE TITLE
Encrypted store for users that passed auth

### ISSUE THREAD

**Issue by DDushkin** [mrousavy/react-native-mmkv#435]
Hello, I have a use case when I need to create 2 stores. One for regular data and the other for sensitive. The question is that I'm not sure how to correctly initialize them, as in the code for the second one I need to provide an encryption key, right?
But what if I want to encrypt that with a user password/secret key and etc?

I see that there is `storage.recrypt(secret)` function, but should it be like this, then?
 I found some clues in your PR description https://github.com/mrousavy/react-native-mmkv/pull/314
```ts
const storage = new MMKV({ id: 'my.test.storage' })

storage.encrypt('my-private-key') // <-- encrypt with key 'my-private-key'
storage.set('test', 'works!')

storage.encrypt(undefined) // <-- remove encryption
storage.set('test', 'still works!')
```

Does it mean I should use stores like this?

```ts
// store.ts
const regularStore = new MMKV({
    id: "regular",
});

const encryptedStore = new MMKV({
    id: "encrypted",
    // no encryption key on start
});

//auth.tsx
const handleSignUp = (email, password) => {
  ...
  encryptedStore.recrypt(password) // then encrypt on sign up?
}

const handleSignIn = (email, password) => {
  ...
  encryptedStore.recrypt(undefined) // then what to do on next app open and sign in?
}
```

How to use that encrypted store after Signing in next time?
Is that correct that I will need to decrypt the store like this `encryptedStore.recrypt(undefined)`, however it doesn't look correct to leave the store decrypted

**Comment by DDushkin** [comment]
Let's say a user is doing sign in
He enters the correct password
But the store was previously encrypted with a password on signup
How to get access to the encrypted store only after the user signin?
```ts
const handleSignIn = (email, password) => {
  ...
  encryptedStore.recrypt(password) //???
}
```
that does look like resetting the encryption key, not "unlocking" with a password?

So I'm trying to understand how this encryption flow should look like with MMKV
When I encrypted the store with a specific user-provided password on signup, how do I access it again on the next login, as I won't know the encryption password until the user enters it?
Please tell me if that all makes sense to you? @mrousavy

**Comment by DDushkin** [comment]
So far I can see such behavior:
```ts
//-------------
//FIRST APP OPEN
//store.ts
const encryptedStore = new MMKV({
    id: "@encrypted",
});
export { encryptedStore };  // returns a new empty storage

//USER SIGN UP
//signup.ts
encryptedStore.recrypt(password);

//USER USE THE APP
//set_secret.ts
encrypted.set('sercret', 'xyz123');

//-----
//NEXT TIME OPEN
//init.ts
const encryptedStore = new MMKV({
    id: "@encrypted",
    //I guess here suppose to be secret now, but where do I get it
});
export { encryptedStore }; // returns a new empty storage

//USER SIGN IN
//signin.ts
encryptedStore.recrypt(password);

//USER USE THE APP
//get_secret.ts
encrypted.getString('sercret'); // empty
//-------------
```

But how to use first storage with data inside instead of getting new storage each time

It works as expected only if I hardcode the `encryptionKey`, but that is depending on user input

**Comment by mrousavy** [comment]
I would not initialize the `MMKV` instance until you have the password, then load it with the PW as encryption key.

```ts
let mmkv: MMKV | undefined

function onLogin(user: User) {
  mmkv = new MMKV({
    id: 'encrypted',
    encryptionKey: user.password
  })
}
```

**Comment by DDushkin** [comment]
> I would not initialize the `MMKV` instance until you have the password, then load it with the PW as encryption key.
> 
> ```ts
> let mmkv: MMKV | undefined
> 
> function onLogin(user: User) {
>   mmkv = new MMKV({
>     id: 'encrypted',
>     encryptionKey: user.password
>   })
> }
> ```

wow, didn't think that way
thanks for the help!
