### ISSUE TITLE
It downloads boost package every time installing new package

### ISSUE THREAD

**Issue by arasrezaei** [mrousavy/react-native-mmkv#436]
Hello,
thanks for your great package,
there is an annoying bug which this package gets re compiled on android after any yarn | npx install.
may be because of node_modules immutability? 
is there any fix for this?
i tried pach-package but it failes (may be i do use it wrong!)

**Comment by ddikodroid** [comment]
I get the same issue, downloadBoost task every time i build APK file.

react-native: 0.67.2
react-native-mmkv: ^2.4.3

**Comment by LukasMod** [comment]
Same here every time i build APK file.
react-native: 0.68.2
react-native-mmkv: 2.4.3

**Comment by radko93** [comment]
This is similar to #424. This slows down local builds a lot. Especially if you're on a slower network.

**Comment by SectionTN** [comment]
@arasrezaei this should work for you:
https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1214998966

**Comment by androideveloper** [comment]
This is still happenning. This slows down both local and CI builds. Anyone found a fix that would work for both local and CI? 
looks like reanimated fixed a similar issue https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1444337577

**Comment by feedthedevil** [comment]
Same here every time i build APK file.
react-native: 0.66.5
react-native-mmkv: 2.5.1

**Comment by lucianobracco-geojam** [comment]
This is still happening to me
