### ISSUE TITLE
useMMKVObject hook causing issue in app.

### ISSUE THREAD

**Issue by wilcoxky** [mrousavy/react-native-mmkv#438]
I am getting this error when using `useMMKVObject` hook within our own custom hook wrapper. While this issue is related to redux it is being initiated by the `set` call in the hook. In order to work around this I switched the code to use without the hook but also believe I lose the listener effect that a hook. Any help or insight would be appreciated, and thank you for the library.

```js
const useSubscription = (shouldHandleRedirect = false) => {
  const subscription = useSelector((state) => state.iapSubscription)
  const [localSubscription] = useMMKVObject('subscription')
  // .. replacing with line below fixes the issue
  // const localSubscription = JSON.parse(storage.getString('subscription'))

  const [isConnected, setIsConnected] = useState(true)

  const userProgram = useSelector(
    ({ firestore }) => firestore.data?.userProgram
  )
  const [hasSubscription, setHasSubscription] = useState(true)
  const userRole = useSelector(
    ({ firebase: { profile } }) => profile?.role
  )
  const dispatch = useDispatch()

  const navigation = useNavigation()

  useEffect(() => {
     // Work with data...
  }, [subscription, localSubscription, isConnected, userRole, userProgram])

 ... 
}
```

<img width="413" alt="image" src="https://user-images.githubusercontent.com/4010709/182486733-df9bf6d2-e60b-4883-82d4-bd7399ce8084.png">

**Comment by KuiGoan** [comment]
Same +1

**Comment by mrousavy** [comment]
Hmm, maybe it's because of this? https://github.com/mrousavy/react-native-mmkv/blob/77982c1a61a5e6d2683e6569ca92e09390b28c48/src/hooks.ts#L90-L98

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
