### ISSUE TITLE
Recover from data corruption support?

### ISSUE THREAD

**Issue by RZulfikri** [mrousavy/react-native-mmkv#442]
@mrousavy wanna ask, does this library support [Recover from data corruption ](https://github.com/Tencent/MMKV/wiki/android_advance#recover-from-data-corruption)?  I think this feature is quite important.

**Comment by mrousavy** [comment]
I didn't implement it because:

> The repair rate is not promised, though. And you might get unexpected key values from recovery

And to me that's not a fair tradeoff. If the data really gets corrupted, it's probably safer to restart the app with a clean state instead of a partial repaired or weird/broken state.

**Comment by RZulfikri** [comment]
I see. But, can you give me any clue on how to implement this? In my case, once data is corrupted it will break the session that is stored and force users to re-login. so instead of re-login, I wanna keep users re-login and then re-fetch the data from API if needed.
