### ISSUE TITLE
Migrate nested redux slices

### ISSUE THREAD

**Issue by nicencina** [mrousavy/react-native-mmkv#444]
Great library, Marc. I'm trying to migrate from AsyncStorage to MMKV and your "MIGRATE_FROM_ASYNC_STORAGE.md" instructions so far seem spot on. Everything seems to work until the very end of migrateFromAsyncStorage(), where we set() to storage. I have a fairly complex data store that consists of multiple redux slices that combineReducers() into 1 index. So when your script tries to migrate it finds 1 key for the entire data tree and writes it as a string to storage.set(). The result is that my app restarts with no data. I'm guessing that the data is not being transferred correctly because of my data structure.

If I have a redux store via AsyncStorage that looks like:

- persist:root:
    - sliceOne:
        - keyX: "somevalueX"
        - keyY: "somevalueY"
    - sliceTwo:
        - keyZ: "somevalueZ"
        - keyForList:
            - keyA: "valA",
            - keyB: "valB"
            - ...
     - ...

Is your script supposed to work with this, or do I need to iterate through the json tree and enter each key/val myself? If I have to enter each key/val myself then how can I replicate the tree structure? Or... do you think that it's a different issue that's preventing the migration to successfully complete? Any help would be amazing!

**Comment by mrousavy** [comment]
Hey @nicencina!

Personally, I would sleep better if my storage isn't just one big stringified JSON. If I had a key per slice or even per value, it would feel much more solid.
Nevertheless, this should work either way - does your MMKV storage not have any keys at all? How do you create the storage?

**Comment by nicencina** [comment]
Honestly, I didn't know how AsyncStorage was storing everything under the hood. To your point exactly, I broke up the data store into multiple slices for better house cleaning, but then I followed redux-persist conventions in using combineReducers() in order to then rationalize them into how redux expected them. From there I let redux-asyncstorage do the rest. I only found out now when migrating to rn-mmkv when trying to debug I realized that AsyncStorage was returning 1 key with a massive serialized json object.

I create the storage object with:

const initMMKV = () => {
    const secret = async () => getSecretKey(); // retrieves key from Keychain or creates new one
    return new MMKV({
       id: appID,
       encryptionKey: secret.key
    })
}

**Comment by nicencina** [comment]
PS: To store values in the MMKV store I use the redux-persist wrapper that you wrote

**Comment by grifotv** [comment]
@nicencina have you tried nested persists? https://github.com/rt2zz/redux-persist#nested-persists

Make sure you add to the root persist black list the nested persists otherwise data will be stored in both places.

**Comment by nicencina** [comment]
Will give it a try! Thank you

**Comment by RaphBlanchet** [comment]
Hey, I'm late to the party, but I think the problem is that the store is created before the migration is actually run. I added some logs to the `Storage` wrapper proposed in the doc, and when I get `persist:root` the first time it's `undefined`, then the store creates a default state and persist it, wiping the migration.

On my code, my redux-store is imported in the `App.tsx` file, so it's created as soon as the app starts. My `StorageMigrationProvider` is a wrapper that returns null as long as the migration is not completed (which will display my SplashScreen)

```
import { persistor, store } from "@/Store";
import { Provider } from "react-redux";
...
const App = () => {
    return (
        <StorageMigrationProvider>
            <Provider store={store}>
            ...
        </StorageMigrationProvider>
    );
};
```

Unfortunately, this is out of my knowledge of how Redux or React is initialized, so if you have a suggestion I'm available to try it!

**Comment by nicencina** [comment]
Thank you @RaphBlanchet -- it does seem to be a timing issue. In fact, we're also getting some UI library exceptions bc they're trying to render before the migration happens. We're going to try to put a timer at the root TSX component so that the migration happens BEFORE anything else tries to execute/render.

**Comment by ThushalIntervest** [comment]
Hi @nicencina, How solve this issue? I am facing issue when migrate async to mmkv redux-persist states show empty after migrate to mmkv. Storage migrate is went success. But problem is the previous state from asyncstorage(presist) shows null how can i get these state in redux-presists(mmkv). 
Please can give solution for this issue 🙏
