### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by devdeer-robin** [mrousavy/react-native-mmkv#450]
From the documentation I do not understand how to setup an encrypted storage. I get the point how to give an encryption key name in the `new MMKV()` constructor.

But I do not know where I have to paste the iOS / Android lines to make that encryption key available and how to test if it worked. How do I need to do it?

For me, I assume that when I am changing the name of the encryption key in the constructor, I should not be able to read the stored value that was encrypted using the initial key, right?

**Comment by shravanpillow** [comment]
1. Open your Android Studio project.
2. Click on the View menu in the top menu bar.
3. Select Tool Windows from the dropdown menu.
4. Click on Device File Explorer from the submenu.
5. The Device File Explorer window will appear on the right-hand side of the Android Studio window.

Once you have opened the Device File Explorer, you can navigate to the data folder of your app and find the .mmkv file that you want to inspect. The data folder for your app will be located in the following path:

data/data/<your app package name>/

Replace <your app package name> with the package name of your app.

**Comment by ShravanMeena** [comment]
1. Open your Android Studio project.
2. Click on the View menu in the top menu bar.
3. Select Tool Windows from the dropdown menu.
4. Click on Device File Explorer from the submenu.
5. The Device File Explorer window will appear on the right-hand side of the Android Studio window.

Once you have opened the Device File Explorer, you can navigate to the data folder of your app and find the .mmkv file that you want to inspect. The data folder for your app will be located in the following path:

data/data/<your app package name>/

Replace <your app package name> with the package name of your app.

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
