### ISSUE TITLE
Encrypt performance

### ISSUE THREAD

**Issue by Nodonisko** [mrousavy/react-native-mmkv#452]
Hi,
first of all thanks for this amazing lib! We implemented your lib and it works perfectly, but we are using encryption and I am wondering how much this affects performance? Are there any benchmarks that will compare performance with encryption on/off?

Thanks!

**Comment by mrousavy** [comment]
Hey, thanks!

No, I don't have any benchmarks for that. Feel free to benchmark yourself and let me know about the results :)

**Comment by Nodonisko** [comment]
@mrousavy I used https://github.com/mrousavy/StorageBenchmark to benchmark it and it seems that it gives exactly same result as without encryption. I also open PR with this https://github.com/mrousavy/StorageBenchmark/pull/4

**Comment by Nodonisko** [comment]
I did little bit more experimenting at it seems that there is quite i big difference when you will increase size of value.

This is test result for ~15 kb of data:
![Screenshot 2022-09-17 at 12 32 03](https://user-images.githubusercontent.com/5837757/190852370-84bd8ad5-9769-4092-b82f-2525c857b615.png)

And this is result for ~30 kb of data:
![Screenshot 2022-09-17 at 12 33 14](https://user-images.githubusercontent.com/5837757/190852414-bc53c498-d2ae-4ecf-860c-eb6a195d81ca.png)

It is slower but still quite nice if we consider that other storages are not encrypted at all.

**Comment by mrousavy** [comment]
Interesting results! Thanks for sharing

**Comment by Nodonisko** [comment]
@dmahajan980 you can find everything here https://github.com/mrousavy/StorageBenchmark

**Comment by bfricka** [comment]
This isn't surprising. AES is really fast. It's actually somewhat surprising to me that it even takes that much more time.
