### ISSUE TITLE
Propagate value change to native module side

### ISSUE THREAD

**Issue by pke** [mrousavy/react-native-mmkv#453]
More a discussion entry but discussions are not yet enabled here:

Since the value change listener are not directly supported by mmkv native module would it somehow be possible to call the react-native app delegate / MainApplication respectively with a JS emitted event? 

```js
DeviceEventEmitter.emit("mmkv/change", { name: "keyname", newValue: "newvalue", oldValue: "oldValue" })
```

I found no way to register an event listener on the native side, only how to create emitters.

**Comment by mrousavy** [comment]
Hey I think yea you can do that, but you are responsible for implementing it. MMKV does not have that API. Use it together with multi-process to ensure up to date values
