### ISSUE TITLE
Why does it keeps always downloading react-native-mmkv:downloadBoost?

### ISSUE THREAD

**Issue by emagombe** [mrousavy/react-native-mmkv#455]
Everytime I install a new package or remove it downloads react-native-mmkv:downloadBoost again. It's 124 MB everytime!
Isn't there a way to do it offline?

Thanks!

**Comment by nanthawat** [comment]
[software-mansion/react-native-reanimated/pull/3552](https://github.com/software-mansion/react-native-reanimated/pull/3552) I think this should work for this project.

**Comment by mrousavy** [comment]
Should be fixed by #459
