### ISSUE TITLE
Storage is unavailable

### ISSUE THREAD

**Issue by DDushkin** [mrousavy/react-native-mmkv#462]
Hello,
I use mmkv + zustand, and I have such a flow
- user enters PIN code
- I init encrypted store with that PIN
- I start using `useEncryptedStore` inside the app with zustand

After a while started seeing such an error in logs `[zustand persist middleware] Unable to update item '@encrypted', the given storage is currently unavailable.`. 
I tried to re-install the app, but that didn't help.

Here is the code
```ts
// MMKV.ts

let encryptedStorage: MMKV | undefined;

const initEncryptedStorage = (encryptionKey: string) => {
    encryptedStorage = new MMKV({
        id: ENCRYPTED_ID,
        encryptionKey,
    });
    
    if (__DEV__) {
        initializeMMKVFlipper({ encryptedStorage, regularStorage });
    }
};
```

```tsx
//Auth.tsx

const handleEnterPIN = (pinCode: string) => {
      initEncryptedStorage(pinCode);
      navigate(PATH.MAIN_SCREEN);
}
```

```ts
//encryptedStore.ts

export const useStoreEncrypted = create<EncryptedInitialStateModel & EncryptedStoreModel>(
    persist({
      ...
    }, {
            name: ENCRYPTED_ID,
            getStorage: () => mmkvToZustandStorage(encryptedStorage),
        },
    ),
);
```

```tsx
//Main.tsx

const user = useStoreEncrypted((state) => state.user);
const setUser = useStoreEncrypted((state) => state.setUser);

// on setUser call I get [zustand persist middleware] Unable to update item '@encrypted', the given storage is currently unavailable.
```

**Comment by mrousavy** [comment]
Hey! The error you're getting (`[zustand persist middleware] Unable to update item '@encrypted', the given storage is currently unavailable`) is from Zustand, not from MMKV. I am not sure what Zustand means by "currently unavailable", I think this issue is better off at Zustand's repo?

**Comment by DDushkin** [comment]
@mrousavy the problem is that I actually have 2 storages in the app, one non-encrypted that I init on start for non-sensitive data, and there is another encrypted that I init as I posted above with PIN code, and I only have problems with that encrypted one...
Also when I get that error the encrypted one is not displayed in the Flipped plugin, however, when all is good I can see it there

**Comment by mrousavy** [comment]
> Can it be related to storage data corruption? maybe at some point, it doesn't initialize correctly?

Well in that case I'd need a repro without Zustand, can you reproduce that?

**Comment by DDushkin** [comment]
@mrousavy here is what I tried
I removed Flipper
then right after the encrypted store init I added `encryptedStorage.set("SECRET", "TEST SECRET PERSIST");` to set the value to mmkv without Zustand,
then on another screen, I put logs 
```
        console.log(
            encryptedStorage?.getString("SECRET"), // MMKV key
            JSON.stringify(useStoreEncrypted.getState(), null, 2), // Zustand encrypted state
            JSON.stringify(useStoreRegular.getState(), null, 2), // Zustand regular state
        );
```
to see if that mmkv key exists and to see what is inside zustand.

On the first run of the app I can see the correct logs
```
TEST SECRET PERSIST //KEY from MMKV
@ENCRYPTED {
  "email": "andrew...",
  ...
}
@REGULAR {
  "status": "new"
}
```

After that close the app, and remove this line `encryptedStorage.set("SECRET", "TEST SECRET PERSIST");` to test if test key persist between sessions

and now on run I see such logs
```
undefined //KEY from MMKV
@ENCRYPTED {
  "email": "",
 }
 @REGULAR {
   "status": "regular"
 }
```
So I suppose that bug is not related to the zustand and only related to the encrypted storage

**Comment by mrousavy** [comment]
Huh, is `encryptedStorage` itself `undefined`? How do you initialize the `MMKV` instance, do you call `initEncryptedStorage`? If yes, are you 100% sure it gets called?

**Comment by DDushkin** [comment]
The flow is like this
### Initial open
```
PIN_SCREEN
-> onSuccessPIN
   -> initEncryptedStorage(pinCode)
      -> Just for testing I call encryptedStorage.set("SECRET", "TEST SECRET PERSIST");
         -> navigate(PATH.MAIN_SCREEN)

MAIN_SCREEN
-> ecryptedStorage exist
   -> encryptedStorage.getString("SECRET") works
      -> Zustand works
         -> set some data to storage with Zustand
```

### Reload the app (not 100% reproducible bug)

```
PIN_SCREEN
-> onSuccessPIN
   -> initEncryptedStorage(pinCode)
      -> navigate(PATH.MAIN_SCREEN)

MAIN_SCREEN
-> ecryptedStorage exist
   -> encryptedStorage.getString("SECRET") - undefined
      -> Zustand returns a warning that storage is unavailable
         -> if we try to save something to Zustand it won't persist as it is not connected to mmkv
```

So in the end
- `encryptedStorage` is not undefined, as I tried to log it with `getAllKeys()` and I saw stuff inside
- I initialize mmkv as posted above with `initEncryptedStorage(pincode)` on PIN code enter
```tsx
let encryptedStorage: MMKV | undefined;

const initEncryptedStorage = (encryptionKey: string) => {
    encryptedStorage = new MMKV({
        id: ENCRYPTED_ID,
        encryptionKey,
    });
    
    if (__DEV__) {
        initializeMMKVFlipper({ encryptedStorage, regularStorage });
    }
};
```
- I'm sure it is called, I checked it many times and put logs right after the init and on the next screen,

**Comment by mrousavy** [comment]
So you're talking about reloading the app. You didn't mention this in your original post. 

I think the reloading causes the initEncryptedStorage to not be called anymore, that's why MMKV is null. That's not MMKV's fault

**Comment by DDushkin** [comment]
The point is that I show the PIN code screen on every app open, so it is not the case when something gets removed from the RAM, because I re-init it again.
The problem is that on hot-reload or on fatal force close or sometimes on just re-opening the app on 
```
new MMKV({
        id: ENCRYPTED_ID,
        encryptionKey,
    });
```
the expected behavior is that existing storage with provided `encryptionKey` will always be loaded, but I'm saying that it fails in some cases

**Comment by mrousavy** [comment]
Can you create a reproduceable example repo?

**Comment by DDushkin** [comment]
Yeah I will try to do it

**Comment by mrousavy** [comment]
thanks, otherwise it's just impossible for me to fix it

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=iL-o8IJhwSQ&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=16

**Comment by billnbell** [comment]
I would recommend you put this in App.tsx if not defined.

```
new MMKV({
        id: ENCRYPTED_ID,
        encryptionKey,
    });
```

**Comment by danieltvaz** [comment]
Same. When I first init the mmkv instance, works like a charm, but when try to use the instance to read data that I stored, it's just undefined.

**Comment by billnbell** [comment]
yeah global values are not kept when you restart which is why you should listen for appOpen and set it if it is undefined

```
  useEffect(() => {
    const subAppState = AppState.addEventListener('change', async (nextAppState) => {
    check for MMKV and set it.
    }
    return () => {
      if (subAppState) {
        subAppState.remove();
      }
    };
}, []);

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Comment by shadyhussein99** [comment]
@DDushkin I faced the same issue and solved it,  the issue is that encryption in react native is an asynchronus operation and `getStorage` of zustand is a synchronus function so when we initially call zustand store the mmkv instance is not ready yet so global state works as expected but persistance fails as zustand can't find the mmkv instance, the solution is to make the mmkv instance ready early before accessing its coresponding zustand store, here is my solution 

```
let encryptedInstance: string;

export const createZStore: (storeName: string) => StateStorage = (
  storeName: string,
) => {
  const storage = createStorage(storeName, encryptedInstance);

  return {
    setItem: (name, value) => {
      return storage.set(`${storeName}.${name}`, value);
    },
    getItem: name => {
      const value = storage.getString(`${storeName}.${name}`);
      return value ?? null;
    },
    removeItem: name => {
      return storage.delete(`${storeName}.${name}`);
    },
  };
};

export function createStorage(
  storeId: string,
  encryptionKey?: string,
) {

  return new MMKV({
    id: storeId,
    ...(encryptionKey ? { encryptionKey } : {}),
  });
}

export const setupEncryptedStorage = async (encryptedStorage: string) => {
  (async () => {
    try {
      const encryptionKey = await getEncryptionKey(`${encryptedStorage}-key`)


      encryptedInstance = encryptionKey;
    } catch (err) {
      throw err;
    }
  })();
};

export const useStoreEncrypted = create<EncryptedInitialStateModel & EncryptedStoreModel>(
    persist({
      ...
    }, {
            name: 'auth-store',
            getStorage: () => createZStore('auth-store'),
        },
    ),
);
```

And then you need to call ` setupEncryptedStorage('auth-store');` early before setting any values in zustand store, for example I call it in the splash screen

What we do here is that we passed synchronus value which is `encryptedInstance` to the mmkv instance to avoid awaiting the encryption operation, we call the asynchronus encryption operation and update `encryptedInstance` early before accessing the store using `setupEncryptedStorage` function, this solves the issue for me
