### ISSUE TITLE
[iOS] 'TypedArray.h' file not found

### ISSUE THREAD

**Issue by kesha-antonov** [mrousavy/react-native-mmkv#467]
Hi
When I build an app with 2.5.0 it fails with this error

<img width="906" alt="Screenshot 2022-10-22 at 14 28 24" src="https://user-images.githubusercontent.com/11584712/197339033-0af33151-155e-4fe4-bc1c-45428b104ba8.png">

**Comment by zhigang1992** [comment]
reverting to 2.4.4 does work for now

**Comment by ali-io** [comment]
> reverting to 2.4.4 does work for now

reverting is not a solution

**Comment by bombillazo** [comment]
duplicate of https://github.com/mrousavy/react-native-mmkv/issues/465

**Comment by mrousavy** [comment]
Fixed in 740c81065af2ffb1a6d6132d922d732bc52e4c1e, released in 2.5.1 ✅
