### ISSUE TITLE
Exception in HostFunction: Value is undefined, expected an Object

### ISSUE THREAD

**Issue by siderakis** [mrousavy/react-native-mmkv#469]
at MMKV.getBuffer (native)

```
getBuffer(key) {
    const func = this.getFunctionFromCache('getBuffer');
>    return func(key);
  }
```

My code
```
  const [t, setT] = useMMKVBuffer('someToken');
```

This only happens when reloading the JS bundle in the simulator (Pressing R). I've only seen it for Buffer. It happens roughly 1/3 of the time I reload, but after it happens once then it happens consistently until I force close the app.

**Comment by mrousavy** [comment]
Does this happen in the example app as well? Are you sure you rebuilt the native part of the app, `getBuffer` is a new native function.

Also there's no info here on which platform this happens, is that iOS or Android?

**Comment by siderakis** [comment]
iOS. It does work after restarting the native app so the native part seems to be linked correctly. I've only seen it when reloading the JS.

I can try the example app tonight.

**Comment by siderakis** [comment]
I couldn't replicate it from the example app.

**Comment by mrousavy** [comment]
Ahh good catch! Can you send me a PR with that line inserted both on iOS and on Android side? Thanks!

**Comment by siderakis** [comment]
https://github.com/mrousavy/react-native-mmkv/pull/470/files

**Comment by mrousavy** [comment]
Oh yea I fixed this in VisionCamera, will fix it here as well!

**Comment by mrousavy** [comment]
Created a PR: https://github.com/mrousavy/react-native-mmkv/pull/519 this should fix it :)
