### ISSUE TITLE
Faulty tests

### ISSUE THREAD

**Issue by pke** [mrousavy/react-native-mmkv#474]
I relation to #472 the tests of this library are getting it wrong too, because the mock is not working as the real implementation is.

https://github.com/mrousavy/react-native-mmkv/blob/77982c1a61a5e6d2683e6569ca92e09390b28c48/example/test/MMKV.test.ts#L18

should return an empty string, shouldn't it?

**Comment by mrousavy** [comment]
ah, you're right. Hm.

**Comment by mrousavy** [comment]
I mean I am getting a valid string from the MMKV Core library, so there's not really much I can do about that. https://github.com/mrousavy/react-native-mmkv/blob/77982c1a61a5e6d2683e6569ca92e09390b28c48/ios/MmkvHostObject.mm#L148-L150

You can create an issue at the MMKV core lib

**Comment by pke** [comment]
But if its a number it should not return a string, correct?

**Comment by mrousavy** [comment]
> But if its a number it should not return a string, correct?

Not correct, **MMKV does not store the datatype**, hence you can interpret the stored data (bytes) in any way.

If you write the number `8` in MMKV, it gets stored as the binary form `0x4020000000000000`. The binary form `0x4020000000000000` could be read as a string, but it's not a valid string so it contains only weird characters.

**Comment by mrousavy** [comment]
With this code:

```ts
storage.set('value', 8);
console.log(storage.getString('value'));
console.log(storage.getBoolean('value'));
console.log(storage.getBuffer('value'));
console.log(storage.getNumber('value'));
```

The following gets printed:

```
 LOG  
 LOG  false
 LOG  []
 LOG  8
```

And if I inspect the native string in Xcode, it contains `0x00000001b9787800` in hex/binary. If you decode that using an online decoder it says `?���¹xx�`. Those apparently are invalid chars for a JS string and that's why it looks empty.

**Comment by mrousavy** [comment]
Another example:

```ts
storage.set('value', 'hello');
console.log(storage.getString('value'));
console.log(storage.getBoolean('value'));
console.log(storage.getBuffer('value'));
console.log(storage.getNumber('value'));
```

prints

```
 LOG  hello
 LOG  true
 LOG  [104, 101, 108, 108, 111]
 LOG  undefined
```

Again, MMKV does not know the storage type. You can interpret every value however you like, so even if it's stored as a string, it can be read as a boolean, number, or arraybuffer and you get the data that way. It might not make sense anymore since it was a string, but anyways.

**Comment by mrousavy** [comment]
It's like doing `reinterpret_cast` on `uint8_t*`.

**Comment by pke** [comment]
I tried to understand the mmkv source code

https://github.com/Tencent/MMKV/blob/f58cf4b7e56765deda27bc30e9537cbdb3075c25/Core/MMKV_OSX.cpp#L179

and you seem right, that when one tries to read a string and it can't be decoded then its straight cast to an byte array.
