### ISSUE TITLE
What is the algorithm or specification for the included encryption?

### ISSUE THREAD

**Issue by Slapbox** [mrousavy/react-native-mmkv#476]

**Comment by mrousavy** [comment]
[AES Crypt](https://github.com/Tencent/MMKV/blob/dev/Core/aes/AESCrypt.cpp)

**Comment by Slapbox** [comment]
Thanks for your reply @mrousavy. 

Sorry, I didn't realize at first that React-Native-MMKV wraps MMKV - but I wonder if you know the key length used?

**Comment by mrousavy** [comment]
well I think that's the length of the key you provide to `encryptionKey`
