### ISSUE TITLE
In Build gradle we should move the Jcenter() to mavencentral(), Since Jcenter is completely shut down.

### ISSUE THREAD

**Issue by NaveenKumar19** [mrousavy/react-native-mmkv#477]
https://github.com/mrousavy/react-native-mmkv/blob/843389facbca31ad1e0cd7de84d1bad858ffd328/android/build.gradle#L26

**Comment by PrajTS** [comment]
This seems to be resolved. This issues can be closed @mrousavy

**Comment by mrousavy** [comment]
Awesome! Thx
