### ISSUE TITLE
Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by val089** [mrousavy/react-native-mmkv#481]
I have got error like belowe during starting applicaton. 

ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app.

**Comment by mrousavy** [comment]
Apparently the native module cannot be found - either you didn't install pods or something went wrong while autolinking. Or you're using Expo Go. Either way; this issue does not contain enough details for me to debug.

**Comment by timoteialbu** [comment]
@mrousavy I am having the same issue but on Android. I did install the pods. The weird thing was that it worked at first until I installed the flipper plugin. After that, it broke and even though I removed it's not working anymore.
I am on RN 0.69.2.
What kind of other details are you looking for that I can provide?

**Comment by timoteialbu** [comment]
I wanna circle back and say I found the problem in my setup. We are in a brownfield app and the way we initialize our app is weird, meaning we need to manually link our Android libraries. This is not an issue with this library. In case anyone finds this helpful, I added this to manually link it:

```
import com.reactnativemmkv.MmkvPackage;

// in the onCreate method
.addPackage(new MmkvPackage())
```

**Comment by nourr23** [comment]
> import com.reactnativemmkv.MmkvPackage;

where did you add it please

**Comment by douglasfelc** [comment]
This is 

> > import com.reactnativemmkv.MmkvPackage;
> 
> where did you add it please

On android\app\src\main\java\com\...\app\MainApplication.kt or .java

**Comment by divyansh0908nl** [comment]
what about for ios?

**Comment by divyansh0908nl** [comment]
> This is
> 
> > > import com.reactnativemmkv.MmkvPackage;
> > 
> > 
> > where did you add it please
> 
> On android\app\src\main\java\com...\app\MainApplication.kt or .java

How can we link this in ios?

**Comment by douglasfelc** [comment]
> How can we link this in ios?

Try this:
Navigate to the ios folder in your project and install the CocoaPods dependencies:
> cd ios
> pod install

**Update AppDelegate.m or AppDelegate.swift**
Depending on your project, open AppDelegate.m (Objective-C) or AppDelegate.swift (Swift) in the ios/YourAppName/ directory.

For Objective-C (AppDelegate.m):
Add the following import at the top of the file:
`#import <MMKV/MMKV.h>`

Inside the didFinishLaunchingWithOptions method, initialize MMKV:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [MMKV initializeMMKV:nil];
  ...
  return YES;
}
```

For Swift (AppDelegate.swift):
import MMKV

Inside the application method, initialize MMKV:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    MMKV.initialize()
    ...
    return true
}
```

Rebuild the iOS App
`yarn ios`
