### ISSUE TITLE
Get all mmkv instances

### ISSUE THREAD

**Issue by omidshafai** [mrousavy/react-native-mmkv#486]
I want to get all the mmkv instances to delete all of them when user logout.
How do I do this?

**Comment by mrousavy** [comment]
Hi!

This is currently not possible because I assume that you keep track of your MMKV instances.

I can however add that functionality (maybe a `MMKV.getAllInstances()` function?)

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=iL-o8IJhwSQ&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=16

**Comment by mrousavy** [comment]
I asked in Tencent/MMKV, but looks like they don't support that feature (yet): https://github.com/Tencent/MMKV/discussions/992

**Comment by omidshafai** [comment]
> I asked in Tencent/MMKV, but looks like they don't support that feature (yet): [Tencent/MMKV#992](https://github.com/Tencent/MMKV/discussions/992)

Thank you.
It can be useful for us whenever it is done.

**Comment by mrousavy** [comment]
Hey - don't think they want to implement that. :/
