### ISSUE TITLE
dlopen: failed to load __emutls_get_address

### ISSUE THREAD

**Issue by volgar1x** [mrousavy/react-native-mmkv#487]
It seems it requires  `__emutls_get_address` function to be defined, and although it's usually provided by `libc++_shared.so`, it does not seem to be the case when using NDK 24 on an Apple M1 CPU.

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 88.38 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.3.2 => 9.3.2
    react: ~18.1.0 => 18.1.0
    react-native: ~0.70.4 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```
$ echo $ANDROID_HOME
/Users/volgar1x/Library/Android/sdk
$ ls $ANDROID_HOME/ndk
24.0.8215888
```

It seems to be building just fine on a Fedora desktop with the same dependencies but with an older NDK (`21.4.7075529`).

See https://github.com/facebook/react-native/issues/35324

**Comment by yevhenjl** [comment]
The same error appears when start _npx react-native run-android_
`Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~PMd_zbLaiyY1lMt4NoBibQ==/com.aaaaa-wf1aOnwi3H5wPreU1Bmg0w==/base.apk!/lib/x86_64/libreactnativemmkv.so"..., js engine: hermes`

`
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.40 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/yevhen/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.1
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 24.0.8215888
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by mrousavy** [comment]
Hmm weird, maybe you need to reinstall Xcode?

Maybe try

```
xcode-select --install
```

Or

```
brew link --overwrite gcc
```

**Comment by yevhenjl** [comment]
> Hmm weird, maybe you need to reinstall Xcode?
> 
> Maybe try
> 
> ```
> xcode-select --install
> ```
> 
> Or
> 
> ```
> brew link --overwrite gcc
> ```


No success :(

I have attached my config files:

[package.json.txt](https://github.com/mrousavy/react-native-mmkv/files/10243425/package.json.txt)
[android_build.gradle.txt](https://github.com/mrousavy/react-native-mmkv/files/10243426/android_build.gradle.txt)
[android_app_build.gradle.txt](https://github.com/mrousavy/react-native-mmkv/files/10243427/android_app_build.gradle.txt)

**Comment by yevhenjl** [comment]
Finally I have succeeded:
It works only with ndkVersion = "21.4.7075529"
Versions 23.1.7779620, 24.0.8215888 and 25.1.8937393 doesn't work

**Comment by meypod** [comment]
I can also confirm that ndk "23.1.7779620" breaks mmkv, and switching back to "21.4.7075529" fixed this issue
the weird thing is that it builds and works properly locally (I'm using windows), but not on github workflow using `cimg/android:2022.08.1-ndk` container image

**Comment by mohitarora777** [comment]
Crashing for me too, on react native version 0.66.3, react-native-mmkv version 2.5.1.
<img width="865" alt="Screenshot 2023-01-16 at 3 17 29 AM" src="https://user-images.githubusercontent.com/107910744/212568974-4be012c3-ac2e-4ff0-852c-b6280f3a024b.png">

**Comment by mohitarora777** [comment]
> Hmm weird, maybe you need to reinstall Xcode?
> 
> Maybe try
> 
> ```
> xcode-select --install
> ```
> 
> Or
> 
> ```
> brew link --overwrite gcc
> ```

this happens on Android not ios

**Comment by mohitarora777** [comment]
<img width="601" alt="Screenshot 2023-02-03 at 1 10 49 PM" src="https://user-images.githubusercontent.com/107910744/216540978-8d40c164-6e24-427a-a1f2-d3a40f4cd624.png">

 @mrousavy Can u pls help us here, we are facing this issue on android 12

**Comment by mrousavy** [comment]
> @mrousavy Can u pls help us here

Sure, send us an email at hello@margelo.io, we do consulting and short term bugfixing from time to time :)

**Comment by mrousavy** [comment]
> switching back to "21.4.7075529" fixed this issue

Yeah, I mean there's nothing I can really do there - seems like a breaking change or bug in the NDK.

**Comment by andresesfm** [comment]
In our case this error was caused by upgrading the AGP: com.android.tools.build:gradle:7.4.0. reverting it to 7.3.0 fixed the issue

**Comment by hssrrw** [comment]
Hi everyone. In my case it is not possible to downgrade NDK to a version lower than 24.0.8215888, since the proper Apple m1/m2 support started only from the version 24, and my laptop is on m2. Therefore the error doesn't allow to run an Android build:
```
Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed:
cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~_6u2JqaGlfD1VFw==
/com.<redacted>DB3g==/lib/arm64/libreactnativemmkv.so"..., js engine: hermes
```

**Comment by lmcjt37** [comment]
Running RN 0.70.6. I'm now targeting/compiling to API 33 and started seeing this issue.

I fixed it by... 

downgrading AGP to 7.3.1 -> `classpath("com.android.tools.build:gradle:7.3.1")`
changing NDK to `23.1.7779620` which is the side-by-side version

Also, referring to the RN upgrade helper helps identify versioning as latest RN 71 targets the above also.

**Comment by rish033** [comment]
@hssrrw were you able to solve it?

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Comment by miteshdb** [comment]
Thanks @yevhenjl 
works for me too with ndkVersion = "21.4.7075529"

**Comment by PhillipFraThailand** [comment]
@yevhenjl solution worked for me, thanks!

**Comment by MdAfzaalkhan** [comment]
@meypod are you able to solve this issue on github workflow?? facing the same issue with workflow i downgraded the ndk version to 21.x.xx but still same error, locally it is working fine but in github workflow throwing this **dlopen: failed to load __emutls_get_address**

**Comment by arahman69** [comment]
@hssrrw did you find a fix for this issue?

**Comment by arahman69** [comment]
This issue has been around for a while, but it took me a significant amount of time to fix in my company's app, which is running React Native 0.70.5. Upgrading wasn't an option, so I had to find a workaround.  

If anyone encounters the same problem in the future, the fix is simple: update the library's CMake file by replacing this:  
node_modules/react-native-mmkv/android/CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.9.0)

set(PACKAGE_NAME "react-native-mmkv")
set(BUILD_DIR ${CMAKE_SOURCE_DIR}/build)
```

with this:  

```cmake
cmake_minimum_required(VERSION 3.18.1)
project(MMKV)

set(PACKAGE_NAME "react-native-mmkv")
set(BUILD_DIR ${CMAKE_SOURCE_DIR}/build)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -static-libstdc++")
```

This ensures proper linking and resolves the `__emutls_get_address` error. Hope this helps anyone facing the same issue! 🚀
