### ISSUE TITLE
Access the MMKV native module on the native side

### ISSUE THREAD

**Issue by nitish24p** [mrousavy/react-native-mmkv#490]
### WHAT
This issue may not be linked directly to the library, but i was wondering if there is a way to create / access an mmkv instance on the native / java / objective C . I have a case where prior to launch time i make an api call and then want to cache this data in the mmkv instance and make it accessible on the RN side.. Is this possible.  I thought of one way is to probably create a genInstance method at the JNI layer which can be exposed as a public native Method. Im not sure how this will work though

**Comment by mrousavy** [comment]
Hi!
You can try to include the MMKV instances, but there's no guarantee that it's being synced because it's in single-process mode.

**Comment by nitish24p** [comment]
Is there any other way i can work with getting the MMKV instance on the native side then?

**Comment by mrousavy** [comment]
Yes, by just using the native Tencent/MMKV library.

**Comment by Jokerwolf** [comment]
Hey @mrousavy, sorry if my question sounds odd (not an experienced native developer): you mean we need to actually include _com.tencent.mmkv.MMKV_ or is there a way to reuse the c++ code you have to create the HostObject in your library?

**Comment by mrousavy** [comment]
No worries - yea you need to use the com.blablabla import and use the native MMKV stuff.
You can use my C++ code, but that's pretty complicated

**Comment by nitish24p** [comment]
@mrousavy Sure will try that.. I had done benchmarking for the native MMKV library https://github.com/Tencent/MMKV/discussions/986

Found perf bottle necks in the serialisation of Json objects in the JNI layer. Since youre library doesnt  use a JNI layer for set string and directly uses the MMKV lib header / Cxx files its actually faster. But sure will try this. Thanks

**Comment by nitish24p** [comment]
@mrousavy Do you have a twitter / email that i can reach out to you for some more questions, or is this issue fine?

**Comment by mrousavy** [comment]
This issue is fine, ask ahead - but keep in mind that accessing MMKV on the native side is not something I want to actively support - it is better to just do it on the JS side.
