### ISSUE TITLE
Add iCloud backup

### ISSUE THREAD

**Issue by retyui** [mrousavy/react-native-mmkv#493]
Async Storage stores data in `Application Support` directory, which is backed up by `iCloud` by default. (Read: https://react-native-async-storage.github.io/async-storage/docs/advanced/backup/)

Can be this behavior add to mmkv too?

**Comment by mrousavy** [comment]
Hm I think MMKV is included in an iCloud backup, but not a normal cross-device iCloud sync.

See https://github.com/Tencent/MMKV/issues/107
