### ISSUE TITLE
Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by jsonchou** [mrousavy/react-native-mmkv#495]
Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you ran `pod install` in the ios/ directory.
* Make sure you ran `expo prebuild`.
* Make sure you rebuilt the app.

### package.json
"react-native": "^0.69.7"
"react-native-mmkv": "^2.5.1",

### pod install 
Installing MMKV (1.2.14)
Installing MMKVCore (1.2.14)

### npx react-native config
``` bash
 "react-native-mmkv": {
      "root": "/Users/ddd/projects/xxx/node_modules/react-native-mmkv",
      "name": "react-native-mmkv",
      "platforms": {
        "ios": {
          "podspecPath": "/Users/ddd/projects/xxx/node_modules/react-native-mmkv/react-native-mmkv.podspec",
          "configurations": [],
          "scriptPhases": []
        },
        "android": {
          "sourceDir": "/Users/ddd/projects/xxx/node_modules/react-native-mmkv/android",
          "packageImportPath": "import com.reactnativemmkv.MmkvPackage;",
          "packageInstance": "new MmkvPackage()",
          "buildTypes": []
        }
      }
    },
```

What is correct debug feedback from the debug tips？

**Comment by jsonchou** [comment]
Using Expo modules
Auto-linking React Native modules for target `xxx`: BVLinearGradient, RNCAsyncStorage, react-native-mmkv, and ...

[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json

**Comment by mrousavy** [comment]
Huh, did you attach a debugger? Does it work if you build it in Release mode?
