### ISSUE TITLE
Build Error on React Native 0.71.0

### ISSUE THREAD

**Issue by hamdij0maa** [mrousavy/react-native-mmkv#497]
**/node_modules/react-native-mmkv/android/build.gradle' line: 173

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv'.
**/node_modules/react-native/android' to contain exactly one file, however, it contains no files.

**Comment by tobua** [comment]
Pull request with the necessary changes seems to be ready already but not yet merged: #480 (0.71 has just been released a couple of hours ago).

**Comment by retyui** [comment]
you can use an early version from git
```tsx
yarn add mrousavy/react-native-mmkv#feat/migrate-rn-71
```

> **Require** to enable `newArchEnabled=true` in `android/gradle.properties` file

**Comment by hamdij0maa** [comment]
👎🏼for Fabric yes, but our need is using RN 0.71.X without Fabric

**Comment by hamdij0maa** [comment]
> > 👎🏼for Fabric yes, but our need is using RN 0.71.X without Fabric
> 
> Why you can't use the Fabric?

because am using other libs that do not support fabric yet

**Comment by chrisbianca** [comment]
I would also echo the need to continue support for the old architecture. There are a number of react native libraries that can't be updated to the new architecture whilst it does not support static frameworks, e.g. react-native-firebase

**Comment by hamdij0maa** [comment]
@mrousavy please do you confirm that the upcoming release will work without enabling Fabric ? 
or it will only work with Fabric enabled ?

**Comment by tobua** [comment]
@hamdij0maa according to this note in the pull request it will only work on 0.71 with fabric enabled:

> ⚠️ Note: This is a breaking change. react-native-mmkv now only builds on RN 0.71 and above using the new architecture. For the sake of simplicity, it is not backwards compatible.

Meaning if you cannot enable fabric you'll have to stay on 0.70.6. Fabric is now the default architecture for RN, so this breaking change makes sense.

**Comment by hamdij0maa** [comment]
It's not the default :v Fabric renderer is not enabled by default, and most of libs example @FlashList by shopify does not support fabric renderer yet :v

**Comment by tobua** [comment]
@hamdij0maa You got a point, didn't know it wasn't already enabled by default.

**Comment by hamdij0maa** [comment]
> @hamdij0maa You got a point, didn't know it wasn't already enabled by default.

No prob brother, 
we just trying to get it working for all xD 
hopefully @mrousavy publish the needed changes soon 🤣

**Comment by Titozzz** [comment]
I think y'all missread `This is a breaking change. react-native-mmkv now only builds on RN 0.71 and above using the new architecture. For the sake of simplicity, it is not backwards compatible.`

If you are on new arch, you'll need 0.71, otherwise you should still be fine. It's just saying that new arch won't work on 0.68, 0.69 and 0.70.

**Comment by hamdij0maa** [comment]
Yes, just confirming 😂

**Comment by leonardoballand** [comment]
Same issue here

RN 0.71 without new architecture :(

**Comment by ugurdalkiran** [comment]
When is the new version released?

**Comment by meftunca** [comment]
Please update during the day.

**Comment by hamdij0maa** [comment]
@mrousavy Please any news regarding the fix ?

**Comment by ugurdalkiran** [comment]
@mrousavy I need this library in current version (0.71.0). Please I am waiting for an update.

**Comment by mrousavy** [comment]
These tags are insanely annoying, stop spamming or I ban you from using RN MMKV.

I am running a company and I am currently busy with a few company related things, I will continue to work on an open-source project I made **for free** (and none of you guys here are paying me for that) when I have some free time.

I expect this to happen later today.

**Comment by hamdij0maa** [comment]
thank you for the update, 
am getting this error 
Task :app:mergeLibDexDebug FAILED

> Task :react-native-mmkv:buildCMakeDebug[x86]
C/C++: ninja: Entering directory `/Users/*****/Desktop/apps/*****/node_modules/react-native-mmkv/android/.cxx/Debug/71605c37/x86'
@Titozzz do you have an idea how to make it working please?

**Comment by tobua** [comment]
Working fine for me, thanks!

**Comment by ugurdalkiran** [comment]
Thank you very much for the update.

But I am getting an error.

Something is conflicting with the react-native-svg library I understand. :/

![image](https://user-images.githubusercontent.com/27302986/212700132-96f3adac-d7f1-4772-a4a7-77771ef31fc8.png)

` Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: C:\a071a\node_modules\react-native-mmkv\android\build\.transforms\8397d2fe439e7a0cd7a94dd5881d0a19\transformed\classes\classes.dex, C:\a071a\node_modules\react-native-svg\android\build\.transforms\e4553b6d9bb03a5dcd7595790fe41e48\transformed\classes\classes.dex`

**Comment by hamdij0maa** [comment]
> Thank you very much for the update.
> 
> But I am getting an error.
> 
> Something is conflicting with the react-native-svg library I understand. :/
...


same error

**Comment by mikalaiulasevich** [comment]
same with Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: /node_modules/react-native-gesture-handler/android/build/.transforms/9016f10b3bbc73680278818232d909ac/transformed/debug/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex, /node_modules/react-native-mmkv/android/build/.transforms/05fe2efb67e79eed93a93868192077d9/transformed/debug/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex

**Comment by mrousavy** [comment]
Did you nuke your gradle cache? https://stackoverflow.com/a/30450020/5281431

**Comment by abgaryanharutyun** [comment]
Same here,
I cleared all caches and am using the latest version of "react-native-mmkv." After upgrading, the error changed. I tested building my app without "react-native-mmkv" and it works well, but when I add it back, I encounter the same issue.

**Comment by inssein** [comment]
I get the same error as @mikalaiulasevich:
```
Type com.facebook.react.viewmanagers.RNGestureHandlerButtonManagerDelegate is defined multiple times: /Users/inssein/projects/dittoed/app/node_modules/react-native-gesture-handler/android/build/.transforms/d613df52358496bff3ffec7f5dc6fdeb/transformed/debug/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex, /Users/inssein/projects/dittoed/app/node_modules/react-native-mmkv/android/build/.transforms/2eb4a9494d7d6ffad6931f884f14eca1/transformed/debug/com/facebook/react/viewmanagers/RNGestureHandlerButtonManagerDelegate.dex
```

**Comment by inssein** [comment]
@mrousavy looks like the issue was with the `build.gradle`. I'm pretty new to this, but I just happened to look at the build.gradle of other libraries and caught the fact that other libraries were only doing `apply plugin: 'com.facebook.react'` if  
`isNewArchitectureEnabled`, like so:

```
if (isNewArchitectureEnabled()) {
    apply plugin: 'com.facebook.react'
}
```

I can open a PR if that's correct.

**Comment by ugurdalkiran** [comment]
Very interesting.

Although **newArchEnabled=false** in android/gradle.properties it was always going into this if. 🤔

apply plugin: 'com.facebook.react' I completely deleted this and it works, amazing. Thanks @inssein 🥳

**Comment by leonardoballand** [comment]
Works like a charm! 💟

**Comment by mrousavy** [comment]
Thanks for your PR @inssein - it's weird that I didn't have this error while testing - which other libraries also do the same approach?

**Comment by inssein** [comment]
Thanks for dealing with that so quickly @mrousavy. As for your question, I looked at https://github.com/software-mansion/react-native-gesture-handler/blob/main/android/build.gradle#L60 and https://github.com/software-mansion/react-native-svg/blob/main/android/build.gradle#L27

**Comment by devoren** [comment]
@inssein +++ same issue with RNGH

**Comment by 98rahul** [comment]
FAILURE: Build failed with an exception.
A problem occurred configuring project ':react-native-mmkv'.
> org.gradle.api.InvalidUserDataException: NDK is not installed 

[CXX1101] NDK at C:\Users\Your\AppData\Local\Android\Sdk\ndk\23.1.7779620 did not have a source.properties file
### build failed as ndk already installed 

RN-0.71.1 
"react-native-mmkv": "^2.6.1",
