### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by ameerarx** [mrousavy/react-native-mmkv#502]
**Description**

<img width="786" alt="Снимок экрана 2023-01-21 в 00 59 28" src="https://user-images.githubusercontent.com/55210011/213794350-b0acd895-71cb-4e6d-8a3d-bfe2140154c5.png">

**Package**
"react-native-mmkv": "2.5.0",
"react-native": "0.70.6",

I run on Mac M1 Max, Android Studio 11.0.15+0-b2043.56-8887301 aarch64, , built on January 11, 2023, cmake 3.18.1

**Comment by devoren** [comment]
Build with fabric enabled? Then use RN v0.71.1 and MMKV v2.6.1

**Comment by mrousavy** [comment]
Please post full logs. I can't do anything with a screenshot just saying that the build failed.

**Comment by mikebouwmans** [comment]
@ameerarx Have you been able to fix this?
