### ISSUE TITLE
infinite configuring

### ISSUE THREAD

**Issue by Szabolcs11** [mrousavy/react-native-mmkv#503]
I'm using "react-native": "0.71.1", and "react-native-mmkv": "^2.6.1"

When I try to run npm run android there will be an infinite configuring

![image](https://user-images.githubusercontent.com/67874109/213896004-1f493a01-ddaf-42f2-9456-cbaa3da8305e.png)

**Comment by mrousavy** [comment]
It's installing the NDK, this might take a while..
