### ISSUE TITLE
Enable multi-process mode via configuration

### ISSUE THREAD

**Issue by theLaurensS** [mrousavy/react-native-mmkv#505]
Hi,

**If I understand correctly:**

1. Multi-process mode is disabled right now on iOS and Android (hardcoded).
2. Multi-process mode is needed if more than one process accesses the same storage and you need to be sure each process reads the most recent value at all times.

**Our use case:**
Our app does things in both the foreground and background process that requires a shared state in the MMKV storage. It seems that this is not working correctly at the moment: if one process updates the state, the other one does not fetch the new value(s) afterwards.

**Short term:**
Is there any way to already enable multi-process mode right now?

**Longer term:**
It seems like a good idea to add it to MMKVConfiguration?
Also proposed [here](https://github.com/mrousavy/react-native-mmkv/issues/445#issuecomment-1227324155).

Thank you for your time and amazing library.

**Comment by mrousavy** [comment]
Hey! Correct. I need to take another look at #402 (cc @RZulfikri) - it looks good, but we need to improve the docs on that.

**Comment by theLaurensS** [comment]
Thanks for your fast reply, @mrousavy !
Any time estimate for this? Then we can act accordingly for our problem.

Thanks!
