### ISSUE TITLE
Detox build fails RN 0.71.2

### ISSUE THREAD

**Issue by jahglow** [mrousavy/react-native-mmkv#510]
Added detox to the app, followed their config, but when running `./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release` or `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`, the build fails (normal build not for detox passes no prob):
```log
> Task :react-native-mmkv:mergeDebugAndroidTestNativeLibs FAILED
> Task :react-native-random-values-jsi-helper:mergeDebugAndroidTestNativeLibs FAILED

-----------
* What went wrong:
Execution failed for task ':react-native-mmkv:mergeDebugAndroidTestNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - app/node_modules/react-native-mmkv/android/build/intermediates/library_jni/debug/jni/arm64-v8a/libc++_shared.so
      - /Users/username/.gradle/caches/transforms-3/4e096e25fdaa838536961cc2c37ab060/transformed/jetified-react-android-0.71.2-debug/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```
`./gradlew clean` and node_modules ceanup doesn't help, using latest v2.7.0

and the same for `react-native-random-values-jsi-helper`. @mrousavy  How can I get rid of duplicating?

**Comment by T-Damer** [comment]
Same stuff

**Comment by jahglow** [comment]
Well, adding it to `android.packagingOptions.excludes` array like so `"**/**/libc++_shared.so"` (maybe the first glob is excessive) in `node_modules/react-native-mmkv/android/build.gradle` does the thing making it build. Whether it works or not I need some detox errors and I have no idea how it influences the production build of the app, it's for me to see yet. Meanwhile I saw it was present there [some time ago](https://github.com/mrousavy/react-native-mmkv/pull/194/files) and @mrousavy removed it, maybe he can shed some light on why.

**Comment by Alaa-Ben** [comment]
For now, I've just added 
```
android {
  // ...
  packagingOptions {
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
  }
}
```
to this lib's build.gradle and used patch-package to make it consistent through npm installs.
It's a workaround but it works.

**Comment by T-Damer** [comment]
> For now, I've just added
> 
> ```
> android {
>   // ...
>   packagingOptions {
>     pickFirst 'lib/x86/libc++_shared.so'
>     pickFirst 'lib/x86_64/libc++_shared.so'
>     pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>     pickFirst 'lib/arm64-v8a/libc++_shared.so'
>   }
> }
> ```
> 
> to this lib's build.gradle and used patch-package to make it consistent through npm installs. It's a workaround but it works.

Yeah, but I really need some stuff from `0.71`, btw on MacOS machines there's no such error, only on Linux/Windows

**Comment by Alaa-Ben** [comment]
What i posted here works for 0.71 (for me at least).
