### ISSUE TITLE
Is there something wrong trying to use MMKV as Local DB?

### ISSUE THREAD

**Issue by Martinocom** [mrousavy/react-native-mmkv#513]
I was searching for a **Local Database solution**, and I really found nothing that is offline-based, no online dependencies (neither in future), simple to configure and currently maintained.

I repeat to be clear: **Local Database solution, no online dependencies**.
_Firebase is online, Realm starts as offline, but if you will ever want to go online, you're bounded to them._
For others, I tried WatermelonDB that doesn't work well with current ReactNative version. Other projects (Pouch or others) are not mantained from years and I don't trust them (some of them are still referencing to link project or doesn't have hooks).

I discovered MMKV and already developed a working prototype of my App. I started to wonder about limitations of this library used as a Local DB. My use-cases are pretty simple, but I'm worried about letting them grow:

> User capable of inputing some:
>  - `Movements` that has an amount, date, detail and reference to category_id. 
>  - `Category` has a name and color. 
>  
> User can add (or remove) movements.
> User can add (or remove or change) categories.
> Every movement is unique and participates to a total budget.
> Budget is calculated as the sum of movements (derived data, not saved).

Questions are:

1. Is there any "file size" limit? Like the 6MB of Android Key-Value Shared Preferences? Or more related to 2GB of FileSystem configuration? Obviously, if the limit is 2GB, I'm pretty sure not to grow so easly there.
2. Is there any slow-downs when reading hundreads (or thousands or milions) of objects?

I was thinking about optimizing data retrival saving movements of, for example, this month in a storage, then the "Historical Movements" in another one, slower to retrieve. But what "slower" means and when it will happen? At 100 Movements? 1.000? 1.000.000? How this library can handle this type of slow-downs? 
_Surely, it depends from your phone and your flash memory speed, but I want to think about "average case"._

I know that maybe I choose _a wrong library for a correct use-case_, but the only alternative is SQLite that has no active develop in ReactNative projects as npm package. And my requirement is that my app needs to be fast (?) and local with no registration nor "artifical" dependency from a Firebase or Realm DB structure, capable of easy export/import of data.

**Comment by aLemonFox** [comment]
Yes, do NOT use mmkv as a database. It won't work as it's not designed to be used as one. Others (including me) have encountered this issue. Read more here: https://github.com/mrousavy/react-native-mmkv/issues/440

**Comment by mrousavy** [comment]
It's better to use it as a key value storage, yes. For databases there's better solutions, but it depends on the size of your data.

**Comment by Abhishek21k** [comment]
if the data is small, then it can be used a temprory soln?

**Comment by Martinocom** [comment]
@Abhishek21k 
It's not about the size of your data, it's about potentially breaking it in the future. Think about a pseudo-shopping app.

If your data is about saving preferences that will update only a limited set of fields (name, surname, language preference, etc...) it's pointless to use a DB and you need to use MMKV (or others).

If your data is about managing a bunch of orders where you need to store items, positions and prices... and then you need to query them or manipulate them... Hell no, don't use MMKV but a real DB.

BUT, if you need to store "temporarily" some data for your offline Shopping Cart... Why not? It would be like a 'session cookie' in your browser. Save the data in MMKV and when the user will reopen the app, the shopping cart will be loaded in memory. 

✅  The content of **ONE SINGLE** Shopping Cart is a limited, well defined, (serializable?), data.
❌  Your whole magazine and its order history is not.

I ended up using MMKV for preferences and some user data, but RealmDB for offline data storage.

**Comment by fegig** [comment]
@Martinocom
Your explanation is 100% fact. MMKV works like a Local or Session Storage. and i mostly recommend it for only on device data cache and sizable key value storage. outside that use a real dbase for your own sanity.
