### ISSUE TITLE
useMMKVObject (and other hooks) without fastWrites option causes intermediate state change because of delete before write

### ISSUE THREAD

**Issue by fahad86** [mrousavy/react-native-mmkv#514]
```
const [myObject, setMyObject] = useMMKVObject('object.key')

useEffect(() => {
  console.log(myObject);
}, [myObject]);

setMyObject(object);
```

Expected:
1) [Object]

2) [ObjectUpdated]

Actual:

1) [Object]

2) undefined

3) [ObjectUpdated]

With fastWrites options, it works as expected

**Comment by mrousavy** [comment]
Good point. I think we should remove the fastWrites prop anyways as that doesn't really make a difference.

**Comment by mrousavy** [comment]
Reverted in the latest release.
