### ISSUE TITLE
App crashes at start up in release build ( package version 2.5.1)

### ISSUE THREAD

**Issue by saumyabhatnagar2000** [mrousavy/react-native-mmkv#515]
Getting this error when I run app in release build

- Package Version : 2.5.1
- React Native version : 0.70.6
- Hermes: enabled
- Codepush : enabled

`26562 26562 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
26562 26562 F DEBUG   :     x0  0000000000000000  x1  000000000000678b  x2  0000000000000006  x3  00000076588ae4f0
26562 26562 F DEBUG   :     x4  00000000ebad808a  x5  00000000ebad808a  x6  00000000ebad808a  x7  00000000ebad808b
26562 26562 F DEBUG   :     x8  00000000000000f0  x9  85bf48936a575991  x10 0000000000000000  x11 ffffff80fffffbdf
26562 26562 F DEBUG   :     x12 0000000000000001  x13 0000000000000045  x14 000000768f83ffb1  x15 000000768f8453f8
26562 26562 F DEBUG   :     x16 00000079b3801050  x17 00000079b37ddeb0  x18 0000007656d2e000  x19 000000000000675d
26562 26562 F DEBUG   :     x20 000000000000678b  x21 00000000ffffffff  x22 fffffffffffffffd  x23 00000076588ae750
026562 26562 F DEBUG   :     x24 0000000000000002  x25 b4000077c658c830  x26 0000000000000001  x27 b4000077565f3be0
26562 26562 F DEBUG   :     x28 000000768d31f8c8  x29 00000076588ae570
26562 26562 F DEBUG   :     lr  00000079b3790ba0  sp  00000076588ae4d0  pc  00000079b3790bcc  pst 0000000000001000`

**Comment by mrousavy** [comment]
That's not an error, nor a stack trace. Either symbolicate it so I have line numbers, give me a reproduceable example, or anything to work with, but what do you even expect me to do in this case?
