### ISSUE TITLE
[WEB] Sourcemap warning

### ISSUE THREAD

**Issue by victorwpbastos** [mrousavy/react-native-mmkv#516]
- Package version: 2.7.0
- React Native version: 0.71.3
- Expo version: 48

When running `npx expo web` the app starts and works as expected, but the terminal is full of these warning: 

![image](https://user-images.githubusercontent.com/1017515/221960846-906f5650-2808-4238-b43c-5c7dc08965f2.png)

Only happens when using on the web. iOS and Android doesn't show any warning.

**Comment by mrousavy** [comment]
sorry, no idea why that is happening. If you can debug this and figure out what's wrong, I'd appreciate a PR!

**Comment by RichardLindhout** [comment]
It can be fixed by upgrading bob, I just did all my own libraries

**Comment by RichardLindhout** [comment]
PR: https://github.com/mrousavy/react-native-mmkv/pull/529

**Comment by RichardLindhout** [comment]
https://github.com/expo/expo/issues/21276

**Comment by 0x10Ayoub** [comment]
Hi @victorwpbastos  I had the same issues solve it  by upgrading react-native-build-bob as @RichardLindhout mentioned plus manually copying of https://github.com/mrousavy/react-native-mmkv/tree/master/src to  node_modules/...mmkv/src

**Comment by RichardLindhout** [comment]
PR is merged! @mrousavy could you do a release?

**Comment by mrousavy** [comment]
Done! 2.8.0 is out, which also includes support for `id` on web! 🎉

**Comment by RichardLindhout** [comment]
@mrousavy did you run yarn install before release? The warning is still there

**Comment by 0x10Ayoub** [comment]
hi @RichardLindhout from my understanding the error is related to the fact that the src folder doesn't exist 
as you can see in the images below 
![Screenshot 2023-04-13 at 03 30 09](https://user-images.githubusercontent.com/25417439/231642346-b882700f-8e08-4b86-ab5d-91fd3c01da98.png)
![Screenshot 2023-04-13 at 03 37 03](https://user-images.githubusercontent.com/25417439/231642680-783f9e12-b562-4eff-99f4-fd4eaf2ecb81.png)

**Comment by RichardLindhout** [comment]
@0x10Ayoub Ah that could be it, in my libraries it was the upgrade to bob which was fixing this error but indeed I think the src needs to be there too :)

**Comment by RichardLindhout** [comment]
@mrousavy any chance you could publish the library with the src directory inside npm?

**Comment by RichardLindhout** [comment]
I see you already committed a fix, but it is not released yet :)

**Comment by mrousavy** [comment]
yea

**Comment by PrajTS** [comment]
@mrousavy Hi. I still don't the release published. Will it take time?
