### ISSUE TITLE
Safely migrate from AsyncStorage

### ISSUE THREAD

**Issue by Jalson1982** [mrousavy/react-native-mmkv#52]
Hello.  I really want to replace in my app on all the place AsyncStorage and use MMKV. The problem I have is that I use async storage with redux persist and if I want to change to MMKV I will need to log out users as in redux persist I keep info if the user has a profile, authenticated, etc. Any idea maybe how safely do migration if it is possible?

**Comment by mrousavy** [comment]
Well yeah, you can just use something like this:

```ts
const hasMigrated = MMKV.getBoolean("hasMigratedFromAsyncStorage")
if (!hasMigrated) {

  const keys = await ... // get all keys from AsyncStorage
  const promises = keys.map(async (key) => {
    const value = await ... // get value for key from AsyncStorage
    MMKV.set(key, value)
  });
  await Promise.all(promises)

  MMKV.set("hasMigratedFromAsyncStorage", true)
}
```

**Comment by tothvoj-gl** [comment]
The migration script is working fine in most cases, but when the apollo-cache-persist item in AsyncStorage is more than 2MB in size, than AsyncStorage.multiGet(keys) will throw an exception. The stacktrace is native C++ pointing to MMKV which is weird and prolonged the investigation of the root cause for us. That's why I wanted to mention here. Below you can find our migration script which wont crash the app if this happens:

 ```
const keys = await AsyncStorage.getAllKeys();

  // eslint-disable-next-line no-restricted-syntax
  for (const key of keys) {
    try {
      // eslint-disable-next-line no-await-in-loop
      const value = await AsyncStorage.getItem(key);

      if (value !== null) {
        if (['true', 'false'].includes(value)) {
          MMKV.setBool(key, value === 'true');
        } else {
          MMKV.setString(key, value);
        }

        AsyncStorage.removeItem(key);
      }
    } catch (error) {
      
    }
  }
```

**Comment by tothvoj-gl** [comment]
No, it was this exception: https://stackoverflow.com/questions/57014171/react-native-asyncstorage-row-too-big-to-fit-into-cursorwindow

**Comment by mrousavy** [comment]
The migration script is now added to the Documentation [here](https://github.com/mrousavy/react-native-mmkv/blob/master/docs/MIGRATE_FROM_ASYNC_STORAGE.md), so these comments might be outdated.

**Comment by mattijsf** [comment]
May I ask why this migration script is using `runAfterInteractions`?

**Comment by davydspotnana** [comment]
@mrousavy instead of reading every item you can use multi get:

```diff
-const value = await AsyncStorage.getItem(key);

+const keys = await AsyncStorage.getAllKeys();
+const entries = await AsyncStorage.multiGet(keys);
```

**Comment by DePavlenko** [comment]
@mrousavy 
The described migration didn't work for redux-persist in our case because store was initialized before the first app render, so `getItem` had been called before the whole migration started. So to fix that we just moved the logic inside of `getItem`:

```
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Storage } from 'redux-persist';
import { MMKV } from 'react-native-mmkv';

export const MMKVReduxStorage = new MMKV();

// TODO: Remove `hasMigratedToMMKVStorage` after a while (when everyone has migrated)
export const hasMigratedToMMKVStorage = MMKVReduxStorage.getBoolean(
  'hasMigratedToMMKVStorage',
);

export const reduxStorage: Storage = {
  setItem: (key, value) => {
    MMKVReduxStorage.set(key, value);
    return Promise.resolve(true);
  },
  getItem: async (key) => {
    let value: string | undefined;
    // TODO: Remove the whole if block after a while (when everyone has migrated)
    if (!hasMigratedToMMKVStorage) {
      try {
        const asyncStorageValue = await AsyncStorage.getItem(key);
        if (asyncStorageValue !== null) {
          if (['true', 'false'].includes(asyncStorageValue)) {
            MMKVReduxStorage.set(key, asyncStorageValue === 'true');
          } else {
            MMKVReduxStorage.set(key, asyncStorageValue);
          }
          value = asyncStorageValue;
          AsyncStorage.removeItem(key);
        }
      } catch (error) {
        AsyncStorage.removeItem(key);
      }
      MMKVReduxStorage.set('hasMigratedToMMKVStorage', true);
    }
    if (!value) {
      value = MMKVReduxStorage.getString(key);
    }
    return Promise.resolve(value);
  },
  removeItem: (key) => {
    MMKVReduxStorage.delete(key);
    return Promise.resolve();
  },
};

```

**Comment by zeeshan-shabbir** [comment]
@DePavlenko how can i test if its working or not? i have live app qith async storage , new code complety different codebase with mmkv, migrating to mmkv from asyncstorage , 

I need to find a way to test if your code worked or not can you guide thanks?
