### ISSUE TITLE
Feature request: 'id' support on Web

### ISSUE THREAD

**Issue by jonathanj** [mrousavy/react-native-mmkv#520]
When trying to pass the `id` option to `createMMKV` on the web, it [throws an exception](https://github.com/mrousavy/react-native-mmkv/blob/f3dc49b55c0fa0c1440f4e0aaf308125913b6ff3/src/createMMKV.web.ts#LL10C28-L10C56) about this not being supported.

I realise that there can't really be truly separate stores on web because of how `localStorage` works, but it could be reasonably emulated (and the caveats about that emulation noted in the documentation) by namespacing the keys.

I'd be happy to contribute this feature, but I'd like to check if there was a reason it wasn't implemented initially that I might not have thought about.

**Comment by mrousavy** [comment]
I mean yes it can be supported by using a wildcard character (like `\\`), I just didn't think this was necessary.
I could draft a version up, if you have a PR I'd also appreciate that
