### ISSUE TITLE
Build Problem, no file in android-folder

### ISSUE THREAD

**Issue by Buccaneer69** [mrousavy/react-native-mmkv#525]
Build file 'D:\Projects\ProjectName\node_modules\react-native-mmkv-storage\android\build.gradle' line: 138
* What went wrong:
A problem occurred evaluating project ':react-native-mmkv-storage'.
> Expected directory '...\node_modules\react-native-mmkv-storage\android\..\..\..\node_modules\react-native\android' to contain exactly one file, however, it contains no files.

found this which might be the cause:
Starting from React Native 0.71, we're not shipping the /android folder inside the React Native NPM package
anymore due to sizing constraints on NPM. The Android artifacts are distributed via Maven Central.
You can read more about it in this RFC:
https://github.com/react-native-community/discussions-and-proposals/pull/508

If you're a library author and you're manipulating the React Native .aar files, to extract headers,
extract .so files or do anything with it, you're probably doing something wrong. React Native
0.71 ships with all the necessary logic to let you consume it transparently by just using:

**Comment by mrousavy** [comment]
> :react-native-mmkv-storage

This is not my library.

Install `react-native-mmkv` instead, this works with RN 0.71.
