### ISSUE TITLE
Could not determine the dependencies of task ':react-native-mmkv:compileDebugAidl'.

### ISSUE THREAD

**Issue by quannq-comartek** [mrousavy/react-native-mmkv#526]
I am faced this issues when I am run android emulator. Please help me

RN : 0.70.3
react-native-mmkv: 2.5.1

> Could not determine the dependencies of task ':react-native-mmkv:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mmkv:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Required by:
         project :react-native-mmkv

**Comment by mrousavy** [comment]
Not enough details, you didn't put the full logs here. Try the example/ app and see if you can reproduce it there.

**Comment by ZexinW** [comment]
Happens to us also, RN: 0.69.7

**Comment by YashGolani** [comment]
Also to react-native: 0.68.3

**Comment by christophby** [comment]
Did you find any solution for this @YashGolani @ZexinW @quannq-comartek ?

**Comment by christophby** [comment]
Okay I found my issue. 

🚫 I just changed my package.json from  `"react-native-mmkv": "^2.4.3",` to `"react-native-mmkv": "^2.5.1",`
This installed `2.11.0` internally.

✅ So I removed the `^` from the version -> `"react-native-mmkv": "2.5.1",` and everything looks good now
