### ISSUE TITLE
You shulnd't be mocking the storage in detox environment

### ISSUE THREAD

**Issue by mattiaferrari02** [mrousavy/react-native-mmkv#527]
https://github.com/mrousavy/react-native-mmkv/blob/f3dc49b55c0fa0c1440f4e0aaf308125913b6ff3/src/MMKV.ts#L146-L148

The storage is being mocked when using detox environment because it uses jest.
There's no need to mock the native module when using detox.
Is there a better way to check `isJest()` in your `PlatformChecker.ts` file?

**Comment by mrousavy** [comment]
Hey! Sorry I don't know. If you have a fix for this, send me a PR :)

**Comment by dmidma-quizard** [comment]
@mrousavy, do you have a solution for this?
I want to disable the mocking of MMKV while I am using Detox.
