### ISSUE TITLE
Init error: Exception in HostFunction: InvalidProtocolBuffer truncatedMessage

### ISSUE THREAD

**Issue by Nodonisko** [mrousavy/react-native-mmkv#528]
We started to experience error ` Exception in HostFunction: InvalidProtocolBuffer truncatedMessage` last month during call of `new MMKV({ ... })`. We are using two instances of MMKV and seems that only encrypted one have this issue.

We are on lastest version 2.7.0. Only thing that helps is reinstall of app (which will purge storage). Any idea what could be cause?

![Screenshot 2023-03-13 at 13 50 24](https://user-images.githubusercontent.com/5837757/224706764-c05ae26e-831a-4d97-a0ca-cf0132ac8ec9.png)

**Comment by mrousavy** [comment]
Hmm, honestly no - can you try to create a reproduceable example?

**Comment by Nodonisko** [comment]
@mrousavy Sorry forget to close issue, it seems that we somehow corrupted DB file, not sure how we did that we were messing with encryption and id recently.

**Comment by Nodonisko** [comment]
@jvfalco1 From our side it was mistake because we added encryption to previously unencrypted DB but kept same name. We just reseted storage for everyone and it works for us.

**Comment by michaelessiet** [comment]
I'm running into the same error, however it occurs after the app has undergone an update via Expo updates. It happens about 40% of the time

**Comment by michaelessiet** [comment]
For context I have an environment variable used for the encryption key

**Comment by gunnartorfis** [comment]
> I'm running into the same error, however it occurs after the app has undergone an update via Expo updates. It happens about 40% of the time

This is happening to a few of our users as well. Not 40% but still quite a lot of them. 
It happened as well after an EAS update.

**Comment by michaelessiet** [comment]
> > I'm running into the same error, however it occurs after the app has undergone an update via Expo updates. It happens about 40% of the time
> 
> This is happening to a few of our users as well. Not 40% but still quite a lot of them. It happened as well after an EAS update.

At this point I just use https://github.com/ammarahm-ed/react-native-mmkv-storage

**Comment by gunnartorfis** [comment]
> @jvfalco1 From our side it was mistake because we added encryption to previously unencrypted DB but kept same name. We just reseted storage for everyone and it works for us.

Our case was similar - we upgraded react-native-mmkv to ^2.10 and then this started to happen since we added App Group config in that release as well. 

@mrousavy might be worth noting this in the docs/changelog. In our App's root error boundary we're calling storage.clearAll() if this error pops up. We can confirm that it solves the issue - we were thankfully in close contact with one of our user that was experiencing this

**Comment by mrousavy** [comment]
> might be worth noting this in the docs/changelog

Wait what exactly do you mean should be mentioned @gunnartorfis ?

**Comment by gunnartorfis** [comment]
> > might be worth noting this in the docs/changelog
> 
> Wait what exactly do you mean should be mentioned @gunnartorfis ?

@mrousavy If adding App Group support might need a storage reset to prevent unexpected behaviour like this one, then it would probably be good to mention it.
