### ISSUE TITLE
[Question] redux-persist with this or redux-persist-filesystem-storage ?

### ISSUE THREAD

**Issue by cristianoccazinsp** [mrousavy/react-native-mmkv#53]
I see you compared this against AsyncStorage, but what about using `redux-persist-filesystem-storage` ?

Would be great to benchmark:
- redux-persist + redux-persist-filesystem-storage   vs   redux-persist + react-native-mmkv.

Thoughts?

**Comment by mrousavy** [comment]
I have never heard of this library before, but you can benchmark this yourself and post results here in case anyone else is searching for this specific benchmark. 👍

**Comment by cristianoccazinsp** [comment]
I believe it basically writes JSON objects directly to the file system, and since redux-persist mostly writes JSON payloads to the storage engine, it should be quite fast for a few reducers.

However, in our app, we have ended up splitting most reducers into its own storage/file, so the largest the reducer list gets, the larger the file list will be at the end. At some point using a KV store like this library should be faster than writing N files to disk (one for each reducer).

I don't really have time to benchmark it now, but I will in the future :)

**Comment by alexco2** [comment]
@mrousavy redux-persist is a library that automatically saves state changes to the local state and re-hydrates the state on startup.
@cristianoccazinsp 
If I understand the new API correcty, the Methods do not return promises anymore. To use redux-persist with a localStorage library, it must support promises. 
https://github.com/rt2zz/redux-persist#storage-engines
I guess this means without adapting redux-persist, it will not work with mmvk. I have not testet it though. Would be great if it worked.

**Comment by jtdaugh** [comment]
@cristianoccazinsp did you ever get around to benchmarking this versus redux-persist-filesystem-storage? I'm about to do so, want to see if the work is already done. Thanks.

**Comment by cristianoccazinsp** [comment]
Hey. I did not benchmark it at all. We were already using file system and it was fast enough for our use case. Curious to see the results though!
