### ISSUE TITLE
Can not create Instance MMKV in Android when custom path and can not find file custom path in IOS

### ISSUE THREAD

**Issue by mvn-toannguyen2-dn** [mrousavy/react-native-mmkv#536]
when i create MMKV with path example:
```typescript
 /**
     * The MMKV instance's root path. By default, MMKV stores file inside `$(Documents)/mmkv/`. You can customize MMKV's root directory on MMKV initialization:
     *
     * @example
     * ```ts
     * const temporaryStorage = new MMKV({ path: '/tmp/' })
     * ```
     */
export const storage = new MMKV({
  id: 'user1',
  path: '/tmp/customPath',
});

```
This call success on IOS
```typescript
storage.set('user.name', 'xxxx');
```
when i log data i still show log but only on IOS. However i can not find my file in IOS device, i see folder MMKV(or TMP) but have nothing in there
![Screenshot 2023-04-21 at 1 57 06 PM](https://user-images.githubusercontent.com/30063881/233563332-1d6cbecd-a3cc-4a42-a025-7beb8a35f973.png)
```typescript
console.log(`${storage.getString('user.name')}`);
// LOG  xxxx
```
Android always throw error : Error: Exception in HostFunction: Failed to create MMKV instance!, js engine: hermes
And i want to try bad path like [issue 464](https://github.com/mrousavy/react-native-mmkv/issues/464)
I am using
react-native: 0.71.7
react-native-mmkv: 2.8.0

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)
