### ISSUE TITLE
Speeding up android builds

### ISSUE THREAD

**Issue by retyui** [mrousavy/react-native-mmkv#538]
Can we add cache for `boost`, (put downloaded zip to `/tmp` folder) ? 

It so annoying to see every build how it's stucking on downloading this 120mb zip, especially locally on my dev. laptop 

![image](https://user-images.githubusercontent.com/4661784/235294423-1f0e9c23-32e3-454e-8dcc-d432d92dca60.png)

**Comment by mrousavy** [comment]
Hey! Did you try the latest version? I remember removing the download.

**Comment by retyui** [comment]
updated to `2.8.0` it helps, thanks !
