### ISSUE TITLE
MMKV storage file grows rapidly

### ISSUE THREAD

**Issue by CostasCF** [mrousavy/react-native-mmkv#539]
I see the problem in #440 still occuring. I tried to install v2.7.0 with fastWrites disabled but my app keeps crashing on android.
Also, if I am not mistaken the fix for #440 in v2.7.0 is not present in v2.8.0?

Problem occuring:
"react-native-mmkv": "^2.8.0",
 "react-native": "0.71.7",

**Comment by CostasCF** [comment]
Why fastWrites property is not available in "react-native-mmkv": "^2.8.0" as it is the latest version?

**Comment by CostasCF** [comment]
Applied fix mention here in #440  (https://github.com/mrousavy/react-native-mmkv/issues/440#issuecomment-1421052424). 
More details: https://github.com/CostasCF/react-native-mmkv-storage-fix
You can install it with: npm install react-native-mmkv-storage-fix@2.8.0

**Comment by billnbell** [comment]
> I see the problem in #440 still occuring. I tried to install v2.7.0 with fastWrites disabled but my app keeps crashing on android. Also, if I am not mistaken the fix for #440 in v2.7.0 is not present in v2.8.0?
> 
> Problem occuring: "react-native-mmkv": "^2.8.0", "react-native": "0.71.7",

Why did the author revert fastWrites?

**Comment by CostasCF** [comment]
@billnbell I don't know honestly. I think it has to do with the speed you lose when you check if a key already exists and overwrite it instead of creating constantly a new one but with the disadvantage of increasing storage size. However you can download my package with the fix included (v2.8.0), I will try to maintain it in the future until the author adds fastWrites property again.

**Comment by billnbell** [comment]
> @billnbell I don't know honestly. I think it has to do with the speed you lose when you check if a key already exists and overwrite it instead of creating constantly a new one but with the disadvantage of increasing storage size. However you can download my package with the fix included (v2.8.0), I will try to maintain it in the future until the author adds fastWrites property again.

OK I am using your, can you upgrade to 2.10.0 ?

**Comment by CostasCF** [comment]
@billnbell I would suggest you to install the current latest version and check if the problem persists. If it does, I will upgrade mine to the latest version, otherwise I am not planning it for the time being.
