### ISSUE TITLE
_reactNativeMmkv.MMKV.set is not a function.

### ISSUE THREAD

**Issue by legaciespanda** [mrousavy/react-native-mmkv#54]
I used this module in an expo app to save a username, but it gives error.
`[Unhandled promise rejection: TypeError: _reactNativeMmkv.MMKV.set is not a function. (In '_reactNativeMmkv.MMKV.set("user.name", "Marc")', '_reactNativeMmkv.MMKV.set' is undefined)]`

@mrousavy @myckhel

**Comment by mrousavy** [comment]
That's because it does not work with Expo. You have to eject.

**Comment by shTalhagaba** [comment]
@mrousavy facing same error in cli any solution for this? Try almost everything
