### ISSUE TITLE
Could not find any matches for com.facebook.react:react-android:+  (build.gradle :react-native-mmkv)

### ISSUE THREAD

**Issue by chuhoanglong** [mrousavy/react-native-mmkv#540]
i got this error when i installed react-native-mmkv . library

Could not determine the dependencies of task ':react-native-mmkv:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mmkv:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Required by:
         project :react-native-mmkv

Could not find any matches for com.facebook.react:react-android:+ as no versions of com.face
<img width="639" alt="Screenshot 2023-05-19 at 17 47 32" src="https://github.com/mrousavy/react-native-mmkv/assets/37845536/74f8ea23-b414-4f00-9b22-ec818a29d83b">
book.react:react-android are available.
Required by:
    project :react-native-mmkv

I am using
react-native: 0.70.5
react-native-mmkv: 2.8.0

**Comment by mrousavy** [comment]
Do a clean and rebuild. I can't reproduce this error.

**Comment by chuhoanglong** [comment]
> Do a clean and rebuild. I can't reproduce this error.
> 
> EDIT: Just saw you're on RN 70. Try upgrading to RN 71, or downgrade MMKV to 2.5.x

After i use react-native-mmkv 2.5.1 version i run android get following error:

Native module MMKV tried to override MmkvModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=tr
<img width="318" alt="Screenshot 2023-05-20 at 11 17 10" src="https://github.com/mrousavy/react-native-mmkv/assets/37845536/8b105e99-1de5-4a7d-910c-f91d0b1ed728">
ue. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
