### ISSUE TITLE
安卓构建失败

### ISSUE THREAD

**Issue by ccmukden** [mrousavy/react-native-mmkv#541]
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Searched in the following locations:
       - file:/D:/ReactNativeProject/VipApp/node_modules/react-native/android/com/facebook/react/react-android/maven-metadata.xml
       - file:/D:/ReactNativeProject/VipApp/node_modules/jsc-android/dist/com/facebook/react/react-android/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-android/maven-metadata.xml
       - https://www.jitpack.io/com/facebook/react/react-android/maven-metadata.xml
     Required by:
         project :app > project :react-native-mmkv

**Comment by montanhes** [comment]
I have the same issue with

```
"react-native": "0.70.6",
"react-native-mmkv": "^2.8.0",
```
