### ISSUE TITLE
Storage Empties Itself When App is Backgrounded 🤯

### ISSUE THREAD

**Issue by youssdevx** [mrousavy/react-native-mmkv#542]
Hello everyone,

I've been experiencing an issue with MMKV in our React Native application. The problem seems to occur when the app is either backgrounded or killed for a certain period of time and then reopened. Upon reopening the app, the storage appears to be empty, which is causing data loss and disrupting the user experience.

Here's a more detailed description of the issue:

- When the app is active and in use, the storage works perfectly fine. Data is stored and retrieved as expected.
- Data is very small as it should be for all the keys, except for one key which is a JSON stringified with a weight of 4.9kB (could be the cause of the issue?)
- However, when the app is either sent to the background or killed (either by the system or the user), and then reopened after some time, the storage seems to be empty. All the data that was previously stored appears to be lost.
- This issue is not consistent. It doesn't happen every time the app is backgrounded or killed, but it happens often enough to be a significant problem.

I'm currently using React Native version 0.71.7 and react-native-mmkv version 2.8.0. This issue has been observed on multiple devices and OS versions.

Has anyone else experienced this issue recently? Any insights or suggestions would be greatly appreciated. I'm particularly interested in any possible workarounds or fixes, as this issue is currently causing significant disruption for our users.

Thank you in advance for your help!

**Comment by youssdevx** [comment]
Yes, but they are under strict conditions. Do you know if anyone has already encountered this kind of problem?

**Comment by youssdevx** [comment]
At the initialization of the application, we delete unused keys from the storage like this. Could this behavior be the source of the issue?

![image (1)](https://github.com/mrousavy/react-native-mmkv/assets/21293851/5dd6e98a-e32e-452b-abc9-3448190d00be)

**Comment by mrousavy** [comment]
Try removing that code and see if it works 🤷‍♂️

**Comment by youssdevx** [comment]
🙃🙃

**Comment by JoaoBGusmao** [comment]
I'm trying to find a similar issue where users are sometimes disconnected but I couldn't find anything. Seems to happen in a really small rate. Do you have a way to reproduce this issue?
In my case, i'm not sure if the mmkv is retuning empty (what makes sense looking at api logs).

RN 64.2/mmkv 2.5.1

**Comment by evelant** [comment]
@mrousavy I'm seeing similar behavior in iOS development. It appears that mmkv is "stuck". Every time the app reloads it resets itself to some previous set of stored data. Everything during the app run is lost, it reverts to the same old state every time.


![image](https://github.com/mrousavy/react-native-mmkv/assets/858965/de424a5a-d2ba-48c8-81bf-9c1eb7a19dd2)

**Comment by evelant** [comment]
Nevermind it was a bug in my app code 🤦 haha

**Comment by youssdevx** [comment]
@JoaoBGusmao I couldn't find a way to reproduce the issue yet...

**Comment by teckbeng-payboy** [comment]
This only happens when we use the encryption feature.

I also experience this when using the encryption

**Comment by mrousavy** [comment]
Hey! Sorry I cannot reproduce the issue here and it has been inactive for a while. 
I am going over issues right now and want to keep the repo clean - so I'm closing this for now, if anyone can post a reproduceable example here I can re-open and take a look :)

**Comment by elencho** [comment]
Same issue, when App goes to background on ios storage clears by itself

**Comment by SolankiYogesh** [comment]
@Kruthishchotu123  same

**Comment by niki-bri** [comment]
Did anyone manage to fix this, I have the same issue.

**Comment by youssdevx** [comment]
It still happens from time to time when working on simulator. 
However, I think the issue is fixed on production builds, I don't have the issue anymore 👌

**Comment by niki-bri** [comment]
Thanks for the answer! Are you using v3? I am still using v2 because of some other libs I that are not compatible with the new architecture. Also, production builds did not fix it for me (using v2).

**Comment by niki-bri** [comment]
I just managed to solve the problem for me (as far as I can tell with the testing I have done so far). I had the same app with two different ids on my phone, one for development, the other for (beta/performance) testing. They both used the same id resulting in some kind of conflict when accessing/writing data with mmkv. In any case, deleting the preduction build solved the problem.  I will simply two different mmvk storage ids to avaoid the problem going forward.

Thanks again @youssdevx  for the answer.

**Comment by youssdevx** [comment]
> Thanks for the answer! Are you using v3? I am still using v2 because of some other libs I that are not compatible with the new architecture. Also, production builds did not fix it for me (using v2).
> 
> 

Still using v2, planning on using v3 when upgrading to Expo SDK 52 🚀

**Comment by Nantris** [comment]
Just ran into this on Android with v3. Definitely not caused by our code. I'm guessing some sort of write failure occurs...

**Comment by Nantris** [comment]
@mrousavy I wonder if you have any thoughts on this?

It seems like this occurs if you try to save data to a key when backgrounding the app, and if the app is exited then the key ends up empty.

As fast as this project is, I'd like to avoid having to essentially double-write the data to create a backup version to restore from.

Do you have any advice for how we might make this more actionable? This should definitely not be closed, even if no one knows how to provide a repro case. This is an edge case that's likely going to be very difficult to reproduce reliably.

**Comment by rodperottoni** [comment]
I have ran into this same issue today. After quitting & restarting my app, the storage would go kapoot and never to be seen again.

My storage instantiation code looked like this:

```
this.id = id
this.store = new MMKV({ id })
this.schema = schema

/**
 * Enable encryption on Native.
 */
if (secure && isNative) {
  const encryptionKey = secureStorage.get('storageEncryptionKey') || Crypto.randomUUID()

  this.store.recrypt(encryptionKey)

  secureStorage.set('storageEncryptionKey', encryptionKey)
}
```

I then attempted to **not** call `recrypt`, and instead instantiate the storage **with** the encryption key

```
/**
 * Enable encryption on Native.
 */
if (secure && isNative) {
  const encryptionKey = secureStorage.get('storageEncryptionKey') || Crypto.randomUUID()

  this.store = new MMKV({ id, encryptionKey }) // Pass encryption key during instantiation

  secureStorage.set('storageEncryptionKey', encryptionKey)
} else {
  this.store = new MMKV({ id })
}
```

I understand my previous code might not have been correct, but decided to post this just in case anyone else has the same logic in their codebase.

**Comment by ninad-joshi-asurion** [comment]
@mrousavy any fix on this issue? I am facing this in IOS. I am using MMKV with encryption key. It doesn't empty storage immediately but when I restart the app 15 20 times it clears the storage.

Got this error message - [E] <MiniPBCoder.cpp:591::decodeOneMap> InvalidProtocolBuffer truncatedMessage

**Comment by Nantris** [comment]
I've only seen this twice but it's a real and very concerning issue.

The ticket should not be closed.

**Comment by Flyrell** [comment]
Still happening, this should be reopened.

**Comment by andrejsoucek** [comment]
Happens to us aswell. @mrousavy please reopen.

**Comment by Ankitinara** [comment]
this issue i also faced in without encrypted 
data lose and return to the login screen , please reopen

**Comment by Nantris** [comment]
Reopening doesn't even have to mean fixing this is planned. It just helps people know what issues to expect, if nothing else.

**Comment by mrousavy** [comment]
Are you experiencing this on V4?

**Comment by Nantris** [comment]
Thanks for your reply @mrousavy!

I hadn't realized v4 had recently released. We're still on v3, but since this bug is so hard to reproduce even a month or two on v4 can't rule it out. In the year I've been using this package I've only seen it happen 3x, but multiple by 10,000 users and it becomes a big and more frequent problem.

Understandable you'd want to know if this truly occurs in v4 though!

**Comment by SruthiVj** [comment]
Facing this issue in v4! (with encryption)

**Comment by axxjrl** [comment]
Facing the same with v3.3.3

**Comment by AhmedHany6161** [comment]
I’m running into a very similar issue on version 2.12.2. While I’m not 100% sure if the root cause is identical, I wanted to share my findings in case they help track this down!

## 📱 My Environment

Device: Android Emulator (Pixel 9 Pro)

OS: Android 15 (with Play Store)

Library Version: 2.12.2

##  🛠 Steps to Reproduce

Stress the write process: Attempt to set a very large string (encrypted or non-encrypted) to give yourself a wide enough window to interrupt the process.

The "Kill" move: Force-kill the app manually while that set operation is still in progress.

The Retrieval: Reopen the app and try to get the data using that specific key.

##  🔍 What I’m Seeing

The corrupted key starts behaving quite inconsistently. I've noticed:

It sometimes returns undefined.

Other times, it returns an empty string ("").

#### Logcat Error: MMKV.cpp:723::getString> InvalidProtocolBuffer negativeSize

#### Note: Interestingly, overwriting the corrupted key with a fresh .set() call works perfectly and restores the correct state.

## 💡 Potential Workaround

Since my data doesn’t change very often, I’ve been able to mitigate this by checking the value before writing. This minimizes the "danger window" by avoiding unnecessary set calls:

`private setInStorage(storage: MMKV, key: string, value: string) {
  // Only write if the key doesn't exist or the value has actually changed
  if (!storage.contains(key) || storage.getString(key) !== value) {
    storage.set(key, value);
  }
}`

Hopefully, this helps the maintainers or anyone else digging into this!
