### ISSUE TITLE
How to set the initial state for hooks like `useMMKVObject`?

### ISSUE THREAD

**Issue by TowhidKashem** [mrousavy/react-native-mmkv#554]
Amazing lib first and foremost, thank you!!

For the various hooks like `useMMKVObject` you need to pass the key name and optionally the mmkv instance as params, but is there a way to pass the initial state value as well like we can do when using React's built in `useState` or `useReducer` hooks?

Right now I'm handling it like this:

```
  let [filters, setFilters] = useMMKVObject<FormState>(
    'app.FILTERS',
    mmkvInstance
  );

  if (!filters) filters = initialState;
```
But this isn't ideal, is there something I'm missing for passing the initial state somehow?

And on an unrelated note, is it ok to mutate data stored in mmkv hooks? or should I follow the same rules as regular react and always copy the current value and apply changes on the copy and update using only the setter function?

**Comment by TowhidKashem** [comment]
> For default state: Do you want a default value for `filters` just in memory if nothing is in storage, or also written to storage?

In my particular use case just in memory is fine, that way the initial UI renders and doesn't break. The workaround I have now is working fine but thought it will be a little cleaner to have the default value for parity's sake.

> You _can_ do
> 
> ```
> filters.something = 5
> setFilters(filters)
> ```

Ah ok this is what I was asking, glad it won't cause issues. I know I still have to call `setFilters()` but figured not creating the extra copy before hand would save me some nano seconds but maybe the performance savings are negligible..

**Comment by doyunnn** [comment]
` let [filters = initialState, setFilters] = useMMKVObject<FormState>(
    'app.FILTERS',
    mmkvInstance
  );`

**Comment by TowhidKashem** [comment]
> ` let [filters = initialState, setFilters] = useMMKVObject<FormState>( 'app.FILTERS', mmkvInstance );`

Ah thats pretty clean, I'll close the issue cause this is good enough for my needs. Thanks.

**Comment by rklomp** [comment]
Looking for a solution of applying a default value I stumbled across this issue.
@mrousavy, Might be useful to add this to the docs?

Or create it as a more `useState`-like replacement that has a default value parameter:
```
useMMKVObject<T>(
  default: T,
  key: string,
  instance?: MMKV
)
```
