### ISSUE TITLE
Value rest after close and re-open the app RN 0.72.0

### ISSUE THREAD

**Issue by faisalamin9696** [mrousavy/react-native-mmkv#555]
I update my project to RN 0.72.0 and I am always getting an undefined value if I close and re-open my app. ANDROID

**Comment by mrousavy** [comment]
No code. No reproduceable example.

**Comment by faisalamin9696** [comment]
Hi @mrousavy, I am using 
` "react-native-mmkv": "^2.8.0",`

On android api 23 I stored a value with

```
export const setItemToStorage = (key, data) => {
  try {
    if (data) {
      const jsonValue = JSON.stringify(data);
      SharedPreference.set(`${key}`, jsonValue);
      return true;
    }
  } catch (e) {
    console.log('mmkv error: ' + String(e))
    return undefined;
  }
};
```

and getting value code is 

```
export const getItemFromStorage = (key: string) => {
  try {
    const data = SharedPreference.getString(`${key}`);
    if (data) {
      const jsonValue = JSON.parse(data);
      return jsonValue;
    }
  } catch {
    return undefined;
  }
};
```

The value is stored but when the app is force-stopped and open it again the value is undefined.

**Comment by karel-suchomel-ed** [comment]
@faisalamin9696 did you manage to fix it? I have the same problem. Everything worked fine on 0.71
