### ISSUE TITLE
How can I set an array of objects and get this array with key?

### ISSUE THREAD

**Issue by minhaz19** [mrousavy/react-native-mmkv#557]
I have an array of objects like this - 

`[{"__v": 0, "_id": "64a513baf9ee24c30378", "areaId": ["80ccf3037025096f4", "90ccf3037025096f45"], "circleId": ["30ccf3037025096f4", "40ccf3037025096f45cb87bf"], "createdAt": "2023-07-05T06:54:50.491Z", "deletedAt": null, "description": "Hip hip horreeeee!!!!!!", "dhId": ["50ccf3037025096f45cb87bf", "90ccf3037025096f45cb87bf"], "districtId": ["30ccf3037025096f45cb87bf", "60ccf3037025096f45cb87bf"], "endAt": "2023-07-05T06:37:15.018Z", "regionId": ["50ccf3037025096f45cb87bf", "60ccf3037025096f4"], "startAt": "2023-07-05T06:37:15.017Z", "territoryId": ["10ccf3037025096f45cb87bf", "20ccf3037025096f45cb87bf"], "updatedAt": "2023-07-05T06:54:50.491Z"}, {"__v": 0, "_id": "64a51405f9ee24c30378d74c", "areaId": ["80ccf3037025096f45cb87bf", "90ccf3037025096f45cb87bf"], "circleId": ["30ccf3037025096f45cb87bf", "40ccf303702509"], "createdAt": "2023-07-05T06:56:05.498Z", "deletedAt": null, "description": "This is the best shop", "dhId": ["50ccf3037025096f45cb87bf", "90ccf3037025096f45cb87bf"], "districtId": ["30ccf3037025096f45cb87bf", "60ccf30370250"], "endAt": "2023-07-05T06:37:15.018Z", "regionId": ["50ccf3037025096f45cb87bf", "60ccf3037025"], "startAt": "2023-07-05T06:37:15.017Z", "territoryId": ["10ccf3037025", "20ccf3037025"], "updatedAt": "2023-07-05T06:56:05.498Z"}]`

how can I set and get this in MMKV?

**Comment by mrousavy** [comment]
Use `JSON.stringify`

**Comment by minhaz19** [comment]
Hey, I am using a large amount of data that I have to save on local storage if I were offline and after I am getting online it will sync with the database. Do you suggest this package for this?

**Comment by yunzaifei** [comment]
@minhaz19 
write a custom hook like this:
```
type TUseMMKVArray = <T>(
  key: string,
) => [T | undefined, (v: T | undefined) => void];

export const useMMKVArray: TUseMMKVArray = <T>(key: string) => {
  const [value, setValue] = useState<T | undefined>();

  useEffect(() => {
    const strV = storage.getString(key);
    if (strV != null) {
      setValue(JSON.parse(strV) as T);
    } else {
      setValue(undefined);
    }
  }, [key]);

  const setArrValue = useCallback(
    (v: T | undefined) => {
      if (v == null) {
        setValue(undefined);
        storage.delete(key);
      } else {
        const jsonV = JSON.stringify(v);
        storage.set(key, jsonV);
        setValue(v);
      }
    },
    [key],
  );

  return [value, setArrValue];
};
```
use this custom hook:
```
const [array, setArray] = useuseMMKVArray<Record<string, any>[]>(key)
```
