### ISSUE TITLE
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by ragu-dattice** [mrousavy/react-native-mmkv#559]
node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, C:\Users\Developer23\Documents\ReactNative\Projects\mPlusTechnician\mplusTechnician3\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0

   "react": "18.0.0",
    "react-native": "0.69.3",

**Comment by mrousavy** [comment]
You need to upgrade RN to 0.71

**Comment by 8223-Samarpit** [comment]
> You need to upgrade RN to 0.71

Could you please suggest me any supporting version of this react-native-mmkv package with react-native: 0.70.6
