### ISSUE TITLE
React Native MMKV fails to build due to fbjni-0.5.0-headers.jar responding with 404

### ISSUE THREAD

**Issue by stiltet-gofore** [mrousavy/react-native-mmkv#564]
### Issue description
When deploying our React Native 0.70.6 app to Android through Fastlane we're now getting failed builds with the following error;

Please refer to [my issue](https://github.com/facebookincubator/fbjni/issues/85) created in FBJNI-repo and [this comment](https://github.com/facebookincubator/fbjni/issues/85#issuecomment-1647826877).

### Where:
Build file 'node_modules/react-native-mmkv/android/build.gradle' line: 322

### What went wrong:
```
Execution failed for task ':react-native-mmkv:extractAARHeaders'.
> Could not resolve all files for configuration ':react-native-mmkv:extractHeaders'.
   > Could not find fbjni-0.5.0-headers.jar (com.facebook.fbjni:fbjni:0.5.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.0/fbjni-0.5.0-headers.jar
```

When looking through https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni we see that the headers file is missing only for version 0.5.0.

https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.0/fbjni-0.5.0-headers.jar responds in 404.

**Comment by Elviogabriel** [comment]
getting same error here

**Comment by tim7on** [comment]
Same here.

**Comment by JeffPatricio** [comment]
same here

**Comment by Gustavo-Kuze** [comment]
Same here

**Comment by ghiculescualexandru** [comment]
same here, hope this gets fixed soon

**Comment by lego-sharat** [comment]
Any solution for this?

**Comment by lego-sharat** [comment]
What version are you using?

**Comment by williamliangwl** [comment]
possible fix: https://github.com/facebookincubator/fbjni/issues/85#issuecomment-1647970138

**Comment by zhekix** [comment]
```
   //noinspection GradleDynamicVersion
-  extractHeaders("com.facebook.fbjni:fbjni:+:headers")
+  extractHeaders("com.facebook.fbjni:fbjni:0.4.0:headers")
   //noinspection GradleDynamicVersion
-  extractJNI("com.facebook.fbjni:fbjni:+")
+  extractJNI("com.facebook.fbjni:fbjni:0.4.0")

```

**Comment by thtRajasthaniGuy** [comment]
same here

**Comment by paryanihitesh** [comment]
fbjni 0.5.1 released
https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.1/

**Comment by Yummy-sk** [comment]
build succeed

**Comment by marcos-cunha-gringo** [comment]
Any updates? Even after they fixed the fbjni release, the error remains.

**Comment by paryanihitesh** [comment]
You will have to clean yarn & gradle cache and try again

**Comment by CaioFernandoDev** [comment]
> You will have to clean yarn & gradle cache and try again

Already did and still fails

**Comment by marcos-cunha-gringo** [comment]
It's like the package are no recognizing that there are the version 0.5.1 of fbjni: 
![image](https://github.com/mrousavy/react-native-mmkv/assets/107485773/cd0980fc-ea98-461d-985f-099d6baed774)

**Comment by lucalves** [comment]
Unfortunately, the same here

**Comment by ollie-trackworx** [comment]
Still getting this error
```shell
 What went wrong:
Execution failed for task ':react-native-mmkv:extractAARHeaders'.
 Could not resolve all files for configuration ':react-native-mmkv:extractHeaders'.
    Could not find fbjni-0.5.0-headers.jar (com.facebook.fbjni:fbjni:0.5.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.0/fbjni-0.5.0-headers.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 Get more help at https://help.gradle.org 
```

**Comment by louicoder** [comment]
Im also getting the same error. The file doesn't exist on the server. Just followed the link and there's no such file.
[This link here](https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.0)

`/fbjni-0.5.0-headers.jar`

**Comment by paryanihitesh** [comment]
I tried the following steps and it worked for me
 - Delete gradle cache
 - Restart the system
 - gradle clean
And it worked

**Comment by louicoder** [comment]
> I tried the following steps and it worked for me
> 
> * Delete gradle cache
> * Restart the system
> * gradle clean
>   And it worked

Please add the respective commands (macOS/Unix) to your post. I would be grateful

**Comment by FetchefDev** [comment]
same here

**Comment by ollie-trackworx** [comment]
> ./gradlew :app:assembleRelease

I can confirm this solution results in a successful build, Thank you @paryanihitesh  and @stiltet-gofore

**Comment by mrousavy** [comment]
Hey!

Yea the latest version of react-native-mmkv fixes this issue, make sure y'all upgrade to 2.10.1! :)

**Comment by MehrabSp** [comment]
Hello!
I think there is a problem in the new version of React Native when installing the library for Android and gradle does not work properly in this library.
Maybe it is for me! I changed the gradle version from 7.2.2 to 7.2.1 and it worked correctly!

**Comment by mrousavy** [comment]
Hey - I think this has been fixed in V3 beta.
