### ISSUE TITLE
Best way to encrypt MMKV storage

### ISSUE THREAD

**Issue by skjorrface** [mrousavy/react-native-mmkv#565]
This is more a question than an actual issue. (sorry beforehand if this is the wrong place/way of asking). Is it safe to specify a private encryption key directly in react native code? If not, what's the safest way to create an encrypted MMKV storage?

**Comment by babaiyu** [comment]
Yes, we need best way to encrypt the storage. Currently in my project i just created one instance (include `encryptionKey`) and using it on whole code like this:

```js
const storage = new MMKV({
  id: 'mmkv_name_id',
  encryptionKey: env.ENCRYPT_STORAGE,
});
```

Did i do right encryption storage? Please comment and help us hehe...

**Comment by mrousavy** [comment]
Yea I think that's safe, iOS uses additional protection for storing that stuff anyways afaik

**Comment by skjorrface** [comment]
I was asking because I once read it's not adviseable to store sensitive information like API keys etc. inside environment variables, as they're not encrypted and included "verbatim" into app's build. I think I'll go for android/ios built in sandbox instead, as that encryption key makes no sense to me directly inside the JS bundle :D
