### ISSUE TITLE
pod install is failing `No package name found` on the latest version

### ISSUE THREAD

**Issue by retyui** [mrousavy/react-native-mmkv#568]
Failed to build the app: No package name found. Found errors in `node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml`

```tsx
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
```

to test it:

```
npx react-native config 

error Failed to build the app: No package name found. Found errors in node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
info Run CLI with --verbose flag for more details.
```

**Comment by mrousavy** [comment]
Hi yea https://github.com/mrousavy/react-native-mmkv/commit/40b71fe27269ee4c0bd5bfb83ee626bf41535cba fixed that but this isnt on npm yet

**Comment by mrousavy** [comment]
how is that related to pod install

**Comment by retyui** [comment]
> how is that related to pod install

baecuse pod install use `react-native config` commad to get list of native deps. that will be installed, 

and **old versions** or react-native EXPECT to have **package name** in **AndroidManifest**

---

so for backward compatibility you have to keep  **package name** in **AndroidManifest**

**Comment by datngotan-aavn** [comment]
I got the same issue with the library version 2.12.2 and React Native 0.69.12
error Failed to build the app: No package name found. Found errors in node_modules/react-native-mmkv/android/src/hasNamespace/AndroidManifest.xml.error Failed to build the app: No package name found.
