### ISSUE TITLE
Cannot resolve symbol 'reactnativemmkv'

### ISSUE THREAD

**Issue by tamacroft** [mrousavy/react-native-mmkv#57]
on android : `import com.reactnativemmkv.MmkvModule`
error is Cannot resolve symbol 'reactnativemmkv'

im using "react-native-mmkv": "^1.1.6",

**Comment by ivanszhuravlev** [comment]
I've got the same issue. Somehow after the installation, the "android" folder is empty
![image](https://user-images.githubusercontent.com/14206477/116545190-c70ff680-a8f8-11eb-94b5-2dd7bf15c63d.png)

**Comment by ivanszhuravlev** [comment]
@tamacroft This one looks like a workaround though https://github.com/mrousavy/react-native-mmkv/issues/37. Worked for me

**Comment by mrousavy** [comment]
> Somehow after the installation, the "android" folder is empty

The android folder in your screenshot is not empty. It contains an `aar` and a build.gradle file, which is the pre-compiled format for distributing android libraries.

**Comment by ivanszhuravlev** [comment]
Ah, ok, thanks, I didn't know that

**Comment by mrousavy** [comment]
@tamacroft did you try cleaning your entire android cache?

```
./gradlew clean
```

**Comment by tamacroft** [comment]
> @tamacroft This one looks like a workaround though #37. Worked for me

thx, it's work
