### ISSUE TITLE
[All] Plan to migrate to Turbo Module

### ISSUE THREAD

**Issue by ngocle2497** [mrousavy/react-native-mmkv#570]
Hi, @mrousavy.
You have any plan to migrate to new Arch Turbo Module?

**Comment by MasonLe2497** [comment]
what about migrate install function to TurboModule :D. i think i can help u with a small PR to do this. 
But, I dont know how react-native-mmkv can call install function when i turn on new Arch. RN docs said New Arch will use JSI instead Brigde while react-native-mmkv use old arch.  LOL

**Comment by MasonLe2497** [comment]
one think, i still waiting for WishList and RN Vision Camera(with Skia and Camera 2). Haha
