### ISSUE TITLE
State Setters from useMMKV hooks shoud support retrieval of previousState

### ISSUE THREAD

**Issue by fahad86** [mrousavy/react-native-mmkv#573]
This is to help with having a clean code with minimal dependancies (and probably fewer re-renders)

For e.g.

```js
const [user, setUser] = useMMKVObject("user");

let newName = "BLAHBLAH";

setUser((prevState) => {
  return {
    ...prevState,
    name: newName
  };
});
```

**Comment by mrousavy** [comment]
Good point, but this will be an extra read. What if the user doesn't need the previou state? then it will be an unnecessary DB Read

**Comment by mrousavy** [comment]
Wait hold on - isn't that already possible?

You can do 

```ts
const [username, setUsername] = useMMKVString("username");

let newName = "BLAHBLAH";

setUser((prevState) => {
  if (prevState === 'marc')
    return 'fahad86'
  else
    return 'marc'
});
```

**Comment by mrousavy** [comment]
Aha, it works for everything but not `useMMKVObject` yet. got it. https://github.com/mrousavy/react-native-mmkv/blob/f564552f262c0a446520fd03f83cd8656acd1917/src/hooks.ts#L178-L202

**Comment by fahad86** [comment]
> Aha, it works for everything but not `useMMKVObject` yet. got it.
> 
> https://github.com/mrousavy/react-native-mmkv/blob/f564552f262c0a446520fd03f83cd8656acd1917/src/hooks.ts#L178-L202

I assumed it didn't work for the other setters as well😅.. so what's the plan now?

**Comment by bviebahn** [comment]
Is there any reason this is not implemented yet? I currently just use my own hook which is pretty straightforward:
```ts
function useMMKVObject<T>(key: string) {
    const [json, setJson] = useMMKVString(key);

    const value = React.useMemo<T | undefined>(
        () => (json ? JSON.parse(json) : undefined),
        [json],
    );

    const setValue = React.useCallback(
        (v: T | undefined) => {
            if (typeof v === 'function') {
                setJson((currentJson) => {
                    const newValue = v(
                        currentJson ? JSON.parse(currentJson) : undefined,
                    );
                    return JSON.stringify(newValue);
                });
            } else {
                setJson(v ? JSON.stringify(v) : undefined);
            }
        },
        [setJson],
    );

    return [value, setValue];
}
```

**Comment by fahad86** [comment]
@mrousavy the above solution by @bviebahn  looks good right? There is also a related PR: https://github.com/mrousavy/react-native-mmkv/pull/254/files

**Comment by mrousavy** [comment]
Hey - that PR is outdated, can someone create a new PR with those changes? Then I think we can merge it, **however:** this is unsafe as there might've been outside modificiations to that data type (e.g. from a notification extension, data loss, or whatever) and the resulting type might not satisfy the type `T` anymore - so use it at your discretion.

**Comment by fahad86** [comment]
understood. PR created: https://github.com/mrousavy/react-native-mmkv/pull/623 please test to ensure that you don't see any issues in your side

**Comment by mrousavy** [comment]
Hey - I think this has been fixed in V3 beta.
