### ISSUE TITLE
Reentrancy Crash on start in iOS with install method

### ISSUE THREAD

**Issue by judastheo** [mrousavy/react-native-mmkv#574]
Hello,

We have been using `react-native-mmkv` for almost two years with a very good experience, using it coupled with `redux-persist`.

While switching from unimodules to new expo integration, introducing more JSI cool architecture stuff, we end up having our app crash on start on iOS.

### package.json
```json
    "expo": "48.0.20",
    "react-native-mmkv": "2.10.1",
```

### Error
Looking at the issue and based on analog discussion found [here](https://github.com/facebook/hermes/issues/1011), our understanding is that in the `MMKVModule`, it seems that it's a thread issue linked to the use of `RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD` for the install method, that [React-Native does not recommend](https://reactnative.dev/docs/native-modules-ios#synchronous-methods).

We tried to come up with simple workarounds but changing the method to make not synchronous and potentially solve the thread issue but failed due to the lack of deep understanding of the library on our part.

### Screenshot
![image](https://github.com/mrousavy/react-native-mmkv/assets/12097960/b0d8908e-b0c3-4dfa-bb48-7ea0da0e0918)

Is this issue reproductible on your side or do you have a workaround? Do not hesitate if you need more precision!

Thanks for the library, have a good day!

**Comment by mrousavy** [comment]
Hey! Glad to hear you've been using my library for over 2 years without any problems 😄 

I don't know where that Expo issue is coming from, I'm just guessing that they changed the threading and/or order of execution in synchronous methods, but I am not using Expo in any of my apps at the moment so I don't experience the same bug.

If you find a solution don't hesitate to send a PR and I'll gladly review/merge.

If you don't, we're happy to make this work for you through my agency, [Margelo](https://margelo.io) :)

**Comment by WJimmyCook** [comment]
Did you ever figure this out @judastheo ?

**Comment by mrousavy** [comment]
Hey - I think this has been fixed in V3 beta.
