### ISSUE TITLE
not work on some of devices like iPad that using m1

### ISSUE THREAD

**Issue by Youssef-Durgham** [mrousavy/react-native-mmkv#580]
not work on some of devices like iPad Pro m1 it return undefined but it work on iPhones and simulator that not using m1 here is how I set the token in signin page

import { MMKV } from 'react-native-mmkv';
export const storage = new MMKV();

const Sign_inScreen = props => {

.............

 await storage.set('jwtToken', response.data.token);

...........
return(.........);
};

and here is how I got the token in the Home Screen
import {MMKV} from 'react-native-mmkv';

export const storage = new MMKV();

function LocationProvider({children}) {

 useEffect(() => {
    const fetchData = async () => {
      try {
        const token = await storage.getString('jwtToken');
        setJwtToken(token);
        const decodedToken = jwtDecode(token);
        setCaptainId(decodedToken.id);
        const status2 = await AsyncStorage.getItem('socketClosedStatus');
        setStatus(JSON.parse(status2));
      } catch (error) {
        console.log('Error retrieving data:', error);
      }
    };

    fetchData();
  }, []);

return();}

**Comment by mrousavy** [comment]
Code not formatted appropriately, closing.
