### ISSUE TITLE
Return success state for `set` and `recrypt` calls

### ISSUE THREAD

**Issue by antondalgren** [mrousavy/react-native-mmkv#583]
The underlying MMKV library returns booleans on these calls wether the `set` or `recrypt` was made successfully or not. It would be nice if these boolean values were to be exposed in the JS world as the application developer may want to do different actions based on the outcome of these method calls. 

https://github.com/Tencent/MMKV/blob/272e5aa1fb57b4ee8cc0ff37e70b7885d99832a7/Core/MMKV_IO.cpp#L1101

https://github.com/Tencent/MMKV/blob/272e5aa1fb57b4ee8cc0ff37e70b7885d99832a7/Core/MMKV_IO.cpp#L557

**Comment by mrousavy** [comment]
Implemented in https://github.com/mrousavy/react-native-mmkv/pull/706
