### ISSUE TITLE
RN 0.74 debugger compatibility

### ISSUE THREAD

**Issue by jbrodriguez** [mrousavy/react-native-mmkv#586]
this is more of a question, not an issue, but seeing that RN  0.74 will drop support for flipper and switch to chrome debugger, i'm wondering whether this library will be compatible

**Comment by mrousavy** [comment]
RN 0.74??

**Comment by mrousavy** [comment]
but yea, it will work with RN 0.74. They will use JSI as well, so whatever Facebook uses works here as well. It's just the _remote_ debugger that won't work
