### ISSUE TITLE
Access MMKV from webview

### ISSUE THREAD

**Issue by jehillert** [mrousavy/react-native-mmkv#587]
Apologies if this is the wrong place to post this, but is there a way to access MMKV from a React app hosted in a React Native WebView?  I have an app that has a lot of complex interactions between injected react app and react native. The web app is served by the react app itself, via react-native-react-bridge.  It would be freaking amazing if they could share the same store, but I can't think of any way the web app and the react native to share a common instance.  

On the other hand, if WebView and React Native both read and write to the same place, then maybe a selector utility could be written that allows both sides to listen for changes to memory caused by the other side, in addition to the UI. Or so I assume. That may be a lot harder than I think it is.

**Comment by mrousavy** [comment]
Phew, this is a weird use-case 😅 

I'm not sure if you can make certain functions available in a WebView, if you can then you can just expose your MMKV object under the WebView's `global`, no?

**Comment by jehillert** [comment]
Yeah, actually I see now I was totally wrong. Seems like I can have one
store, and use middleware to send and receive copies of all the actions
across the bridge via onMessage.

Watching memory would be a fun approach.  But probably not good for
performance to keep checking all the time.  I think I was asking you
because I would expect the webviews to have all sorts of extra security
built into them and thought directly reading and writing inside the WebView
would requires some specialized configuration.  But that was just an
assumption.  I probably should go read up and see if it's already done with
asyncStorage.

Thanks for the response.  I will close the ticket if you haven't already.

**Comment by jehillert** [comment]
Yeah, I see now I was wrong. Seems like I can have one store, and use middleware to send and receive copies of all the actions across the bridge via onMessage.  I may even be able to reuse the same redux code for all the actions and selectors if I avoid circular references.

And yeah, probably not a great idea. Or not good for performance to keep checking storage all the time. 

Thanks for the response.  I will close the ticket if you haven't already.
