### ISSUE TITLE
Android: cannot resolve symbol 'reactnativemmvk'

### ISSUE THREAD

**Issue by LongThV** [mrousavy/react-native-mmkv#588]
+ I have this error on the latest version and only on Android and iOS running normally
+ I also installed according to this guide #37  but still cannot build

![Screenshot 2023-10-12 at 11 32 03](https://github.com/mrousavy/react-native-mmkv/assets/111482059/826c04be-9d39-489a-8fed-859c251ca527)

Version:
react-native: 0.68.4
react-native-mmkv : ^2.10.2
react-native-reanimated: ^2.12.0
Android: 13 sdk 33

**Comment by Bowlerr** [comment]
Did you manage to solve this?

**Comment by mrousavy** [comment]
Fixed in latest MMKV 2.11
