### ISSUE TITLE
Android: Why are the values reset when I update the app?

### ISSUE THREAD

**Issue by lluisandreu** [mrousavy/react-native-mmkv#590]
Does this library reset its values when the app is updated in the Google Play Store? If so, is there any solution to this issue?

Thanks.

**Comment by viv3kk** [comment]
any update on this

**Comment by ammar-madni** [comment]
Anyone else experiencing this? Seems like a huge deal breaker. @lluisandreu did you manage to confirm if the storage is reset when the app is updated?

**Comment by mrousavy** [comment]
I don't get the issue, are you asking a question, immediately assuming that storage IS reset, and then asking for alternatives?

For my app, storage is not reset. I don't know where you have that info from.
