### ISSUE TITLE
new support for react native 0.73 ?

### ISSUE THREAD

**Issue by chanphiromsok** [mrousavy/react-native-mmkv#592]
### Reason
- JSI is not working with chrome debugger 
- Flipper is drop in 0.73
### It will work in 0.73 but what use to debug ?

**Comment by hengkx** [comment]
> Task :react-native-mmkv:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: ninja: error: '/Users/***/.gradle/caches/transforms-3/c49f28b2318960124df4994698c4653d/transformed/jetified-react-android-0.73.0-release/prefab/modules/jsi/libs/android.arm64-v8a/libjsi.so', needed by '../../../../build/intermediates/cxx/RelWithDebInfo/506o2q4q/obj/arm64-v8a/libreactnativemmkv.so', missing and no known rule to make it

**Comment by clauderobi** [comment]
@hengkx Can you elaborate? Is it a tentative to make it work with a remote debugger, but failed?

**Comment by hengkx** [comment]
I use Android Studio success.I guess it may be related to the Java environment.https://reactnative.dev/docs/environment-setup?os=macos 
```
./gradlew assembleRelease  
```
fail

**Comment by hk-skit** [comment]
After upgrading app to RN 0.73, I see followings on console:

```
Task :react-native-mmkv:processDebugManifest
package="com.reactnativemmkv" found in source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativemmkv" from the source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
```

And some other warnings:

```
> Task :react-native-mmkv:buildCMakeDebug[arm64-v8a]
C/C++: ninja: Entering directory `/Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/.cxx/Debug/73n575e2/arm64-v8a'
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:20:80: warning: invalid conversion specifier 'b' [-Wformat-invalid-specifier]
C/C++:                       "Creating MMKV instance \"%s\"... (Path: %s, Encrypted: %b)",
C/C++:                                                                               ~^
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:21:57: warning: data argument not used by format string [-Wformat-extra-args]
C/C++:                       instanceId.c_str(), path.c_str(), hasEncryptionKey);
C/C++:                                                         ^
C/C++: 2 warnings generated.
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1338:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
C/C++:                             ^~~~~~
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1392:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
C/C++:                             ^~~~~~
C/C++: 2 warnings generated.
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
C/C++:             result = std::move(input.readData());
C/C++:                      ^
C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: note: remove std::move call here
C/C++:             result = std::move(input.readData());
```

This happens when the app build is created using RN CLI. Any possible workaround to get rid of these warning?

**Comment by mrousavy** [comment]
> JSI is not working with chrome debugger
> Flipper is drop in 0.73
> It will work in 0.73 but what use to debug ?

I'm sorry but what? What does this mean? What is the bug?

If you are saying "MMKV works in RN 0.73, but how do I debug it?" then the answer is that this question is not related to MMKV at all and should be asked in react-native repo. 

I think you can use Chrome's debugger for debugging. Or React Native Dev Tools.

**Comment by term51** [comment]
> After upgrading app to RN 0.73, I see followings on console:
> 
> ```
> Task :react-native-mmkv:processDebugManifest
> package="com.reactnativemmkv" found in source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
> Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
> Recommendation: remove package="com.reactnativemmkv" from the source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
> ```
> 
> And some other warnings:
> 
> ```
> > Task :react-native-mmkv:buildCMakeDebug[arm64-v8a]
> C/C++: ninja: Entering directory `/Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/.cxx/Debug/73n575e2/arm64-v8a'
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:20:80: warning: invalid conversion specifier 'b' [-Wformat-invalid-specifier]
> C/C++:                       "Creating MMKV instance \"%s\"... (Path: %s, Encrypted: %b)",
> C/C++:                                                                               ~^
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:21:57: warning: data argument not used by format string [-Wformat-extra-args]
> C/C++:                       instanceId.c_str(), path.c_str(), hasEncryptionKey);
> C/C++:                                                         ^
> C/C++: 2 warnings generated.
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1338:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
> C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
> C/C++:                             ^~~~~~
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1392:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
> C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
> C/C++:                             ^~~~~~
> C/C++: 2 warnings generated.
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
> C/C++:             result = std::move(input.readData());
> C/C++:                      ^
> C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: note: remove std::move call here
> C/C++:             result = std::move(input.readData());
> ```
> 
> This happens when the app build is created using RN CLI. Any possible workaround to get rid of these warning?

The same issue

**Comment by uguraktas** [comment]
Same issue here, Any idea?

**Comment by professorkolik** [comment]
You can use reactotron for time being

https://github.com/infinitered/reactotron/blob/master/docs/plugins/react-native-mmkv.md

**Comment by uguraktas** [comment]
> You can use reactotron for time being
> 
> https://github.com/infinitered/reactotron/blob/master/docs/plugins/react-native-mmkv.md

What does this have to do with reactotron?

**Comment by chanphiromsok** [comment]
> > After upgrading app to RN 0.73, I see followings on console:
> 
> > 
> 
> > ```
> 
> > Task :react-native-mmkv:processDebugManifest
> 
> > package="com.reactnativemmkv" found in source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
> 
> > Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
> 
> > Recommendation: remove package="com.reactnativemmkv" from the source AndroidManifest.xml: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/AndroidManifest.xml.
> 
> > ```
> 
> > 
> 
> > And some other warnings:
> 
> > 
> 
> > ```
> 
> > > Task :react-native-mmkv:buildCMakeDebug[arm64-v8a]
> 
> > C/C++: ninja: Entering directory `/Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/.cxx/Debug/73n575e2/arm64-v8a'
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:20:80: warning: invalid conversion specifier 'b' [-Wformat-invalid-specifier]
> 
> > C/C++:                       "Creating MMKV instance \"%s\"... (Path: %s, Encrypted: %b)",
> 
> > C/C++:                                                                               ~^
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/android/src/main/cpp/MmkvHostObject.cpp:21:57: warning: data argument not used by format string [-Wformat-extra-args]
> 
> > C/C++:                       instanceId.c_str(), path.c_str(), hasEncryptionKey);
> 
> > C/C++:                                                         ^
> 
> > C/C++: 2 warnings generated.
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1338:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
> 
> > C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
> 
> > C/C++:                             ^~~~~~
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1392:29: warning: 'const' qualifier on reference type 'MMKV::MMKVKey_t' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') has no effect [-Wignored-reference-qualifiers]
> 
> > C/C++:     auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {
> 
> > C/C++:                             ^~~~~~
> 
> > C/C++: 2 warnings generated.
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
> 
> > C/C++:             result = std::move(input.readData());
> 
> > C/C++:                      ^
> 
> > C/C++: /Users/hitesh/workspace/playground/HelloRN/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:704:22: note: remove std::move call here
> 
> > C/C++:             result = std::move(input.readData());
> 
> > ```
> 
> > 
> 
> > This happens when the app build is created using RN CLI. Any possible workaround to get rid of these warning?
> 
> 
> 
> The same issue

I think that not relate to issue at all
