### ISSUE TITLE
Does the storage work on native Android and IOS, after bundling the RN application

### ISSUE THREAD

**Issue by iamsamuelhere** [mrousavy/react-native-mmkv#593]
Say I have an ReactNative App, which uses react-native-mmkv. Now I generate a bundle file for Android and IOS. The generated bundle file if I include it in my Native Android and IOS to invoke my reactNative Application.

Will the package react-native-mmkv get loaded on the Native APP?

**Comment by mrousavy** [comment]
Yes.
