### ISSUE TITLE
Issue with Reactotron and MMKV Plugin

### ISSUE THREAD

**Issue by joelmulammoottil994** [mrousavy/react-native-mmkv#601]
Actual Behavior:
Using .use(mmkvPlugin({Storage})) causes a connection issue.

import { MMKV } from "react-native-mmkv";
export const Storage = new MMKV({
    id: "storage",
});
|
V
import { Storage } from './Storage/mmkv';
|
V
// When I comment on this line, the connection works correctly and has no issues.
// .use(mmkvPlugin({Storage}))

**Comment by mrousavy** [comment]
Not enough details, no stacktrace, no logs, no reproduceable example, heck I don't even know what Reactotron is.

**Comment by joelmulammoottil994** [comment]
<https://www.npmjs.com/package/reactotron-react-native-mmkv>I followed the
documentation <https://www.npmjs.com/package/reactotron-react-native-mmkv>
and successfully implemented the code. However, when I added
".use(mmkvPlugin({ storage }))" as indicated in the documentation, the
connection to Reactotron failed.
