### ISSUE TITLE
"React Native is not running on device" prevents me from running the app

### ISSUE THREAD

**Issue by ThaJay** [mrousavy/react-native-mmkv#608]
I have found the relevant issue https://github.com/mrousavy/react-native-mmkv/issues/567 and I understand MMKV is not supported in the browser-based debugger. I have no problem with that, but I do like to use it from time to time.

Please change the error into a warning and just let the app do its thing with MMKV disabled instead.

**Comment by mrousavy** [comment]
> with NNKV disabled instead

How? What does "disabled" mean?

**Comment by ThaJay** [comment]
> > with NNKV disabled instead
> 
> How? What does "disabled" mean?

@mrousavy Sorry to be unclear, my suggestion was to not crash the app but just tell the user MMKV does not work in this state.

Btw, this library feels really nice overall so thank you.

**Comment by mrousavy** [comment]
I get what you're saying ThaJay, but I am asking how you imagine this should work?

>  and let the rest of the app continue working.

How would the rest of the app continue to work? What should MMKV do? What will `storage.getBoolean` return? True or False?

**Comment by ThaJay** [comment]
> I get what you're saying ThaJay, but I am asking how you imagine this should work?
> 
> > and let the rest of the app continue working.
> 

My suggestion is to just change the current React Native error to a React Native warning.

Would that be possible or would there be other errors that come up in that case?
If other errors would come up it may be a bit more work to get this stable.

> How would the rest of the app continue to work? What should MMKV do? What will `storage.getBoolean` return? True or False?

I don't know, how does this currently handle getting a value from a string that is not known? Should a better even retrn when there is nothing to get? How do other well known storage / persistence libraries handle this?

**Comment by mrousavy** [comment]
I think in this case you should probably mock the database. I don't think I should silently stub it out and just return undefined or false everywhere, that's probably a bit unsafe.
