### ISSUE TITLE
getBoolean returns undefined

### ISSUE THREAD

**Issue by emmyduruc** [mrousavy/react-native-mmkv#609]
i am using react-native and     "react-native-mmkv": "^2.10.1",
when i set  
storage.set('is-mmkv-fast-asf', true)
and try to Get

const isMmkvFastAsf = storage.getBoolean('is-mmkv-fast-asf') // true
when i console.log(isMmkvFastAsf) i get undefined 

does anyone have a solution to this ?

**Comment by mrousavy** [comment]
I am doing the same thing in the example app and cannot reproduce it.

Share a reproduceable example, otherwise I can'T really help you
