### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by imanshul** [mrousavy/react-native-mmkv#619]
after adding NotificationService (NS) and NotificationViewController (NVC) in iOS app along with appGroup the MMKV is throwing below error.

> 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

I've added MMKV to app target pod along with MMKVAppExtension to both NS and NVC, but still it gives the error. I've also added AppGroup key in info.plist of App but not able to resolve, can you please help me with steps needed to setup.

react-native: 0.73.1
react-native-mmkv: 2.11.0

**Comment by mrousavy** [comment]
This is not related to MMKV. You have to create individual push notification services for your apps.

**Comment by imanshul** [comment]
This was the issue related to MMKV only when app extensions are used, so i need to know the steps to be used in order to use MMKV with App extensions.

**Comment by rawatnaresh** [comment]
@imanshul How did you fix this?

**Comment by peterferguson** [comment]
This fixed the problem for me

https://github.com/Tencent/MMKV/issues/881

**Comment by Nehal-Zeller** [comment]
Hey were you able to find a fix for it?
facing the same issue on adding wallet extension

I tried updating pod file as per above suggestion but didn't help


```
....
target 'myApp' do
config = use_native_modules!

target 'WNonUIExtension' do
pod 'MMKVAppExtension'
end

target 'WUIExtension' do
pod 'MMKVAppExtension'
end
...
```

could you help me here?

**Comment by Nehal-Zeller** [comment]
@imanshul  could you share if you were able to resolve this? Much appreciated!
