### ISSUE TITLE
app groups: value undefined until restart

### ISSUE THREAD

**Issue by coopermaruyama** [mrousavy/react-native-mmkv#622]
I'm using this to share data between a share extension and a react native app and noticing an issues that is pretty easily reproducible.

Observed behavior (when react native app is closed):
- call `set('key','value')` on extension
- open app
- call `get('key')` , returns 'value' (works as expected).

Observed behavior (when app is backgrounded):
- call `set('key','value')` on extension
- open app
- call `get('key')` , returns undefined (unexpected).
- at this point, if I close the app, and then reopen it, a call to `get('key')` now returns 'value'

So the value is indeed being written correctly to the shared container, however the app can only read it after a restart, which leads me to believe that the initialization code is a requirement in order to get the right value.

**Comment by coopermaruyama** [comment]
of course. If the app groups were not correctly set up, there would be no case where I can share values between the app and the extension. It indeed works, but the issue here is that, it is not readable by the 'other side' until that app is restarted. hope that makes sense..

I'm going to try modifying the library such that the initialization code re-runs when the app state goes background -> foreground. If this fixes the issue then it would confirm my suspicion that there is some dependency on that code running in order for the values to be updated on the other side.

**Comment by mrousavy** [comment]
Okay so the MMKV instance gets created with AppGroups... idk

**Comment by nmalzieu** [comment]
I can confirm I started having issues with data being stale in my extension.

Have been using AppGroups with MultiProcess mode for 6+months without any issue.

Recently upgraded to Expo 50 & RN 0.73, not sure if that's linked, but now my extension often reads stale data, and sometimes logs `InvalidProtocolBuffer truncatedMessage`
