### ISSUE TITLE
App group enhancement introduced a breaking change (2.10.0)

### ISSUE THREAD

**Issue by JP250552** [mrousavy/react-native-mmkv#627]
The change introducing app groups moved the storage location when the app groups property is set which is a breaking change - https://github.com/mrousavy/react-native-mmkv/pull/402/files#diff-b667beab6bbb6d80aab761c6781a9a7fea5812e5814d98666080a2ec6edb38dfR46

Upgrading to 2.10.0 causes our users to lose stored data since we had an app group previously defined for other reasons.

It would probably be good to revert and release that change as v3 and also provide a way to override that storage location for backwards comparability.

**Comment by mrousavy** [comment]
Oh, whoops. Hmm I don't think reverting that change makes sense as that was more than a year ago and most people are already on that version by then, meaning they'll lose any data unless they upgrade to v3.

I think you could easily migrate by moving the mmkv file from the normal directory to the appgroup directory.

**Comment by JP250552** [comment]
That's a fair point. Would you be opposed to us adding a property to allow using the default location?
