### ISSUE TITLE
Error: react-native-mmkv is not supported in Expo Go! Use EAS

### ISSUE THREAD

**Issue by erdincakdogan** [mrousavy/react-native-mmkv#638]
Hello guys,

Error: react-native-mmkv is not supported in Expo Go! Use EAS (expo prebuild) or eject to a bare workflow instead., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
A module failed to load due to an error and AppRegistry.registerComponent wasn't called., js engine: hermes

Everything was normal but I got this error I dont know why.

"dependencies": {
    "@ant-design/icons": "^5.1.2",
    "@expo/config-plugins": "^7.8.4",
    "@formatjs/intl-displaynames": "^6.6.1",
    "@formatjs/intl-locale": "^3.4.0",
    "@formatjs/intl-pluralrules": "^5.2.7",
    "@react-native-community/checkbox": "^0.5.15",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "expo": "^49.0.8",
    "expo-application": "^5.8.3",
    "expo-build-properties": "~0.8.3",
    "expo-checkbox": "~2.4.0",
    "expo-constants": "^15.4.5",
    "expo-dev-client": "~2.4.8",
    "expo-device": "^5.9.3",
    "expo-localization": "~14.3.0",
    "expo-modules-core": "^1.11.9",
    "expo-notifications": "^0.27.6",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.12",
    "firebase": "^9.23.0",
    "formik": "^2.4.0",
    "i18next": "^23.6.0",
    "react": "18.2.0",
    "react-dom": ">=16.8.0",
    "react-i18next": "^13.3.1",
    "react-native": "0.72.10",
    "react-native-eject": "^0.2.0",
    "react-native-elements": "^3.4.3",
    "react-native-fast-image": "^8.6.3",
    "react-native-flatlist-slider": "^1.0.6",
    "react-native-image-slider-box": "^2.0.7",
    "react-native-international-phone-number": "0.6.5",
    "react-native-ionicons": "^4.6.5",
    "react-native-linking": "^0.0.0",
    "react-native-mmkv": "^2.10.2",
    "react-native-paper": "^5.7.2",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "13.2.2",
    "twilio": "^4.12.0",
    "typescript": "^5.1.3"

**Comment by mrousavy** [comment]
react-native-mmkv is not supported in Expo Go! Use EAS (expo prebuild) or eject to a bare workflow instead.

**Comment by pizzou** [comment]
how did you fix this error ERROR  Error: react-native-mmkv is not supported in Expo Go! Use EAS (`expo prebuild`) or eject to a bare workflow instead., js engine: hermes I am also facing it

**Comment by pizzou** [comment]
when i try to use zeego  got this error Invariant Violation: requireNativeComponent: "MenuView" was not found in the UIManager

**Comment by erdincakdogan** [comment]
deleted mmkv, install asyncstorage :)

**Comment by mirsahib** [comment]
is it the only solution,i really want to use it in expo

> deleted mmkv, install asyncstorage :)

**Comment by Priyanshuahuja72** [comment]
> when i try to use zeego got this error Invariant Violation: requireNativeComponent: "MenuView" was not found in the UIManager

same problem i am facing too

**Comment by AnkushSarkar10** [comment]
yo why is this closed? Same issue

**Comment by VGerris** [comment]
same here

**Comment by mrousavy** [comment]
Are you guys using Expo Go?

**Comment by VGerris** [comment]
Yes

**Comment by mrousavy** [comment]
With all due respect... what???

The error message literally says MMKV is not supported in Expo Go

**Comment by swapnil20711** [comment]
![Image](https://github.com/user-attachments/assets/5e376d0c-5c10-4398-8adc-abcbf810e97f)
Here is the attached screenshot i am also facing this error @mrousavy I tried to run **npx expo prebuild** but i am still facing the same issue.

**Comment by VGerris** [comment]
Actually I misunderstood, I thought Expo Go was used for development build
back then.

**Comment by GourabSanyal** [comment]
Use the dev build and generate native modules to use MMKV instead of the Expo build.
MMKV does not work without native modules being present.

check [this](https://github.com/mrousavy/react-native-mmkv/issues/549#issuecomment-2492024934) and [this](https://github.com/mrousavy/react-native-mmkv/issues/549#issuecomment-1891100584)
