### ISSUE TITLE
Crash reports after switching to use AppGroups due to 0xdead10cc

### ISSUE THREAD

**Issue by mattsellars123** [mrousavy/react-native-mmkv#650]
Hello,

We are using MMKV in a react native app and were hoping to share our mmkv stores using AppGroups. After configuring things everything seemed to work fine for a while then we started getting crash reports with: 

`Termination Reason: RUNNINGBOARD 0xdead10cc`

We do not yet have any extensions writing to this store. I was wondering if there is some other configuration we need to add so that iOS isn't killing our process when the user happens to background it during file writes. 

Any insight is very appreciated.

**Comment by mrousavy** [comment]
I need full crash logs.

**Comment by mattsellars123** [comment]
Here you go. Thanks for taking a look. Generally what I've seen from other file uses for iOS specifics are listening on backgrounding event from App delegate and using the `UIApplication.shared.beginBackgroundTask` but this is very iOS/UIKit specific in this case and from the react side there are many mmkv uses we would need to ensure are sync'd out to the filesystem and released/closed.

[2024-03-19_11-30-10.6591_-0700-2bd285d62f19f77b80ec7dd30686dfc7c6f74e90.crash.log](https://github.com/mrousavy/react-native-mmkv/files/14704732/2024-03-19_11-30-10.6591_-0700-2bd285d62f19f77b80ec7dd30686dfc7c6f74e90.crash.log)
