### ISSUE TITLE
Cannot run in react-native 0.73.x

### ISSUE THREAD

**Issue by DeVoresyah** [mrousavy/react-native-mmkv#652]
## Env
- "react-native-mmkv": "^2.12.2"
- "react-native": "0.73.6",

## Description
I just upgraded my react native project to `0.73.6` to fix some issues. After that when I run again on the android emulator. I got this error:

```
Note: /Users/devoresyah/Documents/react-native/biomedika/node_modules/react-native-mmkv/android/src/main/java/com/reactnativemmkv/MmkvModule.java uses or overrides a deprecated API.
```

I think it's related about rn 0.73.x using kotlin

**Comment by mrousavy** [comment]
This is not an error, but a "note"/warning.
