### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by tristanheilman** [mrousavy/react-native-mmkv#659]
Starting May 1st, Apple is requiring declarations for API usage as part of their privacy update for App Store submissions. I believe this package will need to include the `NSPrivacyAccessedAPICategoryUserDefaults` API declaration.

I ran a scan on my project and found this
```
Found potentially required reason API usage 'UserDefaults' in './WridzRefactorV2/ios/Pods/Headers/Public/MMKV/MMKV.h'
Line numbers: 369 371 
Found potentially required reason API usage 'NSUserDefaults' in './WridzRefactorV2/ios/Pods/Headers/Public/MMKV/MMKV.h'
Found potentially required reason API usage 'UserDefaults' in './WridzRefactorV2/ios/Pods/MMKV/iOS/MMKV/MMKV/MMKV.h'
Line numbers: 369 371 
Found potentially required reason API usage 'NSUserDefaults' in './WridzRefactorV2/ios/Pods/MMKV/iOS/MMKV/MMKV/MMKV.h'
Found potentially required reason API usage 'UserDefaults' in './WridzRefactorV2/ios/Pods/MMKV/iOS/MMKV/MMKV/MMKV.h'
Line numbers: 369 371 
Found potentially required reason API usage 'NSUserDefaults' in './WridzRefactorV2/ios/Pods/MMKV/iOS/MMKV/MMKV/MMKV.h'
```

Here is a link to a discussion on the react-native-community repo
https://github.com/react-native-community/discussions-and-proposals/discussions/766

Link to Apple Documentation outlining this privacy update
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by mrousavy** [comment]
MMKV Core is already working on this; https://github.com/Tencent/MMKV/commit/06797a74505043ede9b239afe244cab0d3623aa5

We don't need a privacy manifest, we will just no longer rely on those sensitive APIs.

**Comment by mshivam019** [comment]
will there be a new release soon, for this patch?

**Comment by mrousavy** [comment]
MMKV didn't create a new release yet.

**Comment by tristanheilman** [comment]
Looks like the new release was shared 5 days ago. https://github.com/Tencent/MMKV/releases/tag/v1.3.5

**Comment by matteodanelli** [comment]
@tristanheilman where do you run pod install? How can the MMKV module inside can update?

**Comment by tristanheilman** [comment]
> @tristanheilman where do you run pod install? How can the MMKV module inside can update?

I have react-native-mmkv ^2.12.2 installed. Just cd into your iOS directory and run `pod install --repo-update`. The update to the MMKV SDK was a patch update, reinstalling pods should pull in the updated version. After running pod install, check the Podfile.lock folder for MMKV ~> 1.3.5

If you have 1.3.5 installed then you are good to go.

**Comment by mrousavy** [comment]
Fixed in V3 :)
