### ISSUE TITLE
[question] support array value

### ISSUE THREAD

**Issue by troZee** [mrousavy/react-native-mmkv#66]
Hey, 
Does this library support arrays of simple values like string, boolean, numbers etc ? I would like to store last searched results inside mmkv. 

## example 

```js 
import { MMKV } from 'react-native-mmkv';

MMKV.set('app-mmkv-key', [1,2,3])
```

**Comment by mrousavy** [comment]
Hi! MMKV supports storing _primitive_ values, but you can easily store arrays (or objects) by using JSON.stringify and JSON.parse.

**Comment by troZee** [comment]
Thank you for the explanation. I would like to avoid this kind of workaround. Do you plan to implement this feature ?

**Comment by mrousavy** [comment]
Maybe some time I will, but again; it will just do the same serialization and deserialization, just internally. It is just going to convert the array into a protobuf array, and decode it again. `JSON.stringify` is not a weird workaround, it works just fine.

You can also use multiple keys in the meantime, so:

```js
MMKV.set('search-result[0]`, 'hello')
MMKV.set('search-result[1]`, 'world')
MMKV.set('search-result[2]`, 'test')
```

**Comment by nwazuo** [comment]
@devDoubleH Maybe read the array, modify it and write it back?
