### ISSUE TITLE
Storage breaks when calling storage.clearStore() on empty storage

### ISSUE THREAD

**Issue by itsjustjo96** [mrousavy/react-native-mmkv#664]
Using React Native 0.73.

I noticed that when calling `authStorage.clearStore()` twice makes it behave weirdly and not accept any values anymore. I do get the following warning when trying to set a value on that storage.
`Trying to set a object value to hook for type boolean is not allowed.`

The storage was initialized like that.
```typescript
export const authStorage = new MMKVLoader().withEncryption().withInstanceID('auth').initialize()
```

After clearing the storage two times, I try to set it's value like this 

```typescript
const authInfoTmp = {
  id: 'abc',
  phone: {
    countryCode: '+1',
    number: '12345',
  },
  role: 'user',
} satisfies AuthInfo
setAuthInfo(authInfoTmp)
```

Then I do get the warning mentioned above and setting doesn't work. What is really interesting, the storages value is undefined when being queried like that:

```typescript
const [authInfo] = useMMKVStorage<AuthInfo>('auth', authStorage)
```

When force closing the App and reopening it, the storage has the value `true` and still won't accept new values until cleared again (once). Then it works normally again.

I wonder if this is an underlying issue or just a user issue. I'm happy to help investigating this issue further if needed.

Thank you in advance!!

**Comment by mrousavy** [comment]
I don't think this is related to react-native-mmkv. Try calling the `clearAllKeys()` function yourself
