### ISSUE TITLE
Crashing on bundle reload in beta version

### ISSUE THREAD

**Issue by matinzd** [mrousavy/react-native-mmkv#667]
Hey!

I was playing around with the beta version and I faced this issue when refreshing the bundle in development. 

```
[RNMMKV]: Closing all MMKV instances...
[RNMMKV]: Destroying MMKV instance ""...

com.facebook.react.runtime.JavaScript (6): signal SIGABRT
```

Screenshot of the crash in XCode:

<img width="1465" alt="Screenshot 2024-04-26 at 23 54 11" src="https://github.com/mrousavy/react-native-mmkv/assets/24797481/38d2ec80-e6e2-4865-ab4f-0c667af1aa4e">

```
#3	0x000000010506343c in mmkv::ScopedLock<mmkv::ThreadLock>::ScopedLock(mmkv::ThreadLock*) at /Users/matin.zadeh.dolatabad@schibsted.com/work/kreddy-frontend/node_modules/react-native-mmkv/MMKV/Core/ScopedLock.hpp:45
```

Hope it helps. Let me know if you need more info :) 

## Environment:

React Native Version: 0.74.0
New architecture + Bridgless enabled
RN MMKV: 3.0.0-beta.1

**Comment by mrousavy** [comment]
Fixed in the PR!
