### ISSUE TITLE
How to Implement iCloud Sync to Keep Reinstalled Apps to Recover Data？

### ISSUE THREAD

**Issue by wdk956093628** [mrousavy/react-native-mmkv#673]
I'm using 'react-native-mmkv' and 'redux-persist', when closing the app and reopening it the data is still there, but when the app is uninstalled and reinstalled the data is lost!

I don't know how to keep icloud synchronized, is there a configuration item for that? Or is it not supported by the library?

**Comment by realPrimoh** [comment]
That needs a custom implementation that's probably not in scope for this library.

**Comment by mrousavy** [comment]
Yep agreed- I also don't think that MMKV should persist data when the user explicitly uninstalls the app.

MMKV stores data in $(Documents) directory, so you can just back that up to iCloud if you want.

**Comment by wdk956093628** [comment]
Is it possible to do this by configuring MMKV's path, 
I read this https://github.com/Tencent/MMKV/issues/107

**Comment by rikur** [comment]
@konson-git That's how iCloud backup works. For sync, I'd recommend checking out other libraries like https://www.legendapp.com/open-source/state/v3/
