### ISSUE TITLE
After defining the path for the MMKV instance, an empty 'MMKV' directory is still generated under $(Documents)

### ISSUE THREAD

**Issue by bear-ei** [mrousavy/react-native-mmkv#676]
In macOS, even after customizing the path for all my MMKV instances, an empty 'MMKV' directory is still created under my Documents folder.

` const appStorage = useMMKV({id: 'app', path: storagePath})`

**Comment by mrousavy** [comment]
Yea because that's the default folder

**Comment by bear-ei** [comment]
> Yea because that's the default folder

I understand there is a default folder setting. However, I would like it to generate only the specified path folder after I have given an explicit path for the MMKV instance. I don't want it to generate an additional default folder that is useless for the application. I am unsure if there is a way to achieve this.

**Comment by mrousavy** [comment]
There currently is no public config option - however you can just hotpatch this yourself by passing a custom `baseDir` to the native install() / initialize() function .
