### ISSUE TITLE
Expo managment.

### ISSUE THREAD

**Issue by andres-dos-santos** [mrousavy/react-native-mmkv#677]
Hi guys, it's just a simple question, do you have any plans for MMKV to run in an Expo management project?

**Comment by mrousavy** [comment]
Hi - that's not up to me. Expo needs to pull react-native-mmkv into Expo Go if they want to have support for react-native-mmkv :)

**Comment by andres-dos-santos** [comment]
Ok!

**Comment by mrousavy** [comment]
You can just contact them I think there's an open issue even about this
