### ISSUE TITLE
Beta 5 Android build error cannot find symbol

### ISSUE THREAD

**Issue by joacub** [mrousavy/react-native-mmkv#679]
<img width="1180" alt="image" src="https://github.com/mrousavy/react-native-mmkv/assets/2091228/94b923bf-36ef-4d60-8061-3652d2a47a13">

**Comment by mrousavy** [comment]
not enough info.

**Comment by evelant** [comment]
It builds in new arch / bridgeless mode but not in normal mode, not sure why yet

**Comment by joacub** [comment]
> It builds in new arch / bridgeless mode but not in normal mode, not sure why yet

Yes

**Comment by mrousavy** [comment]
lol what is "normal mode"?

**Comment by joacub** [comment]
> lol what is "normal mode"?

New arch disabled

**Comment by mrousavy** [comment]
See this section in the README:

![Screenshot 2024-05-21 at 11 10 18](https://github.com/mrousavy/react-native-mmkv/assets/15199031/b8676320-af56-4d70-99e0-a02ceca0720c)

**Comment by joacub** [comment]
Got it, so lets wait ti until vision camera gets compatible with mew arch 🫡

**Comment by joacub** [comment]
do you have any idea when vision camera will be compatible with the new arch ?

**Comment by mrousavy** [comment]
see https://github.com/mrousavy/react-native-vision-camera/issues/2614
