### ISSUE TITLE
trim not present

### ISSUE THREAD

**Issue by Cancercookie** [mrousavy/react-native-mmkv#686]
Hi, I noticed that in the readme there's a reference to a .trim() function but it's not present in the code. 
I love to have such function in my code, is there any plan to add it soon to v2?

**Comment by mrousavy** [comment]
It is in the codebase, in beta on npm.

**Comment by Cancercookie** [comment]
I saw that, in fact I'm asking for v2. At the moment we don't plan to move towards the new architecture so upgrading to v3 it's a no go from my org.

**Comment by mrousavy** [comment]
Ah didn't see that - well no it's not part in v2.

I can add it for v2 if your company wants to sponsor those efforts
