### ISSUE TITLE
Android armeabi-v7a support dropped by Tencent

### ISSUE THREAD

**Issue by mjgalawork** [mrousavy/react-native-mmkv#687]
Tencent dropped the support for armeabi-v7a in the 1.3.5 (April 24) release of mmkv.

This means the libmmkv.so is not build for this architecture and those android devices crash.

**Comment by mrousavy** [comment]
Okay - well there's nothing I can do about this then

**Comment by mjgalawork** [comment]
I know. I just think it should be as an info in the readme or somewhere else so people know about it

**Comment by mrousavy** [comment]
Ah okay yea I mean I'll check what the usage % of v7a is and maybe if other packages don't support it either - then depending on that I'll maybe add it or not add it to the README. Thanks for letting me know
