### ISSUE TITLE
Error: Failed to create a new MMKV instance: React Native is not running on-device. 

### ISSUE THREAD

**Issue by vytautas-urbelis** [mrousavy/react-native-mmkv#688]
Error: Failed to create a new MMKV instance: React Native is not running on-device. MMKV can only be used when synchronous method invocations (JSI) are possible. If you are using a remote debugger (e.g. Chrome), switch to an on-device debugger (e.g. Flipper) instead.

    "expo": "^51.0.0",
    "react-native": "0.74.1",
    "react-native-mmkv": "^2.12.2",

I am not using any debuggers as mentioned in the error. I am running the iOS simulator on macOS and on an iPhone, not using the Expo Go app.

Perhaps someone else has experienced the same issue?

This is my first time opening an issue and I am new to development, so I apologize if the issue is presented incorrectly or if there is missing information.

Thank you.

![Simulator Screenshot - iPhone 15 - 2024-06-03 at 18 11 03](https://github.com/mrousavy/react-native-mmkv/assets/43892711/aa6bb592-68b0-4e73-9681-34f877537cec)

**Comment by vytautas-urbelis** [comment]
Updated MMKV to:

     "react-native-mmkv": "3.0.0-beta.5",

and and it works now.

**Comment by pablospaniard** [comment]
This beta implies a new architecture to be enabled
![image](https://github.com/mrousavy/react-native-mmkv/assets/10797797/c379e980-15e9-424c-b3b8-6d37852c65fa)
It is still considered experimental and not ready for production use.
https://reactnative.dev/docs/the-new-architecture/landing-page#should-i-use-the-new-architecture-today
Please fix/update v2.

**Comment by pablospaniard** [comment]
@vytautas-urbelis please reopen

**Comment by mrousavy** [comment]
Maybe something changed with the bridge setup - either way the future is V3 - it's a pure CxxTurboModule, and yes, that requires the new architecture but I cannot support hundreds of different configurations of setups. One with RN 0.73 old arch, one with RN 0.73 new arch, RN 0.74 old arch, RN 0.74 new arch, etc etc there's so much change inbetween that V3 only supports new arch.

**Comment by mrigo** [comment]
Hey, some update?
I cannot use it on Android with v2 or on iOS with v3 :'/

**Comment by Dinesh7571** [comment]
If youre react native version is less than   0.76      then use this version of mmkv 2.12.2

**Comment by qalabhussnainshah** [comment]
I cannot use it on Android with v2 or on iOS with v3

**Comment by MuhammadRomanKhan717** [comment]
> Updated MMKV to:
> 
> ```
>  "react-native-mmkv": "3.0.0-beta.5",
> ```
> 
> and and it works now.

great its works

**Comment by galdinoramon** [comment]
@Dinesh7571 thats is the exact version I am using and still get this error, any workaround to solve this? I need to use the old arch for now!

**Comment by mrousavy** [comment]
I don't know. V2 hasn't been updated in more than half a year, we're already on V3.

**Comment by MohammadAliNajm** [comment]
![Image](https://github.com/user-attachments/assets/3fd530cd-5370-4260-8ee0-76c743f845fc)

I can't get rid of it, I am using V 2.12.1 and tried multiple versions of react native and it is still not working

**Comment by renchap** [comment]
> I don't know. V2 hasn't been updated in more than half a year, we're already on V3.

Unfortunately not every app can be updated to use new architecture, for example if you are using https://github.com/react-native-maps/react-native-maps you are forced to use old arch for now.

**Comment by mrousavy** [comment]
> Unfortunately not every app can be updated to use new architecture

As harsh as it sounds, that's not my fault nor my responsibility.

Instead of me trying to provide backwards support for longer, others should move to new arch quicker.
Less work for me (I'm already way too busy with all the OSS libs I maintain), and the ecosystem moves forward, which is good.

**Comment by renchap** [comment]
Yes, I know very well the burden of being a maintainer. Thanks a lot for all you are doing!

For the other people here having this problem, can you check the value of `newArchEnabled` in your `gradle.properties` file?

I have a feeling that v2.12.1 will fail if `newArchEnabled=true`, but all will work if its disabled. Which would mean:
- if you are on the old arch, use v2.12.1 (new arch will fail)
- if you are on the new arch, use v3

**Comment by muhammadasifdotai** [comment]
**Issue**:  MMKV Compatibility with React Native New Architecture

**Project Details:**

Created using: npx @react-native-community/cli@latest init YourProjectName  
React Native Version: "react-native": "0.78.0"
MMKV Version: "react-native-mmkv": "^3.2.0"
New Architecture: Enabled (newArchEnabled=true)

**Observations:**
i. If your project uses the New Architecture, older versions of MMKV can cause issues.
ii. No need to downgrade MMKV, as the latest version (^3.2.0) is fully compatible with the New Architecture.
iii. No need to disable New Architecture (newArchEnabled=false)

**Solution:**

Simply running the following commands resolved the issue:

**For Android:**
npx react-native run-android  

**For iOS:**
npx react-native run-ios --simulator='iPhone 16 Pro'

**Comment by muhammadasifdotai** [comment]
I observed that running these commands downloads some additional dependencies that are not installed during the library installation process.

**Comment by saiyam-zepto-dev** [comment]
@mrousavy I have new Arch enabled in my gradle.properties and i am using react-native-mmkv 3.3.0
I still see this issue 
Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
* Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.

react-native : '0.78.2'
react-native-mmkv '3.3.0'

Works fine for IOS but android gives this error.

**Comment by onelittlebird** [comment]
I get this same issue when enabling the new architecture for both iOS and Android.

react-native: 0.79.5
react: 19.1.0
react-native-mmkv: 3.3.0

**Comment by felippewick** [comment]
An observation: With "react-native-mmkv": "^2.12.2" it works in iOS 17.5 simulator but not 18.2 (getting the error above)

**Comment by MOHAMED-LAAGUILI** [comment]
> [@mrousavy](https://github.com/mrousavy) I have new Arch enabled in my gradle.properties and i am using react-native-mmkv 3.3.0 I still see this issue Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
> 
> * Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
> 
> react-native : '0.78.2' react-native-mmkv '3.3.0'
> 
> Works fine for IOS but android gives this error.

same here

still struggling with it after many tries, i install the apk with smake errors

**Comment by MOHAMED-LAAGUILI** [comment]
ill try  to update mkkv to  "3.0.0-beta.5"

**Comment by jolenele** [comment]
> ill try to update mkkv to "3.0.0-beta.5"

Any updates?

**Comment by MOHAMED-LAAGUILI** [comment]
> Updated MMKV to:
> 
> ```
>  "react-native-mmkv": "3.0.0-beta.5",
> ```
> 
> and and it works now.

No i dont think so still have same arch error with mmkv instance


@renchap @mrigo @pablospaniard @mrousavy @jolenele

**Comment by MOHAMED-LAAGUILI** [comment]
@MuhammadRomanKhan717, pls could u share with me ur eas.json file and the config file if its ok

@renchap 
@mrigo 
@pablospaniard 
@mrousavy 
@jolenele
