### ISSUE TITLE
Error in setup:

### ISSUE THREAD

**Issue by youssef-devx** [mrousavy/react-native-mmkv#689]
CASE 1:

I use Expo and I followed every step in the documentation to setup **react-native-mmkv**.
Here is my code:
```
import { MMKV } from 'react-native-mmkv'

export const storage = new MMKV()
```

I get this error:

ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app., js engine: hermes

---------------------------------------------------------------------
CASE 2:

When I use this code:

```
import { MMKV } from 'react-native-mmkv'

export const storage = new MMKV({
  id: "preferences",
  path: `/storage`,
  encryptionKey: 'hunter2'
})
```
I get this error, even though I run `npx react-native config` the package is linked:

 ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app., js engine: hermes

**Comment by mrousavy** [comment]
which RN version

**Comment by youssef-devx** [comment]
The latest version 0.74.2

**Comment by mrousavy** [comment]
You need V3 beta if you are on new arch.

**Comment by rezaarifian** [comment]
same issue when running using expo
```
"react-native-mmkv": "^2.12.2",
"react-native": "0.74.3",
```
