### ISSUE TITLE
Error : TypeError: Cannot read property 'MULTI_PROCESS' of undefined

### ISSUE THREAD

**Issue by ashishmangukiya** [mrousavy/react-native-mmkv#691]
Facing issue after enabling bridgeless mode. 

    "react-native-mmkv": "3.0.0-beta.5",
    "react-native": "0.74.2",
    "react": "18.2.0",

// index.js
import { MMKV, Mode } from 'react-native-mmkv';
const storage = new MMKV({ mode: Mode.MULTI_PROCESS });
storage.set("test", "test")

Error : 
TypeError: Cannot read property 'MULTI_PROCESS' of undefined

**Comment by mrousavy** [comment]
created a fix: https://github.com/mrousavy/react-native-mmkv/pull/692
