### ISSUE TITLE
Critical Error in 0.74.* iOS

### ISSUE THREAD

**Issue by ashishmangukiya** [mrousavy/react-native-mmkv#694]
Currently using
"react-native-mmkv": "3.0.0-beta.5",
"react-native": "0.74.2",
"react": "18.2.0",

and getting error like
Invariant Violation: "MyAppName" has not been registered. This can happen if:

Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
A module failed to load due to an error and AppRegistry.registerComponent wasn't called.

working fine if I use new MMKV()
if I use like -> new MMKV({ mode: 1 }) then getting above error.

@mrousavy can you please help me ?

**Comment by ashishmangukiya** [comment]
@mrousavy  
can you please tell me like which version of the library supports the latest React-native version? 
I want to use the path and mode feature so please let me know.

**Comment by mrousavy** [comment]
Can you please stop pinging me?

That error doesn't give me any information - if there are error logs you should find them in native Xcode logs or Android Studio logcat logs.

Please post them here, then I can help you.

**Comment by mrousavy** [comment]
I don't even know where you get that from, but `mode: 1` is wrong syntax. This expects an enum, why do you pass a number here?

**Comment by ashishmangukiya** [comment]
@mrousavy  thanks for the reply.
If I use like -> new MMKV({ mode: Mode.MULTI_PROCESS })
 then getting error like 
**Error: Value is undefined, expected a String**
![simulator_screenshot_487372D7-C41C-48E3-B0C0-96ED0FAC795D](https://github.com/mrousavy/react-native-mmkv/assets/41316094/72572490-70e0-413e-b7ee-128791fe52e4)

**Comment by mrousavy** [comment]
Because `id` is missing. Please use TypeScript.

**Comment by ashishmangukiya** [comment]
@mrousavy  even after using `id`, same issue. 
Sorry for pinging you multiple times because I need to release a new version of our app.
export const storage = new MMKV({
  id: 'shared-storage',
  mode: Mode.MULTI_PROCESS,
});

` Error: Value is a number, expected a String
`

Tried consoling in /react-native-mmkv/src/createMMKV.ts
```
  const module = getMMKVTurboModule();
  console.log(config,'config')
  const instance = module.createMMKV(config);
```

and I am getting 
`{ id: 'shared-storage', mode: 1 }, 'config'
`

Screen is white (Can't see anything)

**Comment by ashishmangukiya** [comment]
Created a new app with sample react native code and installed the library with above code and getting same error. 
No issues in my existing application because it is not working in the fresh new app.

**Comment by mrousavy** [comment]
what if you pass a string like `mode: 'MULTI_PROCESS'`?

**Comment by ashishmangukiya** [comment]
@mrousavy  I passed as 
```
export const storage = new MMKV({ id: 'shared-storage', mode: 'MULTI_PROCESS' });
storage.set("test", "test");
```
No errors now and app loading without any error but MULTI_PROCESS not working 

added below details in info.plist file
```
<key>AppGroup</key>
<string>group.test.app</string>
```

And try to fetch the data (key as test) in widgets extension using below code 
Swift file 
```
 let userDefaults = UserDefaults(suiteName: "group.test.app")
 if let test = userDefaults?.string(forKey: "test") {
   print(test, "test")
  }
```
  
  test key does not exist. 
  Any configuration Am I missing here? 
  One last help I need now.
