### ISSUE TITLE
Bug on options

### ISSUE THREAD

**Issue by Zarinia** [mrousavy/react-native-mmkv#695]
I have been init  new mmkv  with these options
after restarting the app, all data lost or removed 
but without using these options all things are ok

```
id: `my-storage`, //required: if when either path/encryptionKey exist
path: `./storage`, //optional: changing storage path
encryptionKey: 'sec123#*H312fsdfdf' //optional: storing all value
// mode: Mode.MULTI_PROCESS
```

**Comment by mrousavy** [comment]
Without logs I cannot help you.

- Xcode > Log window
- Android Studio > Logcat logs
