### ISSUE TITLE
Support for App Groups in MMKV 3.0.0-beta.6

### ISSUE THREAD

**Issue by calism2** [mrousavy/react-native-mmkv#702]
Hello,

I'm currently developing an iOS share extension and I believe that the MMKV library would be a great fit for my project. MMKV's compatibility with both React Native versions and its support for app extensions make it an ideal choice. However, I noticed that although the documentation mentions support for app groups via info.plist, this feature seems to be missing in release 3.0.0-beta.6.

As someone who is not an iOS developer, I have managed to implement the basic functionality for sharing app groups. However, having this feature natively supported in MMKV would significantly simplify development and improve the overall experience.

Could you please consider adding support for app groups in the upcoming releases? Thank you.

//  MmkvHostObject.cpp
```
#ifdef __APPLE__
#include <Foundation/Foundation.h>
  NSString* appGroup = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"AppGroup"];
    if( appGroup ){
        NSString* groupDir = [[NSFileManager defaultManager]
                              containerURLForSecurityApplicationGroupIdentifier:appGroup]
            .path;
            const char* groupDirCStr = [groupDir UTF8String];
            std::string groupDirStr(groupDirCStr);
            
            instance = MMKV::mmkvWithID(config.id, mode, encryptionKeyPtr, &groupDirStr);

    }else{
        instance = MMKV::mmkvWithID(config.id, mode, encryptionKeyPtr, pathPtr);
    }
```

**Comment by mrousavy** [comment]
Hey - please create a PR and I'll gladly review & merge changes if everything works! Thanks
