### ISSUE TITLE
jsi/jsi.h file not found during build

### ISSUE THREAD

**Issue by jsdeveloperr** [mrousavy/react-native-mmkv#708]
I am encountering a build error related to the react-native-mmkv library. The error states that the file jsi/jsi.h cannot be found during the compilation process. Despite following the recommended setup instructions, I have not been able to resolve this issue.

Steps to Reproduce:

    Create a new React Native project.
    Install the react-native-mmkv library.
    Configure the project as per the documentation.
    Attempt to build the project using Xcode.

Expected Behavior:
The project should build successfully without any missing file errors.

Actual Behavior:
The build fails with the following error message:

    'jsi/jsi.h' file not found

Project Configuration:

    package.json dependencies:
    {
      "dependencies": {
        "react": "18.2.0",
        "react-native": "0.71.8",
        "react-native-mmkv": "2.12.2",
        // other dependencies...
      },
      // other configurations...
    }

Podfile configuration:

    require_relative '../node_modules/react-native/scripts/react_native_pods'
    require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
    
    platform :ios, '12.0'
    prepare_react_native_project!
    
    flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
    
    linkage = ENV['USE_FRAMEWORKS']
    if linkage != nil
      Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
      use_frameworks! :linkage => linkage.to_sym
    end
    
    target 'projectW3C' do
      config = use_native_modules!
    
      flags = get_default_flags()
    
      use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => flags[:hermes_enabled],
        :fabric_enabled => flags[:fabric_enabled],
        :flipper_configuration => flipper_config,
        :app_path => "#{Pod::Config.instance.installation_root}/.."
      )
    
      target 'projectW3CTests' do
        inherit! :complete
        # Pods for testing
      end
    end
    
    post_install do |installer|
      react_native_post_install(
        installer,
        :mac_catalyst_enabled => false
      )
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          if ['react-native-mmkv', 'React-jsi', 'RCT-Folly', 'React-cxxreact'].include?(target.name)
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) $(SRCROOT)/../node_modules/react-native/ReactCommon/jsi $(SRCROOT)/../node_modules/react-native/ReactCommon/jsi/jsi $(SRCROOT)/../node_modules/react-native/ReactCommon $(SRCROOT)/../node_modules/react-native/React $(SRCROOT)/../node_modules/react-native'
          end
        end
      end
    end

Error Log:

     The following build commands failed:
        CompileC /Users/username/Library/Developer/Xcode/DerivedData/projectW3C- 
        csgksuoqtlgoqdgtrzvpjzfhodvr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native- 
        mmkv.build/Objects-normal/x86_64/TypedArray.o /Users/username/Desktop/Mobile/node_modules/react-native- 
        mmkv/cpp/TypedArray.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-mmkv' 
        from project 'Pods')
        (1 failure)

Additional Information:

    I have tried cleaning the project and rebuilding, but the error persists.
    I verified that the jsi.h file exists in node_modules/react-native/ReactCommon/jsi/jsi.

Environment:

    React Native version: 0.71.8
    React Native MMKV version: 2.12.2
    Xcode version: 14.x
    macOS version: 12.x

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/username/Library/Developer/DerivedData/projectW3C-csgksuoqtlgoqdgtrzvpjzfhodvr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-mmkv.build/Objects-normal/x86_64/TypedArray.o  /Users/username/Desktop/Mobile/node_modules/react-native-mmkv/cpp/TypedArray.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-mmkv' from project 'Pods')
(1 failure)

<img width="248" alt="Screenshot 2024-07-28 at 23 53 46" src="https://github.com/user-attachments/assets/5d82e93a-5977-4b78-8305-b60748f976f2">

Any assistance in resolving this issue would be greatly appreciated.

**Comment by mrousavy** [comment]
You probably need at least RN 0.02 or higher

**Comment by chj-damon** [comment]
I'm using RN 0.72.5, when using xcode 16 ios sdk18 to build, it reports error like this.
