### ISSUE TITLE
Property 'size' does not exist on type 'MMKV'.ts

### ISSUE THREAD

**Issue by kaviisuru** [mrousavy/react-native-mmkv#717]
i use  "react-native-mmkv": "^2.12.2" with expo, can't acces storage.size ,it's undefined

**Comment by mrousavy** [comment]
Why do you create a new issue? I just told you in the old one, `size` is only part of V3, not V2. https://github.com/mrousavy/react-native-mmkv/issues/716

**Comment by kaviisuru** [comment]
Oh, I'm really sorry, it was my mistake. By the way, I tried to install version 3, but it defaults to installing version 2. Can you give me any instructions, please?

**Comment by kaviisuru** [comment]
"Ah, okay. I managed it by using the " npx expo install react-native-mmkv@^3" command. Thank you for clarifying!"
