### ISSUE TITLE
3.0.0 build issue with RN 0.75.2

### ISSUE THREAD

**Issue by gurbela** [mrousavy/react-native-mmkv#722]
I was built on MacOS Sonoma 14.6.1 with new architect of react native enabled.

<img width="1679" alt="Screenshot 2024-08-27 at 15 33 41" src="https://github.com/user-attachments/assets/7b11fd70-4338-488d-9689-d4c2cb66a09d">

**Comment by ZukaGap** [comment]
I have a similar problem

**Comment by enchorb** [comment]
+1

**Comment by mrousavy** [comment]
will be fixed in https://github.com/mrousavy/react-native-mmkv/pull/719. react-native made a breaking change, so I can only either support RN 0.74 or RN 0.75.

**Comment by YadBro** [comment]
+1

**Comment by mrousavy** [comment]
released in [react-native-mmkv 3.0.2](https://github.com/mrousavy/react-native-mmkv/releases/tag/v3.0.2) :rocket:

**Comment by YadBro** [comment]
thanks ❤️

**Comment by shreysaroch** [comment]
still not fixed.  
rn: 0.75.1, mmkv: 3.2.0 @mrousavy

**Comment by Satyam-code143** [comment]
hi @shreysaroch 
Even I am facing the same issue for the 
en:0.76, mmkv:3.2.0
Did you find any solution?
