### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Hatta-Food-Hub** [mrousavy/react-native-mmkv#730]
and trying to run the debug build

_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_CFG_NO_COROUTINES=1 -DFOLLY_MOBILE=1 -DFOLLY_HAVE_RECVMMSG=1 -DFOLLY_HAVE_PTHREAD=1 -DFOLLY_HAVE_XSI_STRERROR_R=1 -MD -MT CMakeFiles/appmodules.dir/Users/billion/Desktop/Hatta/HFHDriver/android/app/build/generated/rncli/src/main/jni/rncli.cpp.o -MF CMakeFiles/appmodules.dir/Users/billion/Desktop/Hatta/HFHDriver/android/app/build/generated/rncli/src/main/jni/rncli.cpp.o.d -o CMakeFiles/appmodules.dir/Users/billion/Desktop/Hatta/HFHDriver/android/app/build/generated/rncli/src/main/jni/rncli.cpp.o -c /Users/billion/Desktop/Hatta/HFHDriver/android/app/build/generated/rncli/src/main/jni/rncli.cpp
C/C++: In file included from /Users/billion/Desktop/Hatta/HFHDriver/android/app/build/generated/rncli/src/main/jni/rncli.cpp:25:
C/C++: /Users/billion/Desktop/Hatta/HFHDriver/node_modules/react-native-mmkv/android/../cpp/NativeMmkvModule.h:25:43: error: use of undeclared identifier 'NativeMmkvMode'
C/C++:                             std::optional<NativeMmkvMode>>;
C/C++:                                           ^
C/C++: /Users/billion/Desktop/Hatta/HFHDriver/node_modules/react-native-mmkv/android/../cpp/NativeMmkvModule.h:26:29: error: use of undeclared identifier 'MMKVConfig'
C/C++: template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
C/C++:                             ^
C/C++: /Users/billion/Desktop/Hatta/HFHDriver/node_modules/react-native-mmkv/android/../cpp/NativeMmkvModule.h:26:75: error: use of undeclared identifier 'MMKVConfig'
C/C++: template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
C/C++:                                                                           ^
C/C++: /Users/billion/Desktop/Hatta/HFHDriver/node_modules/react-native-mmkv/android/../cpp/NativeMmkvModule.h:35:49: error: unknown type name 'MMKVConfig'
C/C++:   jsi::Object createMMKV(jsi::Runtime& runtime, MMKVConfig config);
C/C++:                                                 ^
C/C++: 4 errors generated.

> Task :app:buildCMakeDebug[arm64-v8a] FAILED

**Comment by Hatta-Food-Hub** [comment]
> Guten Tag, Hans here! 🥨
> 
> Thanks for your support by sponsoring react-native-mmkv! It looks like you're running into a build error related to some undeclared identifiers in the C++ files.
> 
> Could you provide more context on your environment? Please include details such as your react-native-mmkv version, the version of React Native you're using, and any other relevant dependencies. Also, if you could share the full build logs, that would help us diagnose ze issue much better!
> 
> Looking forward to your response! 🍻
> 
> > Note: If you think I made a mistake, please ping `@mrousavy` to take a look.

Guten Tag,

this is my info

System:
  OS: macOS 14.6.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 843.67 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.13.1
    path: ~/.nvm/versions/node/v20.13.1/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.13.1/bin/yarn
  npm:
    version: 10.5.2
    path: ~/.nvm/versions/node/v20.13.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "25"
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "33"
      - "33"
      - "34"
      - "34"
      - "34"
    Build Tools:
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 33.0.3
      - 34.0.0
      - 35.0.0
      - 35.0.0
      - 35.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
      - android-VanillaIceCream | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by Hatta-Food-Hub** [comment]
dependencies

 "react": "18.2.0",
    "react-native": "0.74.3",
     "react-native-mmkv": "^3.0.2",
     
     "@react-navigation/bottom-tabs": "^6.6.0",
    "@react-navigation/drawer": "^6.7.1",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.10.0",

**Comment by Hatta-Food-Hub** [comment]
After @mrousavy has suggested moving from beta to this latest release this issue is coming it was earlier as well

**Comment by 321paranoiawhy** [comment]
Same error, I re-codegen, but it did not help, can anyone solve this? Info may be valuable:

- `react-native`: `0.74.2`
- `react-native-mmkv`: `^3.0.2`
- development platform: `macOS`
- target platform: `android`

The error are:

- `error: use of undeclared identifier 'NativeMmkvMode'`
- `error: use of undeclared identifier 'MMKVConfig'`
- `error: unknown type name 'MMKVConfig'`

**Comment by 321paranoiawhy** [comment]
> Same error, I re-codegen, but it did not help, can anyone solve this? Info may be valuable:
> 
> * `react-native`: `0.74.2`
> * `react-native-mmkv`: `^3.0.2`
> * development platform: `macOS`
> * target platform: `android`
> 
> The errors are:
> 
> * `error: use of undeclared identifier 'NativeMmkvMode'`
> * `error: use of undeclared identifier 'MMKVConfig'`
> * `error: unknown type name 'MMKVConfig'`

After downgrade `react-native-mmkv` to `3.0.1`, the errors disappear, hope this can help others.

**Comment by mrousavy** [comment]
I mentioned that in the release notes. 3.0.2 requires RN 75, 3.0.1 requires RN 74.

**Comment by waqarAllshore** [comment]
same issue here

**Comment by VladyslavKochetkov** [comment]
> I mentioned that in the release notes. 3.0.2 requires RN 75, 3.0.1 requires RN 74.

I feel like that should be more than just a patch upgrade

**Comment by WKampel** [comment]
Same issue

**Comment by devGuerra** [comment]
same here
