### ISSUE TITLE
Reloading expo app throws Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules

### ISSUE THREAD

**Issue by davidchieregato** [mrousavy/react-native-mmkv#733]
I am using Expo 51 with react-native 0.75.2 and react-native-mmkv 3.0.2

Only after the app reload pressing 'r' the below error appears, but the new architecture is clearly enabled

```
› Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundled 3940ms node_modules/expo-router/entry.js (1238 modules)
[micarenewapp] [RNMMKV]: Initializing MMKV at
/Users/David_Chieregato/Library/Developer/CoreSimulator/Devices/3D08537D-7C9C-451B-B129-0759E669A147/data/Containers/Data/Application/78861F6A-A8CD-40E1-94CC-5D1BC57D70A3/Documents/mmkv...
[micarenewapp] [RNMMKV]: Creating MMKV instance "mmkv.default"... (Path: , Encrypted: false)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
› Reloading apps
[micarenewapp] [RNMMKV]: Destroying MMKV instance "mmkv.default"...
iOS Bundled 54ms node_modules/expo-router/entry.js (1 module)
iOS Bundled 51ms node_modules/expo-router/entry.js (1 module)
[micarenewapp] [RNMMKV]: Initializing MMKV at
/Users/David_Chieregato/Library/Developer/CoreSimulator/Devices/3D08537D-7C9C-451B-B129-0759E669A147/data/Containers/Data/Application/78861F6A-A8CD-40E1-94CC-5D1BC57D70A3/Documents/mmkv...
[micarenewapp] [RNMMKV]: Creating MMKV instance "mmkv.default"... (Path: , Encrypted: false)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 ERROR  Warning: Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
* Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
* Enable the new architecture in your app to use react-native-mmkv 3.x.x. (See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md), js engine: hermes 
    at ContextNavigator (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:173256:24)
    at ExpoRoot (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:173228:28)
    at App
    at ErrorToastContainer (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:195061:24)
    at ErrorOverlay
    at withDevTools(ErrorOverlay) (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:191290:27)
    at RCTView
    at View (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:62656:43)
    at CssInterop.View (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11073:45)
    at RCTView
    at View (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:62656:43)
    at CssInterop.View (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:11073:45)
    at AppContainer (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:81038:25)
    at main(RootComponent) (http://xx.xx.xx.xx:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app:92535:28)
```

**Comment by amutsch** [comment]
Hi @davidchieregato 

It does not look like you have new architecture enabled.  Bridgeless mode comes from the switch from yoga to Yoga 3 in RN 74.  New architecture still requires toggling a change in your gradle.properties and a little more to enable it in IOS and the log message will then indicate fabric being enabled which I don't see.

Thanks

**Comment by davidchieregato** [comment]
So this is interesting, 

In my app.json I have newArchEnabled

```
"plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true
          }
        }
      ]
    ]
```

I just checked also the android gradle.properties which includes `newArchEnabled=true`

But the log still shows 
```
 (NOBRIDGE) LOG  Bridgeless mode is enabled
```
Both on iOS and android. 
So probably the problem is not in this library as my logs are not showing `"fabric": true`. Not sure what the issue may be.

**Comment by amutsch** [comment]
I'll have to see if I have time to update mmkv and react native to see what is going on, I'll try and get back to you this week.

**Comment by mrousavy** [comment]
Does it work if you delete those two lines? https://github.com/mrousavy/react-native-mmkv/blob/12c051704e0db363f9f63d2b30dbf291151f90d4/package/cpp/MmkvHostObject.cpp#L56-L57

**Comment by mrousavy** [comment]
>  (NOBRIDGE) LOG  Bridgeless mode is enabled

This means you are on new arch, so it should be fine.

**Comment by davidchieregato** [comment]
It seems that deleting the android and ios folders fixed the issue today, probably it was not related to the library. Closing this.

**Comment by victorpavlenko** [comment]
Same issue for my android build.

```
"plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true
          }
        }
      ]
]
```

Same 

> (NOBRIDGE) LOG Bridgeless mode is enabled

But in my case prebuild clear doesnt help

**Comment by hapo-nghialuu** [comment]
> Does it work if you delete those two lines?

Same
I deleted android, ios folder but still encounter this error

**Comment by kasim-shaikh1** [comment]
"expo": "~53.0.9", "react-native": "0.79.2","react-native-mmkv": "^3.2.0",
getting same error when running on expo go

**Comment by Knitesh026** [comment]
i have enable newArch in app.json -     "newArchEnabled": true,
 and gradle.properties - newArchEnabled=true
 but still getiing error " ERROR  Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
* Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
* Enable the new architecture in your app to use react-native-mmkv 3.x.x. (See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md), js engine: hermes"   


**

![Image](https://github.com/user-attachments/assets/b9aad464-aba5-44df-93ea-ef035b96d410)

**

**Comment by kasim-shaikh1** [comment]
> i have enable newArch in app.json - "newArchEnabled": true, and gradle.properties - newArchEnabled=true but still getiing error " ERROR Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
> 
> * Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
> * Enable the new architecture in your app to use react-native-mmkv 3.x.x. (See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md), js engine: hermes"
> 
> **
> 
> ![Image](https://github.com/user-attachments/assets/b9aad464-aba5-44df-93ea-ef035b96d410)
> 
> **

add this in your app.json
"experiments": {
      "turboModules": true
    },
delete android folder , rebuild with clear. also try to use your physical phone.

**Comment by neo7-studio-web** [comment]
If it can help...

I had the exact same problem with Expo 53 (new arch), react-native 0.79, react-native-mmkv 3.3.0
I added react-native-mmkv as a Wrapper for Apollo client persist cache
`ERROR Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!`

I made a new development build (with expo EAS) and it worked.

**Comment by codiku-dev** [comment]
Expo 53.0.11 , RN 0.79.3 => Still same error while definitely using the new architecture.

**Comment by mrakus-sofomo** [comment]
> Expo 53.0.11 , RN 0.79.3 => Still same error while definitely using the new architecture.

The same on my side

**Comment by alexclinky** [comment]
This has fixed my problem (make sure new arch is enabled)

```npx expo prebuild --clean```

```npx exp run:ios```

**Comment by mkilincaslan** [comment]
Same issue in my app too, I need help!!

Error message;
```
Error: Failed to create a new MMKV instance: react-native-mmkv 3.x.x requires TurboModules, but the new architecture is not enabled!
* Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
* Enable the new architecture in your app to use react-native-mmkv 3.x.x. (See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md), js engine: hermes
```

```
app.json
{
  "expo": {
    "name": "myapp",
    "slug": "myapp",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "newArchEnabled": true,
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.myapp"
    },
    "web": {
      "bundler": "metro",
      "output": "single",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      "expo-font",
      [
        "expo-build-properties",
        {
          "android": {
            "newArchEnabled": true
          },
          "ios": {
            "newArchEnabled": true
          }
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true,
      "turboModules": true
    },
    "android": {
      "package": "com.myapp"
    }
  }
}
````

```
package.json
{
  "name": "myapp",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "EXPO_NO_TELEMETRY=1 expo start",
    "build:web": "expo export --platform web",
    "lint": "expo lint",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "prebuild:clean": "expo prebuild --clean"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo/vector-icons": "^14.1.0",
    "@lucide/lab": "^0.1.2",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@tanstack/react-query": "^5.83.0",
    "axios": "^1.10.0",
    "expo": "^53.0.0",
    "expo-blur": "~14.1.4",
    "expo-build-properties": "~0.14.8",
    "expo-camera": "~16.1.6",
    "expo-constants": "~17.1.6",
    "expo-dev-client": "~5.2.4",
    "expo-font": "~13.3.1",
    "expo-haptics": "~14.1.4",
    "expo-linear-gradient": "~14.1.4",
    "expo-linking": "~7.1.4",
    "expo-router": "~5.0.6",
    "expo-splash-screen": "~0.30.8",
    "expo-status-bar": "~2.2.3",
    "expo-symbols": "~0.4.3",
    "expo-system-ui": "~5.0.7",
    "lucide-react-native": "^0.475.0",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.2",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-mmkv": "^3.3.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.10.0",
    "react-native-svg": "15.11.2",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "^0.20.0",
    "react-native-webview": "13.13.5",
    "styled-components": "^6.1.18",
    "zustand": "^5.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~19.0.10",
    "@types/styled-components": "^5.1.34",
    "@types/styled-components-react-native": "^5.2.5",
    "typescript": "^5.3.0"
  }
}

```

**Comment by saiyam-zepto-dev** [comment]
Same issue

**Comment by mkilincaslan** [comment]
I found the reason of the error on my end, if anybody who has the same issue should follow this.

## The Problem with Expo Go and New Architecture
**Expo Go** does NOT support the New Architecture (TurboModules/Fabric). Here's why:

**Expo Go** limitations: Expo Go is a pre-built app that runs on the old React Native architecture and cannot use native modules that require the New Architecture.

MMKV 3.x.x requirement: react-native-mmkv 3.x.x specifically requires TurboModules, which are only available with the New Architecture.

Configuration mismatch: Even though you have newArchEnabled: true in your [app.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) and Android gradle.properties, this setting only takes effect when you build a development build or production build, not when using Expo Go.

### Solutions
You have 3 options:

Option 1: Use Development Build (Recommended)
Create a custom development build that includes the New Architecture

Option 2: Downgrade MMKV to 2.x.x (Quick Fix)
Downgrade to MMKV 2.x.x which works with both architectures and Expo Go

Option 3: Use Alternative Storage (Temporary)
Use `@react-native-async-storage/async-storage` which works with Expo Go

Recommendation
Since you're building a production app with authentication and want to use modern React Native features, I recommend Option 1 - using development builds. This allows you to:

✅ Use the New Architecture and all its benefits
✅ Keep MMKV 3.x.x for better performance
✅ Test exactly what your users will get in production
✅ Use any native modules you need

This is how I found out while I was pair programming with co-pilot. Hope it works for everyone who has troubles. Good luck!

**Comment by vanishcode** [comment]
In my case, it was a name conflict caused this problem 😅
before:
`const Storage = new MMKV()`
after:
`const storage = new MMKV()`

**Comment by MOHAMED-LAAGUILI** [comment]
still getting error 
MMKV 3.x.x requirement: react-native-mmkv 3.x.x specifically requires TurboModules, which are only available with the New Architecture.

<img width="271" height="637" alt="Image" src="https://github.com/user-attachments/assets/4242f8fd-c6ef-4795-835b-c932b88846b3" />

# app.config.json
`
import type { ConfigContext, ExpoConfig } from '@expo/config';
import type { AppIconBadgeConfig } from 'app-icon-badge/types';

import { ClientEnv, Env } from './env';

const appIconBadgeConfig: AppIconBadgeConfig = {
  enabled: Env.APP_ENV !== 'production',
  badges: [
    {
      text: Env.APP_ENV,
      type: 'banner',
      color: 'white',
    },
    {
      text: Env.VERSION.toString(),
      type: 'ribbon',
      color: 'white',
    },
  ],
};

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: Env.NAME,
  description: `${Env.NAME} Mobile App`,
  owner: Env.EXPO_ACCOUNT_OWNER,
  scheme: Env.SCHEME,
  slug: Env.SLUG,
  version: Env.VERSION.toString(),
  orientation: 'portrait',
  icon: './assets/icon-new.png',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
   experiments: {
    typedRoutes: true,
    turboModules: true,
  },
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ['**/*'],
  ios: {
    supportsTablet: true,
    bundleIdentifier: Env.BUNDLE_ID,
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon-new.png',
      backgroundColor: '#FFFFFF',
    },
    package: Env.PACKAGE,
  },
  web: {
    favicon: './assets/favicon-new.png',
    bundler: 'metro',
  },
  plugins: [
     [
        "expo-build-properties",
        {
          android: {
            newArchEnabled: true
          },
          ios: {
            newArchEnabled: true
          }
        }
      ],
    [
      'expo-splash-screen',
      {
        backgroundColor: '#FFFFFF',
        image: './assets/splash-icon-new.png',
        imageWidth: 150,
      },
    ],
    [
      'expo-font',
      {
        fonts: ['./assets/fonts/Inter.ttf'],
      },
    ],
    'expo-localization',
    'expo-router',
    ['app-icon-badge', appIconBadgeConfig],
    ['react-native-edge-to-edge'],
  ],
  extra: {
    ...ClientEnv,
    eas: {
      projectId: Env.EAS_PROJECT_ID,
    },
  },

});
`

# package.json
`
{
  "name": "timetracker",
  "version": "1.0.0",
  "private": true,
  "packageManager": "pnpm@10.12.3",
  "main": "expo-router/entry",
  "scripts": {
    "start": "cross-env EXPO_NO_DOTENV=1 expo start",
    "prebuild": "cross-env EXPO_NO_DOTENV=1 pnpm expo prebuild",
    "android": "cross-env EXPO_NO_DOTENV=1 expo run:android",
    "ios": "cross-env EXPO_NO_DOTENV=1 expo run:ios",
    "web": "cross-env EXPO_NO_DOTENV=1 expo start --web",
    "xcode": "xed -b ios",
    "doctor": "npx expo-doctor@latest",
    "preinstall": "npx only-allow pnpm",
    "start:staging": "cross-env APP_ENV=staging pnpm run start",
    "prebuild:staging": "cross-env APP_ENV=staging pnpm run prebuild",
    "prebuild:development": "cross-env APP_ENV=development pnpm run prebuild",
    "android:staging": "cross-env APP_ENV=staging pnpm run android",
    "ios:staging": "cross-env APP_ENV=staging pnpm run ios",
    "start:production": "cross-env APP_ENV=production pnpm run start",
    "prebuild:production": "cross-env APP_ENV=production pnpm run prebuild",
    "android:production": "cross-env APP_ENV=production pnpm run android",
    "ios:production": "cross-env APP_ENV=production pnpm run ios",
    "build:development:ios": "cross-env APP_ENV=development EXPO_NO_DOTENV=1 eas build --profile development --platform ios",
    "build:development:android": "cross-env APP_ENV=development EXPO_NO_DOTENV=1 eas build --profile development --platform android--clear-cache",
    "build:staging:ios": "cross-env APP_ENV=staging EXPO_NO_DOTENV=1 eas build --profile staging --platform ios",
    "build:staging:android": "cross-env APP_ENV=staging EXPO_NO_DOTENV=1 eas build --profile staging --platform android ",
    "build:production:ios": "cross-env APP_ENV=production EXPO_NO_DOTENV=1 eas build --profile production --platform ios",
    "build:production:android": "cross-env APP_ENV=production EXPO_NO_DOTENV=1 eas build --profile production --platform android --clear-cache",
    "prepare": "husky",
    "app-release": "cross-env SKIP_BRANCH_PROTECTION=true np --no-publish --no-cleanup --no-release-draft",
    "version": "pnpm run prebuild && git add .",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "type-check": "tsc  --noemit",
    "lint:translations": "eslint ./src/translations/ --fix --ext .json  ",
    "test": "jest",
    "check-all": "pnpm run lint && pnpm run type-check && pnpm run lint:translations && pnpm run test",
    "test:ci": "pnpm run test --coverage",
    "test:watch": "pnpm run test --watch",
    "install-maestro": "curl -Ls 'https://get.maestro.mobile.dev' | bash",
    "e2e-test": "maestro test .maestro/ -e APP_ID=com.obytes.development"
  },
  "browser": {
    "better-sqlite3": false,
    "@nozbe/watermelondb/adapters/sqlite": false
  },
  "lint-staged": {
    "package.json": [
      "pnpm install --lockfile-only",
      "git add pnpm-lock.yaml"
    ],
    "pnpm-lock.yaml": [
      "git add pnpm-lock.yaml"
    ]
  },
  "dependencies": {
    "@expo/metro-runtime": "^5.0.4",
    "@expo/next-adapter": "^6.0.0",
    "@gorhom/bottom-sheet": "^5.0.5",
    "@hookform/resolvers": "^3.9.0",
    "@nozbe/watermelondb": "^0.28.0",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/netinfo": "11.4.1",
    "@react-navigation/drawer": "^7.3.9",
    "@react-navigation/native": "^7.1.6",
    "@shopify/flash-list": "1.7.6",
    "@shopify/react-native-skia": "2.0.0-next.4",
    "@tanstack/react-query": "^5.85.5",
    "@tanstack/react-table": "^8.21.3",
    "@wuba/react-native-echarts": "1.1.1-alpha.1",
    "app-icon-badge": "^0.1.2",
    "axios": "^1.7.5",
    "better-sqlite3": "^12.2.0",
    "clsx": "^2.1.1",
    "expo": "53.0.23",
    "expo-build-properties": "^1.0.9",
    "expo-constants": "~17.1.6",
    "expo-crypto": "^14.1.5",
    "expo-dev-client": "~5.2.4",
    "expo-font": "~13.3.1",
    "expo-image": "~2.4.0",
    "expo-linear-gradient": "~14.1.5",
    "expo-linking": "~7.1.7",
    "expo-localization": "~16.1.6",
    "expo-router": "~5.1.6",
    "expo-splash-screen": "~0.30.10",
    "expo-sqlite": "^15.2.14",
    "expo-status-bar": "~2.2.3",
    "expo-system-ui": "~5.0.11",
    "expo-updates": "^0.28.17",
    "i18next": "^23.14.0",
    "lodash.memoize": "^4.1.2",
    "lottie-react-native": "7.2.2",
    "lucide-react-native": "^0.541.0",
    "moti": "^0.29.0",
    "nativewind": "^4.1.23",
    "next": "^15.5.0",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-error-boundary": "^4.0.13",
    "react-hook-form": "^7.53.0",
    "react-i18next": "^15.0.1",
    "react-icons": "^5.5.0",
    "react-native": "0.79.5",
    "react-native-chart-kit": "^6.12.0",
    "react-native-datatable-component": "^2.1.14",
    "react-native-edge-to-edge": "1.6.0",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-gifted-charts": "^1.4.64",
    "react-native-keyboard-controller": "^1.17.4",
    "react-native-mmkv": "^3.3.3",
    "react-native-paper": "^5.14.5",
    "react-native-reanimated": "~3.17.5",
    "react-native-reanimated-table": "^0.0.2",
    "react-native-restart": "0.0.27",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-table-component": "^1.2.2",
    "react-native-tableview-simple": "^4.4.1",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.20.0",
    "react-query": "^3.39.3",
    "react-query-kit": "^3.3.0",
    "tailwind-rn": "^4.2.0",
    "tailwind-variants": "^0.2.1",
    "uuid": "^13.0.0",
    "zod": "^3.23.8",
    "zustand": "^5.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.26.0",
    "@babel/helper-validator-identifier": "^7.27.1",
    "@commitlint/cli": "^19.2.2",
    "@commitlint/config-conventional": "^19.2.2",
    "@dev-plugins/react-query": "^0.0.7",
    "@eslint/eslintrc": "^3.3.1",
    "@eslint/js": "^9.28.0",
    "@expo/config": "~11.0.10",
    "@react-native-community/cli": "^20.0.2",
    "@testing-library/jest-dom": "^6.5.0",
    "@testing-library/react-native": "^12.7.2",
    "@types/i18n-js": "^3.8.9",
    "@types/invariant": "^2.2.37",
    "@types/jest": "^29.5.12",
    "@types/lodash.memoize": "^4.1.9",
    "@types/react": "~19.0.14",
    "@typescript-eslint/eslint-plugin": "^8.34.0",
    "@typescript-eslint/parser": "^8.34.0",
    "babel-plugin-module-resolver": "^5.0.2",
    "cross-env": "^7.0.3",
    "dotenv": "^16.4.5",
    "eslint": "^9.28.0",
    "eslint-config-expo": "^9.2.0",
    "eslint-config-prettier": "^10.1.5",
    "eslint-import-resolver-typescript": "^4.4.3",
    "eslint-plugin-i18n-json": "^4.0.1",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-prettier": "^5.4.1",
    "eslint-plugin-react-compiler": "19.1.0-rc.2",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "eslint-plugin-tailwindcss": "^3.18.0",
    "eslint-plugin-testing-library": "^7.5.2",
    "eslint-plugin-unicorn": "^59.0.1",
    "eslint-plugin-unused-imports": "^4.1.4",
    "husky": "^9.1.5",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-expo": "~53.0.10",
    "jest-junit": "^16.0.0",
    "lint-staged": "^15.2.9",
    "np": "^10.0.7",
    "prettier": "^3.3.3",
    "tailwindcss": "3.4.4",
    "ts-jest": "^29.1.2",
    "typescript": "~5.8.3",
    "typescript-eslint": "^8.34.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/user/repo-name.git"
  },
  "expo": {
    "doctor": {
      "reactNativeDirectoryCheck": {
        "listUnknownPackages": false,
        "exclude": [
          "react-native-restart",
          "@nozbe/watermelondb",
          "react-native-chart-kit",
          "react-native-table-component"
        ]
      }
    },
    "install": {
      "exclude": [
        "eslint-config-expo"
      ]
    }
  },
  "osMetadata": {
    "initVersion": "8.0.0"
  }
}

`
