### ISSUE TITLE
Couldn't connect firebase with mmkv

### ISSUE THREAD

**Issue by waqaramjad** [mrousavy/react-native-mmkv#734]
I have a project in which mmkv is already setup and now i want to add firebase for push notifications the issue is that firebase dosn't allow flipper and mmkv can't work without flipper as its required on debugging what's the solution for this?

**Comment by mrousavy** [comment]
you can use flipper.

**Comment by waqaramjad** [comment]
@mrousavy Issue is that I can't use flipper with firebase as per their documentation and mmkv not work without flipper, what's the solutions for this to work?
