### ISSUE TITLE
Compilation Error with React Native MMKV: NativeMmkvPlatformContextSpec Not Found

### ISSUE THREAD

**Issue by waqarkhan09099** [mrousavy/react-native-mmkv#735]
I encountered an error while trying to build the project with react-native-mmkv. The build fails with compilation errors indicating that the NativeMmkvPlatformContextSpec class and other symbols cannot be found.

React Native Version 0.74

Execution failed for task ':react-native-mmkv:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

[...error details...]

![image](https://github.com/user-attachments/assets/8dbff096-b73f-4593-9ac8-3cecb783fe29)

![image](https://github.com/user-attachments/assets/317d61ad-321f-4068-8ad8-089a32412327)

Please advise on any known issues or potential fixes. If this is a bug, I would appreciate guidance on how to resolve it or a potential timeline for a fix.

**Comment by amutsch** [comment]
Looks like you are using a 3.x version of this library.  What version exactly are you using.  Do you have new architecture enabled for react-native?

**Comment by waqarkhan09099** [comment]
![image](https://github.com/user-attachments/assets/ea094eef-ab8e-41cf-85ae-9e7ba18fda17)

> Looks like you are using a 3.x version of this library. What version exactly are you using. Do you have new architecture enabled for react-native?
![image](https://github.com/user-attachments/assets/11414510-7af7-4b0a-919a-2815cc9124d6)

**Comment by waqarkhan09099** [comment]
Can I replace it with a version lower than 3.x?

**Comment by amutsch** [comment]
@waqarkhan09099 If you do not have new architecture enabled you should be using 2.x latest, if using new architecture I know for a fact the last 3.x beta was working good with RN 74 as I was using that personally.

**Comment by amutsch** [comment]
I was working on my local upgrade today, I did find 3.0.2 did not work with RN 74.x I stuck to the beta for that and then went to 3.0.2 with my upgrade to RN 75.  I have validated building on Windows for android, I will validate my Mac builds and Ios builds when I get back on Sunday

**Comment by danishhusain** [comment]
![Screenshot 2024-09-06 110707](https://github.com/user-attachments/assets/345c35e1-3bba-4f1f-8139-55b1bd4cee6b)

@waqarkhan09099 You can use "react-native-mmkv": "^2.12.2" this version of library in current  "react-native": "0.75.2" version project. Its working fine for me. Date:- 09/06/2024

> I encountered an error while trying to build the project with react-native-mmkv. The build fails with compilation errors indicating that the NativeMmkvPlatformContextSpec class and other symbols cannot be found.
> 
> React Native Version 0.74
> 
> Execution failed for task ':react-native-mmkv:compileDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> [...error details...]
> 
> ![image](https://private-user-images.githubusercontent.com/63258252/364875132-8dbff096-b73f-4593-9ac8-3cecb783fe29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDA4NDUsIm5iZiI6MTcyNTYwMDU0NSwicGF0aCI6Ii82MzI1ODI1Mi8zNjQ4NzUxMzItOGRiZmYwOTYtYjczZi00NTkzLTlhYzgtM2NlY2I3ODNmZTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjI3ZWYxYzZjMThkNjUxNTYxODcyODY2MGNjODU2ODk4ODgwNzJkMWE5NmViNWFjMjgzZWVhY2UyZWQ5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KvZZe_t_bu089qs7h3FzUVdP3XJbFiQJ6Pl_wVWMpBI)
> 
> ![image](https://private-user-images.githubusercontent.com/63258252/364875281-317d61ad-321f-4068-8ad8-089a32412327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDA4NDUsIm5iZiI6MTcyNTYwMDU0NSwicGF0aCI6Ii82MzI1ODI1Mi8zNjQ4NzUyODEtMzE3ZDYxYWQtMzIxZi00MDY4LThhZDgtMDg5YTMyNDEyMzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzQzZDk2Y2Y4OTBmZTc5NzIzNWFkZWZlMDUyNWY3ZDA2NWQzMjkxMzJjYTdjNjA3N2Y4YmU3ZWQ4YTA1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zAMl16Bfe9gilZjse_EQdWrE6vdnjSY0QsuoSzfDHWQ)
> 
> Please advise on any known issues or potential fixes. If this is a bug, I would appreciate guidance on how to resolve it or a potential timeline for a fix.


@waqarkhan09099 You can use "react-native-mmkv": "^2.12.2" this version of library in current  "react-native": "0.75.2" version project. Its working fine for me. Date:- 09/06/2024
![Screenshot 2024-09-06 110707](https://github.com/user-attachments/assets/64fe4f9a-879d-4625-a0a8-ef6ed1c58f3c)

**Comment by waqarkhan09099** [comment]
> ![Screenshot 2024-09-06 110707](https://private-user-images.githubusercontent.com/46295253/365045987-345c35e1-3bba-4f1f-8139-55b1bd4cee6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDk2MDksIm5iZiI6MTcyNTY0OTMwOSwicGF0aCI6Ii80NjI5NTI1My8zNjUwNDU5ODctMzQ1YzM1ZTEtM2JiYS00ZjFmLTgxMzktNTViMWJkNGNlZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE5MDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTI3NjU5NTQxMTVhYjM2NTU5MjJkNDc1YzU2MmMwZTVhM2RkYWI2MTdmYTkwODY5NWMzMDQ5YTliMjRlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.86DhL_VgnOiBSwVpFYKsEV6N25sHjnUmHIlO69UHjNc)
> 
> @waqarkhan09099 You can use "react-native-mmkv": "^2.12.2" this version of library in current "react-native": "0.75.2" version project. Its working fine for me. Date:- 09/06/2024
> 
> > I encountered an error while trying to build the project with react-native-mmkv. The build fails with compilation errors indicating that the NativeMmkvPlatformContextSpec class and other symbols cannot be found.
> > React Native Version 0.74
> > Execution failed for task ':react-native-mmkv:compileDebugJavaWithJavac'.
> > > Compilation failed; see the compiler error output for details.
> > 
> > 
> > [...error details...]
> > ![image](https://private-user-images.githubusercontent.com/63258252/364875132-8dbff096-b73f-4593-9ac8-3cecb783fe29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDA4NDUsIm5iZiI6MTcyNTYwMDU0NSwicGF0aCI6Ii82MzI1ODI1Mi8zNjQ4NzUxMzItOGRiZmYwOTYtYjczZi00NTkzLTlhYzgtM2NlY2I3ODNmZTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjI3ZWYxYzZjMThkNjUxNTYxODcyODY2MGNjODU2ODk4ODgwNzJkMWE5NmViNWFjMjgzZWVhY2UyZWQ5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KvZZe_t_bu089qs7h3FzUVdP3XJbFiQJ6Pl_wVWMpBI)
> > ![image](https://private-user-images.githubusercontent.com/63258252/364875281-317d61ad-321f-4068-8ad8-089a32412327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDA4NDUsIm5iZiI6MTcyNTYwMDU0NSwicGF0aCI6Ii82MzI1ODI1Mi8zNjQ4NzUyODEtMzE3ZDYxYWQtMzIxZi00MDY4LThhZDgtMDg5YTMyNDEyMzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzQzZDk2Y2Y4OTBmZTc5NzIzNWFkZWZlMDUyNWY3ZDA2NWQzMjkxMzJjYTdjNjA3N2Y4YmU3ZWQ4YTA1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zAMl16Bfe9gilZjse_EQdWrE6vdnjSY0QsuoSzfDHWQ)
> > Please advise on any known issues or potential fixes. If this is a bug, I would appreciate guidance on how to resolve it or a potential timeline for a fix.
> 
> @waqarkhan09099 You can use "react-native-mmkv": "^2.12.2" this version of library in current "react-native": "0.75.2" version project. Its working fine for me. Date:- 09/06/2024 ![Screenshot 2024-09-06 110707](https://private-user-images.githubusercontent.com/46295253/365046640-64fe4f9a-879d-4625-a0a8-ef6ed1c58f3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDk2MDksIm5iZiI6MTcyNTY0OTMwOSwicGF0aCI6Ii80NjI5NTI1My8zNjUwNDY2NDAtNjRmZTRmOWEtODc5ZC00NjI1LWEwYTgtZWY2ZWQxYzU4ZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE5MDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YTE2OGY4NmVkNTZiMzdjOGUyMDc5ZTM0YmI0NzdkMzdmY2NjZjc3M2RmMzEwNjM3NDYzZDlmNzE4NWQzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bhO-GnQRPg_clzqk5TIp1pluf6pyzUKfFot_u84VoC8)

Thanks for your assistance. That version works for me.
However, I suggest that the react-native-mmkv latest version be compatible with the react native version 0.70.x till lastest 

### Warning Description After Run Android :
While building the `react-native-mmkv` library, the following warning is displayed in the logs:
node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:1625:29: warning: 'const' qualifier on reference type 'MMKVKey_t' (aka 'const basic_string<char> &') has no effect [-Wignored-reference-qualifiers] auto packKeyValue = [&](const MMKVKey_t &key, const MMBuffer &value) {

**Proposed Fix:**
Removing the `const` qualifier from the reference type `MMKVKey_t &key` will resolve the warning.

**Comment by amutsch** [comment]
@waqarkhan09099 In this case v2 is old architecture, v3 is new architecture, complete re-write for the most part for @mrousavy
