### ISSUE TITLE
Android Build Crashes with 3.0.2 Please Fix

### ISSUE THREAD

**Issue by Ritik5Prasad** [mrousavy/react-native-mmkv#736]
Dear Team,
I really like this library for storage but with the new version im getting this compilation error from android side 

"dependencies": {
    "react": "18.3.1",
    "react-native": "0.75.2",
    "react-native-mmkv": "^3.0.2"
  },

`
info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:7: error: cannot find symbol
public class MmkvPlatformContextModule extends NativeMmkvPlatformContextSpec {
                                               ^
  symbol: class NativeMmkvPlatformContextSpec
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:15: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:21: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:19: error: cannot find symbol
    if (name.equals(MmkvPlatformContextModule.NAME)) {
                                             ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:20: error: incompatible types: MmkvPlatformContextModule cannot be converted to NativeModule
      return new MmkvPlatformContextModule(reactContext);
             ^
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:31: error: cannot find symbol
              MmkvPlatformContextModule.NAME,
                                       ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:33: error: cannot find symbol
                      MmkvPlatformContextModule.NAME,
                                               ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
/Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:34: error: cannot find symbol
                      MmkvPlatformContextModule.NAME,
                                               ^
  symbol:   variable NAME
  location: class MmkvPlatformContextModule
Note: /Users/ritikprasad/Desktop/hotel_guest/node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.`

**Comment by dev-whoan** [comment]
Hello, Did you solve this problem?

**Comment by phvasconcellos84** [comment]
Same here. I'm about to downgrade React Native version...

**Comment by catarinadasilva** [comment]
I've the same issue with distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip

**Comment by amutsch** [comment]
RN 75.2 recommends gradle 8.8 but that likely isn't the problem, whenever I upgrade an RN version I usually make sure to manually clear the build directories in android, I did multiple upgrades to verify versions and integrations between RN and mmkv last night

**Comment by catarinadasilva** [comment]
> RN 75.2 recommends gradle 8.8 but that likely isn't the problem, whenever I upgrade an RN version I usually make sure to manually clear the build directories in android, I did multiple upgrades to verify versions and integrations between RN and mmkv last night

Thanks for the tip, however, the issue is not that, it seems that is missing the class NativeMmkvPlatformContextSpec in version 3.0.2 and that causes the build crash:
```
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:7: error: cannot find symbol
public class MmkvPlatformContextModule extends NativeMmkvPlatformContextSpec { ^ symbol: class NativeMmkvPlatformContextSpec
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:15: error: method does not override or implement a method from a supertype @Override ^
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:21: error: method does not override or implement a method from a supertype @Override ^
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:19: error: cannot find symbol if (name.equals(MmkvPlatformContextModule.NAME)) { ^ symbol: variable NAME location: class MmkvPlatformContextModule
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:20: error: incompatible types: MmkvPlatformContextModule cannot be converted to NativeModule return new MmkvPlatformContextModule(reactContext); ^
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:31: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:33: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule
.../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:34: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule

```

**Comment by amutsch** [comment]
> > RN 75.2 recommends gradle 8.8 but that likely isn't the problem, whenever I upgrade an RN version I usually make sure to manually clear the build directories in android, I did multiple upgrades to verify versions and integrations between RN and mmkv last night
> 
> Thanks for the tip, however, the issue is not that, it seems that is missing the class NativeMmkvPlatformContextSpec in version 3.0.2 and that causes the build crash:
> 
> ```
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:7: error: cannot find symbol
> public class MmkvPlatformContextModule extends NativeMmkvPlatformContextSpec { ^ symbol: class NativeMmkvPlatformContextSpec
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:15: error: method does not override or implement a method from a supertype @Override ^
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java:21: error: method does not override or implement a method from a supertype @Override ^
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:19: error: cannot find symbol if (name.equals(MmkvPlatformContextModule.NAME)) { ^ symbol: variable NAME location: class MmkvPlatformContextModule
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:20: error: incompatible types: MmkvPlatformContextModule cannot be converted to NativeModule return new MmkvPlatformContextModule(reactContext); ^
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:31: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:33: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule
> .../node_modules/react-native-mmkv/android/src/main/java/com/mrousavy/mmkv/MmkvPackage.java:34: error: cannot find symbol MmkvPlatformContextModule.NAME, ^ symbol: variable NAME location: class MmkvPlatformContextModule
> ```

Can you confirm you are running new architecture.  The item that sticks out in that message is cannot be converted to NativeModule.  The 3.x line is a turbo module for the new architecture.  If you have not enabled new architecture you need to continue with the 2.x line

**Comment by catarinadasilva** [comment]
I see, yes, in fact, I can't run the Android with the new architecture because there are libraries that do not support it yet, I've rollbacked to v2 and got working again, but would like to have all libs updated to the latest version to avoid the issues I've currently that almost all libs were outdated... (PS: on iOS everything works with the new architecture 🤔)

Thanks for the help.
