### ISSUE TITLE
Blocking Synchronous method vs cpp code

### ISSUE THREAD

**Issue by madhus1025** [mrousavy/react-native-mmkv#740]
Hi All,

We can write a method in java like below

  @ReactMethod(isBlockingSynchronousMethod = true)
  public String getString(String key) {
    return sharedPreferences.getString(key, "");
  }
  
  Which is a synchronous way for accessing, for react native mmkv we have used c++ library and we do the same sync fetching.
  
  What is the difference between using these way ?

**Comment by mrousavy** [comment]
Mainly performance.

`@ReactMethod(isBlockingSynchronousMethod = true)` on the bridge used to lock down two threads and synchronize them - which was much slower than just directly calling something on the JS Thread.

In a TurboModule, I think this is now a bit more similar in terms of implementation.

But still, react-native-mmkv uses C++ so it does not go through Java (JNI) at all, which is much faster.
