### ISSUE TITLE
react-native-mmkv failing on fastlane build

### ISSUE THREAD

**Issue by xcboi2k** [mrousavy/react-native-mmkv#749]
i am encountering build failure when i am building my ios app, here is the build error:

`❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:25:43)

  23 | using MMKVConfig =
  24 |     NativeMmkvConfiguration<std::string, std::optional<std::string>, std::optional<std::string>,
> 25 |                             std::optional<NativeMmkvMode>>;
     |                                           ^ use of undeclared identifier 'NativeMmkvMode'
  26 | template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
  27 | 
  28 | // The TurboModule itself

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:26:29)

  24 |     NativeMmkvConfiguration<std::string, std::optional<std::string>, std::optional<std::string>,
  25 |                             std::optional<NativeMmkvMode>>;
> 26 | template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
     |                             ^ use of undeclared identifier 'MMKVConfig'
  27 | 
  28 | // The TurboModule itself
  29 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:26:75)

  24 |     NativeMmkvConfiguration<std::string, std::optional<std::string>, std::optional<std::string>,
  25 |                             std::optional<NativeMmkvMode>>;
> 26 | template <> struct Bridging<MMKVConfig> : NativeMmkvConfigurationBridging<MMKVConfig> {};
     |                                                                           ^ use of undeclared identifier 'MMKVConfig'
  27 | 
  28 | // The TurboModule itself
  29 | class NativeMmkvModule : public NativeMmkvCxxSpec<NativeMmkvModule> {

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.h:35:49)

  33 | 
  34 |   bool initialize(jsi::Runtime& runtime, std::string basePath);
> 35 |   jsi::Object createMMKV(jsi::Runtime& runtime, MMKVConfig config);
     |                                                 ^ unknown type name 'MMKVConfig'
  36 | };
  37 | 
  38 | } // namespace facebook::react

❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:20:41)

  18 | class MmkvHostObject : public jsi::HostObject {
  19 | public:
> 20 |   MmkvHostObject(const facebook::react::MMKVConfig& config);
     |                                         ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  21 |   ~MmkvHostObject();
  22 | 
  23 | public:

❌  (node_modules/react-native-mmkv/cpp/MmkvHostObject.h:28:54)

  26 | 
  27 | private:
> 28 |   static MMKVMode getMMKVMode(const facebook::react::MMKVConfig& config);
     |                                                      ^ no type named 'MMKVConfig' in namespace 'facebook::react'
  29 | 
  30 | private:
  31 |   MMKV* instance;

❌  (node_modules/react-native-mmkv/cpp/NativeMmkvModule.cpp:38:65)

  36 | NativeMmkvModule::~NativeMmkvModule() {}
  37 | 
> 38 | jsi::Object NativeMmkvModule::createMMKV(jsi::Runtime& runtime, MMKVConfig config) {
     |                                                                 ^ unknown type name 'MMKVConfig'
  39 |   auto instance = std::make_shared<MmkvHostObject>(config);
  40 |   return jsi::Object::createFromHostObject(runtime, instance);
  41 | }`
  
  how to fix this issue?

**Comment by mrousavy** [comment]
You need to be on latest RN (75/76) and have new architecture enabled.

**Comment by wcastand** [comment]
i feel like 3.0.2 should have been a v4 or at least 3.1.0
it break on a patch most current build since it requires the new architecture and latest react.
