### ISSUE TITLE
Error setting `mode` as multi_process

### ISSUE THREAD

**Issue by erickriva** [mrousavy/react-native-mmkv#750]
Version: 3.0.2
OS: Android 14
Using new architecture

```
Error: Value is a number, expected a String
```

when using

```js
import { MMKV, Mode } from "react-native-mmkv";
const database = new MMKV({ mode: Mode.MULTI_PROCESS });
```

Setting `mode` to `MULTI_PROCESS` (as a string) makes it work, but `Mode` enum is expected so Typescript complains.

**Comment by mrousavy** [comment]
Interesting. I'm guessing this is a codegen bug

**Comment by mrousavy** [comment]
fixed in https://github.com/mrousavy/react-native-mmkv/pull/754 🔥
