### ISSUE TITLE
Remove banner images from react native.

### ISSUE THREAD

**Issue by danish5454** [mrousavy/react-native-mmkv#752]
**img** folder which takes `2.44MB` storage.

<img width="379" alt="Screenshot 2024-10-21 at 11 31 26 AM" src="https://github.com/user-attachments/assets/6ded8874-ff47-4f72-9acd-e6b3e224f955">

**Comment by danish5454** [comment]
Have a look on img folder size.

![Screenshot 2024-10-21 at 11 35 44 AM](https://github.com/user-attachments/assets/f571d259-8307-4558-8f48-38c8dbd8529f)

**Comment by mrousavy** [comment]
This is already done. https://github.com/mrousavy/react-native-mmkv/commit/12c051704e0db363f9f63d2b30dbf291151f90d4

**Comment by danish5454** [comment]
@mrousavy Is there a way to remove banner images in `V2` ?

**Comment by jasongaare** [comment]
@danish5454 I believe you could accomplish it in `V2` using patch-package
