### ISSUE TITLE
react-native-mmkv v3 is not compatible with expo bare work flow

### ISSUE THREAD

**Issue by NickeNicrad** [mrousavy/react-native-mmkv#755]
Execution failed for task ':react-native-mmkv:generateCodegenSchemaFromJavaScript'.

**Comment by mrousavy** [comment]
this is not enough info, no build logs no repro no versions no nothing.

**Comment by amutsch** [comment]
Still doesn't help, best guess is you need v2 because you aren't using new architecture

**Comment by NickeNicrad** [comment]
Hello Amutsch,

Hope you are doing well,

I tried to downgrade it back to 2.12.2 and I worked well on ios but on
android, it couldn't event build

**Comment by amutsch** [comment]
You need to provide versions and build logs, We can't even begin to help you with what you have provided.

**Comment by NickeNicrad** [comment]
Here is the error I'm getting on android terminal

* What went wrong:
Execution failed for task ':react-native-mmkv:writeDebugAarMetadata'.
> Failed to create parent directory
'/Users/jackblack/Desktop/nyota-v1/node_modules/react-native-mmkv/android/build'
when creating directory
'/Users/jackblack/Desktop/nyota-v1/node_modules/react-native-mmkv/android/build/intermediates/aar_metadata/debug'


and on ios:

Installing
global.mmkvCreateNewInstance...
[Nyota.debug.dylib] [I]
<MMKV.cpp:167::initialize> version v2.0.0, page
size 16384, arch arm64-v8a
[Nyota.debug.dylib] [I]
<MMKV.cpp:219::initializeMMKV> Apple Device: 0,
version: 64, mlock enabled: 0
[Nyota.debug.dylib] [I]
<MMKV.cpp:228::initializeMMKV> root dir:
/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv
[Nyota.debug.dylib] Installed
global.mmkvCreateNewInstance!
[Nyota.debug.dylib] [D] <libMMKV.mm:927::+[MMKV
mmapKeyWithMMapID:rootPath:]> mmapKey:
mmkv.default
[Nyota.debug.dylib] [I]
<MemoryFile.cpp:101::open> open fd[0x13], flag
7,
/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default
[Nyota.debug.dylib] [I]
<MemoryFile.cpp:215::mmap> mmap to address
[0x100a68000], oldPtr [0x0],
[/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default]
[Nyota.debug.dylib] [I]
<MemoryFile_OSX.cpp:35::tryResetFileProtection>
protection on
[/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default]
is (null)
[Nyota.debug.dylib] [I]
<MemoryFile.cpp:101::open> open fd[0x14], flag
7,
/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default.crc
[Nyota.debug.dylib] [I]
<MemoryFile.cpp:215::mmap> mmap to address
[0x1018f0000], oldPtr [0x0],
[/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default.crc]
[Nyota.debug.dylib] [I]
<MemoryFile_OSX.cpp:35::tryResetFileProtection>
protection on
[/Users/jackblack/Library/Developer/CoreSimulator/Devices/1CC868F1-5FD7-42F5-AAB2-1EA50DCA4B5E/data/Containers/Data/Application/310AF894-8604-44E2-A39A-592584FF09FA/Documents/mmkv/mmkv.default.crc]
is (null)

**Comment by amutsch** [comment]
Failing to create a directory is not usually a problem with the library, it is typically permissions on the os/folder structure

**Comment by NickeNicrad** [comment]
Ok, thanks for the clarification.
