### ISSUE TITLE
Does react-native-mmkv 3.1.0 can support react-native-web directly without extra webpack config?

### ISSUE THREAD

**Issue by chinamcafee** [mrousavy/react-native-mmkv#761]
When I use react-native-mmkv 3.1.0 in  react-native-web with Electron environment, I got some error:
![image](https://github.com/user-attachments/assets/dae3b8c4-4048-4d92-85ff-bbda0a51da9e)

But when I add extra configuration in webpack cofig as follows, react-native-mmkv 3.1.0 can works well with my project:
`
   config.resolve.alias = {
    'react-native-mmkv': 'react-native-mmkv/lib/commonjs',
  }
`

And when I downgrade to react-native-mmkv 2.12.2, my project dosen't need to add alias config above and works well.

Is it necessary to add the additional configuration options when using react-native-mmkv version 3.1.0?

The packages version I use in my project are as follows:
"react-native-mmkv": "3.1.0",  or "react-native-mmkv": "2.12.2",
"react-native-web": "~0.19.13",
"expo": "^52.0.6",
"react-native": "0.76.1",
"electron": "33.2.0",
"webpack": "5.92.1"

**Comment by chinamcafee** [comment]
@mrousavy This is not a pressing matter, but I would appreciate it if you could answer this question when you have some free time.

**Comment by amutsch** [comment]
@chinamcafee I'm taking a look at this as webpack will work with the RN-web alias and throw some errors that are ignored but Vite will not build even with the alias

**Comment by amutsch** [comment]
This should be resolved in the next release
