### ISSUE TITLE
Compilation fails with React Native 0.73 and Gradle 8.1

### ISSUE THREAD

**Issue by Elanthingal** [mrousavy/react-native-mmkv#763]
### Environment

React Native version: 0.73.0
react-native-mmkv version: 3.0.2 (tried 3.1.0)
Android Gradle Plugin: 8.1.0
Gradle: 8.1
Node version: 18.2
Operating System: Windows 

### Error
`
> Configure project :react-native-mmkv
[react-native-mmkv] Thank you for using react-native-mmkv ??     
[react-native-mmkv] If you enjoy using react-native-mmkv, please 
consider sponsoring this project: https://github.com/sponsors/mrousavy

> Configure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3

> Task :react-native-mmkv:compileDebugJavaWithJavac FAILED
 `

**Comment by Elanthingal** [comment]
@mrousavy

**Comment by amutsch** [comment]
You didn't provide enough of the error log to diagnose what is going on with it,  The 3.x.x line requires new architecture enabled so make sure you have that
