### ISSUE TITLE
Store and refresh JWT using MMKV in JS and Java

### ISSUE THREAD

**Issue by crystalrock627** [mrousavy/react-native-mmkv#769]
I need to securely store my JWT token in MMKV from JavaScript and access it from Java for certain requests. Additionally, I want to refresh the token in Java and update it back in MMKV, ensuring seamless synchronization between JavaScript and Java.

Does anyone have suggestions or examples of how to  implement this setup? Specifically:
How to set a value to MMKV from JS and retrieve it in Java, and vice versa?
Looking forward to any insights or best practices for this integration!

**Comment by mrousavy** [comment]
Use a native module (or a Nitro Module) to pass it to Java.

**Comment by crystalrock627** [comment]
can you please give an example
