### ISSUE TITLE
setting boolean value is always storing as undefined

### ISSUE THREAD

**Issue by AnkurMagan-Blankspace** [mrousavy/react-native-mmkv#775]
I am trying to save a boolean value and tried using `set` and `useMMKVBoolean` but in both cases value is being stored as undefined:

### Storage instance
```
import { MMKV } from 'react-native-mmkv'

export const storage = new MMKV({
  id: 'cheese-storage',
})
```

### Usage

```
export const useValidateAccount = () => {
  const { mutate, isPending } = useMutation({
    mutationKey: ['validateUser'],
    mutationFn: validateAccount,
    onSuccess: data => {
      storage.set('validation-token', data.data.validatetoken)
      storage.set('first-time-user', data.data.first_time_user)
    },
  })

  return { mutate, isPending }
}
```

Note: It works as expected when I try to save it as string instead of boolean

<img width="552" alt="Screenshot 2024-12-03 at 11 49 28 PM" src="https://github.com/user-attachments/assets/cf2565eb-204b-419d-afe7-e6f8095d46b7">

 "react-native-mmkv": "^3.1.0",
 "react-native": "0.76.1",
 platform: iOS

**Comment by mrousavy** [comment]
Hey - I just tried to reproduce this and for me it works.

```ts
const storage = new MMKV()
storage.set('somebool', true)
console.log(storage.getBoolean('somebool')) // true
```

I think it is your `useMutation` hook that might be writing/reading booleans wrong.
