### ISSUE TITLE
2.12.2 Error: Failed to create a new MMKV instance in old architecure and bridgless

### ISSUE THREAD

**Issue by itsramiel** [mrousavy/react-native-mmkv#779]
My react native app is on 0.76.3 running old arch and bridgeless. Using v2.12.2 throws the following error:
```
Error: Failed to create a new MMKV instance: React Native is not running on-device. MMKV can only be used when synchronous method invocations (JSI) are possible. If you are using a remote debugger (e.g. Chrome), switch to an on-device debugger (e.g. Flipper) instead.
```

which comes from:
https://github.com/mrousavy/react-native-mmkv/blob/6682adfbd9b0ccb35b50cc1063ca31e569cdc34b/src/createMMKV.ts#L49-L53

[Repo](https://github.com/itsramiel/MMKVError)
Suggested solution: #778

**Comment by itsramiel** [comment]
Yes I am aware when this error happens but I am not running in a debugger. There is a pr with the suggested solution.
@mrousavy please take a look per:
> Note: If you think I made a mistake, please ping @mrousavy to take a look.

**Comment by hachem-benamor** [comment]
> According to Marc, this is not planned to be fixed. Check [reply here](https://github.com/mrousavy/react-native-mmkv/pull/778#issuecomment-2531387485)
> 
> I guess patching the lib is the way to go here unfortunately.

Do you have any alternative, or what the patch should be so we can work around this? 
Thank you!

**Comment by wsx98456** [comment]
saddened to hear this. I have to use the old architecture for certain reasons, and even following itsramiel method couldn't resolve the issue. I hope MMKV won't abandon users who have to stick with the old architecture.
Does anyone have any alternative?

**Comment by mrousavy** [comment]
> I hope MMKV won't abandon users who have to stick with the old architecture.

It's not about me _wanting_ to leave users behind - it's simply a better way of doing things. It would require tons of hours of effort to make this backwards compatible, and the new way is just better, simpler and more efficient.
