### ISSUE TITLE
synchronous not delete all my keys

### ISSUE THREAD

**Issue by tamacroft** [mrousavy/react-native-mmkv#78]
i have an example code : 

`let keys = MMKV.getAllKeys();`
  `keys.forEach(item => {
    MMKV.delete(item)
  });`
  
  but it's not delete all keys? how to fix that?

**Comment by mrousavy** [comment]
What do you mean it does not delete all keys? Can you log the keys before that code and afterwards?

**Comment by tamacroft** [comment]
> 
> 
> What do you mean it does not delete all keys? Can you log the keys before that code and afterwards?



in my case, i have key ex: `user` and this key is filled / has a value, I want to clear/delete this key like `AsyncStorage.removeItem('user')` in mmkv, but in this case my key still have a value.

Using `MMKV.delete('user')` still `user` have a value,

**Comment by mrousavy** [comment]
I just [released MMKV v1.2.0](https://github.com/mrousavy/react-native-mmkv/releases/tag/v1.2.0) which includes `MMKV.deleteAllKeys()`. Try that instead.

**Comment by dancixx** [comment]
The  `deleteAllKeys` method doesn't exist in typedef. Can you update it? :)
