### ISSUE TITLE
Issue on v3 with XCode

### ISSUE THREAD

**Issue by nitrique** [mrousavy/react-native-mmkv#782]
Hi,

First of all, here is my RN Version : 0.74.5

I was setting-up rn-mmkv on a new project and got an issue,
when I tried to build in XCode I got the following errors:

<img width="664" alt="image" src="https://github.com/user-attachments/assets/92a804bc-388f-4bed-a423-3b1325c605b7" />

When downgrading to V2, I figured out that the pod install was slightly different

```
Installing MMKV (2.0.0)
Installing MMKVCore (2.0.0)
Installing react-native-mmkv 2.12.2 (was 3.1.0)
```

When going back to V3 here is the pod install:

```
Installing react-native-mmkv 3.2.0 (was 2.12.2)
Removing MMKV
Removing MMKVCore
```

Best,
Nicolas

**Comment by mrousavy** [comment]
you need to upgrade to RN 75 afaik

**Comment by nitrique** [comment]
Sorry I didn't see it in the doc, looks like I need vacation...
