### ISSUE TITLE
Does v3.x support in both native and React Native on the iOS platform?

### ISSUE THREAD

**Issue by wbees** [mrousavy/react-native-mmkv#783]
The 3.x version of react-native-mmkv uses mmkv-core, while the 2.x version depends directly on the MMKV library, which includes iOS platform code.

How can MMKV be used on both the native side and React Native simultaneously in version 3.x? If add the mmkv pod on iOS, there will be duplicate code from mmkv-core.

**Comment by wbees** [comment]
1. package.json add the react-native-mmkv
2. podfile add the pod 'MMKV'

In the file list we can see the Core related files is both in react-native-mmkv and MMKV. Build project can success, but would be crash when running.  The 3 call 2 is from react-native-mmkv/MMKV/Core/MiniPBCoder.cpp to MMKVCore/Core/CodedInputData.cpp. 
`#0    0x0000000104c1add1 in mmkv::CodedInputData::readRawByte() at Project/ios/Pods/MMKVCore/Core/CodedInputData.cpp:246
#1    0x0000000104c1ae79 in mmkv::CodedInputData::readRawVarint32() at Project/ios/Pods/MMKVCore/Core/CodedInputData.cpp:184
#2    0x0000000104c1b36d in mmkv::CodedInputData::readData(mmkv::KeyValueHolder&) at Project/ios/Pods/MMKVCore/Core/CodedInputData.cpp:167
#3    0x0000000105c26f25 in mmkv::MiniPBCoder::decodeOneMap(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, mmkv::KeyValueHolder, mmkv::KeyHasher, mmkv::KeyEqualer, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, mmkv::KeyValueHolder>>>&, unsigned long, bool)::$_0::operator()(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, mmkv::KeyValueHolder, mmkv::KeyHasher, mmkv::KeyEqualer, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, mmkv::KeyValueHolder>>>&) const at Project/node_modules/react-native-mmkv/MMKV/Core/MiniPBCoder.cpp:517
#4    0x0000000105c26d4b in mmkv::MiniPBCoder::decodeOneMap(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, mmkv::KeyValueHolder, mmkv::KeyHasher, mmkv::KeyEqualer, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, mmkv::KeyValueHolder>>>&, unsigned long, bool) at Project/node_modules/react-native-mmkv/MMKV/Core/MiniPBCoder.cpp:541
#5    0x0000000105c27ce0 in mmkv::MiniPBCoder::decodeMap(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, mmkv::KeyValueHolder, mmkv::KeyHasher, mmkv::KeyEqualer, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, mmkv::KeyValueHolder>>>&, mmkv::MMBuffer const&, unsigned long) at Project/node_modules/react-native-mmkv/MMKV/Core/MiniPBCoder.cpp:650
#6    0x0000000105c41f4b in MMKV::loadFromFile() at Project/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:112
#7    0x0000000105c43482 in MMKV::checkLoadData() at Project/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:307
#8    0x0000000105c44e40 in MMKV::getRawDataForKey(std::__1::basic_string_view<char, std::__1::char_traits<char>>) at Project/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:545
#9    0x0000000105c45087 in MMKV::getDataForKey(std::__1::basic_string_view<char, std::__1::char_traits<char>>) at Project/node_modules/react-native-mmkv/MMKV/Core/MMKV_IO.cpp:570
#10   0x0000000105c356d4 in MMKV::getString(std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, bool) at Project/node_modules/react-native-mmkv/MMKV/Core/MMKV.cpp:702
#11   0x0000000105c5cc8b in MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const at Project/node_modules/react-native-mmkv/cpp/MmkvHostObject.cpp:204
#12   0x0000000105c5cb26 in decltype(std::declval<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3&>()(std::declval<facebook::jsi::Runtime&>(), std::declval<facebook::jsi::Value const&>(), std::declval<facebook::jsi::Value const*>(), std::declval<unsigned long>())) std::__1::__invoke[abi:ue170006]<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:340
#13   0x0000000105c5cab0 in facebook::jsi::Value std::__1::__invoke_void_return_wrapper<facebook::jsi::Value, false>::__call[abi:ue170006]<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:407
#14   0x0000000105c5ca60 in std::__1::__function::__alloc_func<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3, std::__1::allocator<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()[abi:ue170006](facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/c++/v1/__functional/function.h:193
#15   0x0000000105c5ba64 in std::__1::__function::__func<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3, std::__1::allocator<MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/c++/v1/__functional/function.h:364
`

**Comment by mrousavy** [comment]
You identified the problem correctly, I use MMKV from source, not the CocoaPod.

It's not directly supported to use MMKV in native code like this now.

You either have to also use the C++ library, or do everything through JS.

This decision was necessary to gain better performance and more lightweight and simpler code.

**Comment by tgreco** [comment]
@mrousavy will you be changing to using the objc wrapper soon?

https://github.com/Tencent/MMKV/issues/1512#issuecomment-2786106714

**Comment by mrousavy** [comment]
Why would I? Switching from C++ to ObjC is slower.

**Comment by midmirror** [comment]
> Why would I? Switching from C++ to ObjC is slower.

This approach will cause iOS to be unable to use the native MMKV after integrating React Native into the iOS project
