### ISSUE TITLE
Build issue on iOS

### ISSUE THREAD

**Issue by oferRounds** [mrousavy/react-native-mmkv#85]
Using react-native 0.63.4

Any idea how to fix it? Perhaps it’s related to the fact my project does not use Flipper?

![image](https://user-images.githubusercontent.com/1477963/123243034-4bdb5300-d4eb-11eb-9c82-d51de893cc5b.png)
![image](https://user-images.githubusercontent.com/1477963/123243077-585fab80-d4eb-11eb-96e0-92b58df06ef0.png)

**Comment by oferRounds** [comment]
Perhaps it’s due to the fact my pod file includes `use_frameworks!`?

**Comment by mrousavy** [comment]
Are you using Apple Silicone (M1 chip)? Can you build the example app?

**Comment by oferRounds** [comment]
Ahmmm, yes, I use the Apple Silicone (M1 chip), can this be related?

**Comment by kanzitelli** [comment]
hey guys @oferRounds @mrousavy 

I started getting this error when I turned `hermes` engine `off` in Pods.

![Screenshot 2021-06-25 at 03 46 52](https://user-images.githubusercontent.com/4402166/123356597-4839e180-d568-11eb-9742-fe44a95b05ac.png)

And also, I couldn't make the project run when I was using `use_frameworks!` and `hermes` engine `on`. Some libraries, like `@react-native-community/netinfo` and `react-native-fbsdk-next`, couldn't import `hermes.h` and something like that. If anybody knows why it happens could you share an explanation? 😅

**Comment by oferRounds** [comment]
Hi @kanzitelli, thanks for this! I actually still on react-native 0.63, so hermes is not available for me
But as you said, it seems to me that the `use_frameworks!` is the one causing the issues

**Comment by kanzitelli** [comment]
@oferRounds yes, unfortunately. I could only make my project run by removing `react-native-mmkv` and using regular `AsyncStorage` :(

as I understand, `react-native-mmkv` is based on JSI which is getting broken after using `use_framework!`. Also it was breaking some Pods which had `s.dependency 'React'` in `.podspec` file. But it has to be `s.dependency 'React-Core'`.

**Comment by oferRounds** [comment]
@brod-ie nice! Thank you! Will try

**Comment by brod-ie** [comment]
@oferRounds Even simpler! [Updated my comment](https://github.com/mrousavy/react-native-mmkv/issues/85#issuecomment-982747100) 😀

**Comment by oferRounds** [comment]
OMG thank you!!! Will soon check and update

**Comment by mrousavy** [comment]
Let me know if v2.0.0 still has that error :)

**Comment by felixSchl** [comment]
There is a simpler fix which does not require installing a plugin:

```
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('react-native-mmkv')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```

Put this in the block defining the pod somewhere under the `use_frameworks!` call.

**Comment by tkmin** [comment]
> There is a simpler fix which does not require installing a plugin:
> 
> ```ruby
>   pre_install do |installer|
>     installer.pod_targets.each do |pod|
>       if pod.name.eql?('react-native-mmkv')
>         def pod.build_type;
>           Pod::BuildType.static_library
>         end
>       end
>     end
>   end
> ```
> 
> Put this in the block defining the pod somewhere under the `use_frameworks!` call.

exactly where should I put those codes..? still getting build error

```
$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'fondee' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )



  target 'fondeeTests' do
    use_frameworks!
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

end
```
