### ISSUE TITLE
Error: Exception in HostFunction: Second argument ('key') has to be of type string!

### ISSUE THREAD

**Issue by KingAmo** [mrousavy/react-native-mmkv#9]
bellow code:
```
MMKV.set('key', 123)
```
throw an error.

after swap key and value, it is ok
it seems v1.0.2 key-value order  go back  to RTL, not LTR

**Comment by mrousavy** [comment]
Looks like it still uses the old binaries, could you try cleaning the cache?

```
rm -rf node_modules/react-native-mmkv
rm -rf package-lock.json
npm i
```

**Comment by mrousavy** [comment]
If it happens on iOS, try

```
cd ios
rm -rf Pods
rm -rf Podfile.lock
pod install
```

Then rebuild

**Comment by mrousavy** [comment]
Feel free to comment if you're still experiencing this issue, closing for now

**Comment by BLOCKMATERIAL** [comment]
same bug but with boolean type
platofrm: IOS 
devices: Iphone 14 Pro Max
